/*
 Copyright (c) 2014, Raonwiz Technology Inc. All rights reserved.
*/
window.DEXT5UPLOAD||(window.DEXT5UPLOAD=function(){var b=window.DEXT5UPLOAD_ROOTPATH||"";if(!b)for(var c=document.getElementsByTagName("script"),a=c.length,d=null,e=0;e<a;e++)if(d=c[e],d=d.src.match(/(^|.*[\\\/])dext5upload.js/i)){b=d[1];break}-1==b.indexOf(":/")&&(b=0===b.indexOf("/")?location.href.match(/^.*?:\/\/[^\/]*/)[0]+b:location.href.match(/^[^\?]*\/(?:)/)[0]+b);b=b.substring(0,b.length-1);b=b.substring(0,b.lastIndexOf("/"))+"/";if(!b)throw"DEXT5 Upload installation path could not be automatically detected.";
return{isRelease:!0,isPopUpCssLoaded:!1,version:"DEXT5 Upload",ReleaseVer:"2.7.1124270.1349.01",ServerReleaseVer:"",cabVersion:"5,0,0,15",rootPath:b,DEXTMULTIPLE:{},DEXTHOLDER:{},DEXTMULTIPLEID:[]}}(),DEXT5UPLOAD.brower||(DEXT5UPLOAD.browser=function(){var b=navigator.userAgent.toLowerCase(),c=window.opera,c={ie:-1<b.search("trident")||-1<b.search("msie")||-1<b.search("edge/12")||-1<b.search("edge/13")?!0:!1,edge:-1<b.search("edge/12")||-1<b.search("edge/13")?!0:!1,opera:!!c&&c.version,webkit:-1<
b.indexOf(" applewebkit/"),mac:-1<b.indexOf("macintosh"),quirks:"BackCompat"==document.compatMode,mobile:-1<b.indexOf("mobile"),iOS:/(ipad|iphone|ipod)/.test(b),isCustomDomain:function(a){if(!this.ie)return!1;var b=a.domain;a=DEXT5UPLOAD.util.getDocWindow(a).location.hostname;return b!=a&&b!="["+a+"]"},isHttps:"https:"==location.protocol,HTML5Supported:!0,HTML5PlusSupported:!1,ajaxOnProgressSupported:!1};c.gecko="Gecko"==navigator.product&&!c.webkit&&!c.opera;c.ie&&(c.gecko=!1);c.webkit&&(-1<b.indexOf("chrome")?
(c.chrome=!0,-1<b.indexOf("opr")&&(c.opera=!0,c.chrome=!1)):c.safari=!0);var a;c.ieVersion=0;c.ie&&(c.quirks||!document.documentMode?-1<b.indexOf("msie")?a=parseFloat(b.match(/msie (\d+)/)[1]):-1<b.indexOf("trident")?a=parseFloat(b.match(/rv:([\d\.]+)/)[1]):-1<b.indexOf("edge/12")||-1<b.indexOf("edge/13")?(a=12,c.chrome=!1):a=7:a=document.documentMode,c.ieVersion=a,c.ie12=12==a,c.ie11=11==a,c.ie10=10==a,c.ie9=9==a,c.ie8=8==a,c.ie7=7==a,c.ie6=7>a||c.quirks);c.gecko&&(a=b.match(/rv:([\d\.]+)/))&&(a=
a[1].split("."),a=1E4*a[0]+100*(a[1]||0)+1*(a[2]||0));c.webkit&&(a=parseFloat(b.match(/ applewebkit\/(\d+)/)[1]));c.HTML5Supported="File"in window&&"FileReader"in window&&"Blob"in window;c.HTML5PlusSupported="File"in window&&"FileReader"in window&&"Blob"in window&&("WebSocket"in window||"MozWebSocket"in window);c.WorkerSupported="Worker"in window;c.imageProcessWorkerSupported="Worker"in window;b=null;try{b=new XMLHttpRequest,c.ajaxOnProgressSupported=!!(b&&"upload"in b&&"onprogress"in b.upload)}catch(d){c.ajaxOnProgressSupported=
!1}b=null;return c}()),DEXT5UPLOAD.UserAgent||(DEXT5UPLOAD.UserAgent=function(){var b=window&&window.navigator&&window.navigator.userAgent?window.navigator.userAgent:"",c={extend:function(a,b){for(var c in b)-1!=="browser cpu device engine os".indexOf(c)&&0===b[c].length%2&&(a[c]=b[c].concat(a[c]));return a},has:function(a,b){return"string"===typeof a?-1!==b.toLowerCase().indexOf(a.toLowerCase()):!1},lowerize:function(a){return a.toLowerCase()},major:function(a){return"string"===typeof a?a.split(".")[0]:
void 0}},a=function(){for(var a,c=0,d,e,h,k,x,p,z=arguments;c<z.length&&!x;){var B=z[c],A=z[c+1];if("undefined"===typeof a)for(h in a={},A)k=A[h],"object"===typeof k?a[k[0]]=void 0:a[k]=void 0;for(d=e=0;d<B.length&&!x;)if(x=B[d++].exec(b))for(h=0;h<A.length;h++)p=x[++e],k=A[h],"object"===typeof k&&0<k.length?2==k.length?a[k[0]]="function"==typeof k[1]?k[1].call(this,p):k[1]:3==k.length?a[k[0]]="function"!==typeof k[1]||k[1].exec&&k[1].test?p?p.replace(k[1],k[2]):void 0:p?k[1].call(this,p,k[2]):void 0:
4==k.length&&(a[k[0]]=p?k[3].call(this,p.replace(k[1],k[2])):void 0):a[k]=p?p:void 0;c+=2}return a},d=function(a,b){for(var d in b)if("object"===typeof b[d]&&0<b[d].length)for(var e=0;e<b[d].length;e++){if(c.has(b[d][e],a))return"?"===d?void 0:d}else if(c.has(b[d],a))return"?"===d?void 0:d;return a},e={ME:"4.90","NT 3.11":"NT3.51","NT 4.0":"NT4.0",2E3:"NT 5.0",XP:["NT 5.1","NT 5.2"],Vista:"NT 6.0",7:"NT 6.1",8:"NT 6.2","8.1":"NT 6.3",10:["NT 6.4","NT 10.0"],RT:"ARM"},h=[[/\((ipad|playbook);[\w\s\);-]+(rim|apple)/i],
["model","vendor",["type","tablet"]],[/applecoremedia\/[\w\.]+ \((ipad)/],["model",["vendor","Apple"],["type","tablet"]],[/(apple\s{0,1}tv)/i],[["model","Apple TV"],["vendor","Apple"]],[/(archos)\s(gamepad2?)/i,/(hp).+(touchpad)/i,/(kindle)\/([\w\.]+)/i,/\s(nook)[\w\s]+build\/(\w+)/i,/(dell)\s(strea[kpr\s\d]*[\dko])/i],["vendor","model",["type","tablet"]],[/(kf[A-z]+)\sbuild\/[\w\.]+.*silk\//i],["model",["vendor","Amazon"],["type","tablet"]],[/(sd|kf)[0349hijorstuw]+\sbuild\/[\w\.]+.*silk\//i],[["model",
d,{"Fire Phone":["SD","KF"]}],["vendor","Amazon"],["type","mobile"]],[/\((ip[honed|\s\w*]+);.+(apple)/i],["model","vendor",["type","mobile"]],[/\((ip[honed|\s\w*]+);/i],["model",["vendor","Apple"],["type","mobile"]],[/(blackberry)[\s-]?(\w+)/i,/(blackberry|benq|palm(?=\-)|sonyericsson|acer|asus|dell|huawei|meizu|motorola|polytron)[\s_-]?([\w-]+)*/i,/(hp)\s([\w\s]+\w)/i,/(asus)-?(\w+)/i],["vendor","model",["type","mobile"]],[/\(bb10;\s(\w+)/i],["model",["vendor","BlackBerry"],["type","mobile"]],[/android.+(transfo[prime\s]{4,10}\s\w+|eeepc|slider\s\w+|nexus 7)/i],
["model",["vendor","Asus"],["type","tablet"]],[/(sony)\s(tablet\s[ps])\sbuild\//i,/(sony)?(?:sgp.+)\sbuild\//i],[["vendor","Sony"],["model","Xperia Tablet"],["type","tablet"]],[/(?:sony)?(?:(?:(?:c|d)\d{4})|(?:so[-l].+))\sbuild\//i],[["vendor","Sony"],["model","Xperia Phone"],["type","mobile"]],[/\s(ouya)\s/i,/(nintendo)\s([wids3u]+)/i],["vendor","model",["type","console"]],[/android.+;\s(shield)\sbuild/i],["model",["vendor","Nvidia"],["type","console"]],[/(playstation\s[3portablevi]+)/i],["model",
["vendor","Sony"],["type","console"]],[/(sprint\s(\w+))/i],[["vendor",d,{HTC:"APA",Sprint:"Sprint"}],["model",d,{"Evo Shift 4G":"7373KT"}],["type","mobile"]],[/(lenovo)\s?(S(?:5000|6000)+(?:[-][\w+]))/i],["vendor","model",["type","tablet"]],[/(htc)[;_\s-]+([\w\s]+(?=\))|\w+)*/i,/(zte)-(\w+)*/i,/(alcatel|geeksphone|huawei|lenovo|nexian|panasonic|(?=;\s)sony)[_\s-]?([\w-]+)*/i],["vendor",["model",/_/g," "],["type","mobile"]],[/(nexus\s9)/i],["model",["vendor","HTC"],["type","tablet"]],[/[\s\(;](xbox(?:\sone)?)[\s\);]/i],
["model",["vendor","Microsoft"],["type","console"]],[/(kin\.[onetw]{3})/i],[["model",/\./g," "],["vendor","Microsoft"],["type","mobile"]],[/\s(milestone|droid(?:[2-4x]|\s(?:bionic|x2|pro|razr))?(:?\s4g)?)[\w\s]+build\//i,/mot[\s-]?(\w+)*/i,/(XT\d{3,4}) build\//i],["model",["vendor","Motorola"],["type","mobile"]],[/android.+\s(mz60\d|xoom[\s2]{0,2})\sbuild\//i],["model",["vendor","Motorola"],["type","tablet"]],[/android.+((sch-i[89]0\d|shw-m380s|gt-p\d{4}|gt-n8000|sgh-t8[56]9|nexus 10))/i,/((SM-T\w+))/i],
[["vendor","Samsung"],"model",["type","tablet"]],[/((s[cgp]h-\w+|gt-\w+|galaxy\snexus|sm-n900))/i,/(sam[sung]*)[\s-]*(\w+-?[\w-]*)*/i,/sec-((sgh\w+))/i],[["vendor","Samsung"],"model",["type","mobile"]],[/(samsung);smarttv/i],["vendor","model",["type","smarttv"]],[/\(dtv[\);].+(aquos)/i],["model",["vendor","Sharp"],["type","smarttv"]],[/sie-(\w+)*/i],["model",["vendor","Siemens"],["type","mobile"]],[/(maemo|nokia).*(n900|lumia\s\d+)/i,/(nokia)[\s_-]?([\w-]+)*/i],[["vendor","Nokia"],"model",["type",
"mobile"]],[/android\s3\.[\s\w;-]{10}(a\d{3})/i],["model",["vendor","Acer"],["type","tablet"]],[/android\s3\.[\s\w;-]{10}(lg?)-([06cv9]{3,4})/i],[["vendor","LG"],"model",["type","tablet"]],[/(lg) netcast\.tv/i],["vendor","model",["type","smarttv"]],[/(nexus\s[45])/i,/lg[e;\s\/-]+(\w+)*/i],["model",["vendor","LG"],["type","mobile"]],[/android.+(ideatab[a-z0-9\-\s]+)/i],["model",["vendor","Lenovo"],["type","tablet"]],[/linux;.+((jolla));/i],["vendor","model",["type","mobile"]],[/((pebble))app\/[\d\.]+\s/i],
["vendor","model",["type","wearable"]],[/android.+;\s(glass)\s\d/i],["model",["vendor","Google"],["type","wearable"]],[/android.+(\w+)\s+build\/hm\1/i,/android.+(hm[\s\-_]*note?[\s_]*(?:\d\w)?)\s+build/i,/android.+(mi[\s\-_]*(?:one|one[\s_]plus)?[\s_]*(?:\d\w)?)\s+build/i],[["model",/_/g," "],["vendor","Xiaomi"],["type","mobile"]],[/(mobile|tablet);.+rv\:.+gecko\//i],[["type",c.lowerize],"vendor","model"]],e=[[/microsoft\s(windows)\s(vista|xp)/i],["name","version"],[/(windows)\snt\s6\.2;\s(arm)/i,
/(windows\sphone(?:\sos)*|windows\smobile|windows)[\s\/]?([ntce\d\.\s]+\w)/i],["name",["version",d,e]],[/(win(?=3|9|n)|win\s9x\s)([nt\d\.]+)/i],[["name","Windows"],["version",d,e]],[/\((bb)(10);/i],[["name","BlackBerry"],"version"],[/(blackberry)\w*\/?([\w\.]+)*/i,/(tizen)[\/\s]([\w\.]+)/i,/(android|webos|palm\sos|qnx|bada|rim\stablet\sos|meego|contiki)[\/\s-]?([\w\.]+)*/i,/linux;.+(sailfish);/i],["name","version"],[/(symbian\s?os|symbos|s60(?=;))[\/\s-]?([\w\.]+)*/i],[["name","Symbian"],"version"],
[/\((series40);/i],["name"],[/mozilla.+\(mobile;.+gecko.+firefox/i],[["name","Firefox OS"],"version"],[/(nintendo|playstation)\s([wids3portablevu]+)/i,/(mint)[\/\s\(]?(\w+)*/i,/(mageia|vectorlinux)[;\s]/i,/(joli|[kxln]?ubuntu|debian|[open]*suse|gentoo|arch|slackware|fedora|mandriva|centos|pclinuxos|redhat|zenwalk|linpus)[\/\s-]?([\w\.-]+)*/i,/(hurd|linux)\s?([\w\.]+)*/i,/(gnu)\s?([\w\.]+)*/i],["name","version"],[/(cros)\s[\w]+\s([\w\.]+\w)/i],[["name","Chromium OS"],"version"],[/(sunos)\s?([\w\.]+\d)*/i],
[["name","Solaris"],"version"],[/\s([frentopc-]{0,4}bsd|dragonfly)\s?([\w\.]+)*/i],["name","version"],[/(ip[honead]+)(?:.*os\s*([\w]+)*\slike\smac|;\sopera)/i],[["name","iOS"],["version",/_/g,"."]],[/(mac\sos\sx)\s?([\w\s\.]+\w)*/i,/(macintosh|mac(?=_powerpc)\s)/i],[["name","Mac OS"],["version",/_/g,"."]],[/((?:open)?solaris)[\/\s-]?([\w\.]+)*/i,/(haiku)\s(\w+)/i,/(aix)\s((\d)(?=\.|\)|\s)[\w\.]*)*/i,/(plan\s9|minix|beos|os\/2|amigaos|morphos|risc\sos|openvms)/i,/(unix)\s?([\w\.]+)*/i],["name","version"]],
d=a.apply(this,[[/(opera\smini)\/([\w\.-]+)/i,/(opera\s[mobiletab]+).+version\/([\w\.-]+)/i,/(opera).+version\/([\w\.]+)/i,/(opera)[\/\s]+([\w\.]+)/i],["name","version"],[/\s(opr)\/([\w\.]+)/i],[["name","Opera"],"version"],[/(kindle)\/([\w\.]+)/i,/(lunascape|maxthon|netfront|jasmine|blazer)[\/\s]?([\w\.]+)*/i,/(avant\s|iemobile|slim|baidu)(?:browser)?[\/\s]?([\w\.]*)/i,/(?:ms|\()(ie)\s([\w\.]+)/i,/(rekonq)\/([\w\.]+)*/i,/(chromium|flock|rockmelt|midori|epiphany|silk|skyfire|ovibrowser|bolt|iron|vivaldi)\/([\w\.-]+)/i],
["name","version"],[/(trident).+rv[:\s]([\w\.]+).+like\sgecko/i],[["name","IE"],"version"],[/(edge)\/((\d+)?[\w\.]+)/i],["name","version"],[/(yabrowser)\/([\w\.]+)/i],[["name","Yandex"],"version"],[/(comodo_dragon)\/([\w\.]+)/i],[["name",/_/g," "],"version"],[/(chrome|omniweb|arora|[tizenoka]{5}\s?browser)\/v?([\w\.]+)/i,/(uc\s?browser|qqbrowser)[\/\s]?([\w\.]+)/i],["name","version"],[/(dolfin)\/([\w\.]+)/i],[["name","Dolphin"],"version"],[/((?:android.+)crmo|crios)\/([\w\.]+)/i],[["name","Chrome"],
"version"],[/XiaoMi\/MiuiBrowser\/([\w\.]+)/i],["version",["name","MIUI Browser"]],[/android.+version\/([\w\.]+)\s+(?:mobile\s?safari|safari)/i],["version",["name","Android Browser"]],[/FBAV\/([\w\.]+);/i],["version",["name","Facebook"]],[/version\/([\w\.]+).+?mobile\/\w+\s(safari)/i],["version",["name","Mobile Safari"]],[/version\/([\w\.]+).+?(mobile\s?safari|safari)/i],["version","name"],[/webkit.+?(mobile\s?safari|safari)(\/[\w\.]+)/i],["name",["version",d,{"1.0":"/8","1.2":"/1","1.3":"/3","2.0":"/412",
"2.0.2":"/416","2.0.3":"/417","2.0.4":"/419","?":"/"}]],[/(konqueror)\/([\w\.]+)/i,/(webkit|khtml)\/([\w\.]+)/i],["name","version"],[/(navigator|netscape)\/([\w\.-]+)/i],[["name","Netscape"],"version"],[/(swiftfox)/i,/(icedragon|iceweasel|camino|chimera|fennec|maemo\sbrowser|minimo|conkeror)[\/\s]?([\w\.\+]+)/i,/(firefox|seamonkey|k-meleon|icecat|iceape|firebird|phoenix)\/([\w\.-]+)/i,/(mozilla)\/([\w\.]+).+rv\:.+gecko\/\d+/i,/(polaris|lynx|dillo|icab|doris|amaya|w3m|netsurf)[\/\s]?([\w\.]+)/i,/(links)\s\(([\w\.]+)/i,
/(gobrowser)\/?([\w\.]+)*/i,/(ice\s?browser)\/v?([\w\._]+)/i,/(mosaic)[\/\s]([\w\.]+)/i],["name","version"]]);d.major=c.major(d.version);e=a.apply(this,e);if(a=a.apply(this,h))void 0==a.model&&(a.model=""),void 0==a.type&&(a.type=""),void 0==a.vendor&&(a.vendor="");return{browser:d,os:e,device:a}}()));
DEXT5UPLOAD.config={InitXml:"",InitServerXml:"",InitVisible:!0,SkinName:"",Width:"",Height:"",Lang:"",KeepLang:"",HeaderBar:"",StatusBar:"",ButtonBar:"",ButtonBarEdit:"",ButtonBarView:"",BorderStyle:"",MaxTotalFileCount:"",MaxTotalFileSize:"",MaxOneFileSize:"",MultiFileSelect:"",ExtensionAllowOrLimit:"",ExtensionArr:"",Mode:"",Views:"",Runtimes:"",RunTimes:"",UseWS:"",FolderNameRule:"",CustomHeaderColor:"",CustomFooterColor:"",CustomProgressBarColor:"",CustomTextColor:"",CustomWebFileColor:"",UploadHolder:"",
ResumeUpload:"",ResumeDownload:"",FolderTransfer:"",FolderDetailHeader:"",UseServerFileSize:"",UseAddEvent:"",UseDeleteEvent:"",UseViewOrOpenEvent:"",UseUploadingCancelEvent:"",UseDownloadEvent:"",UseAfterAddEvent:"",UseAfterAddEndTimeEvent:"",UseAfterDownloadEvent:"",Timeout:"",AutomaticConnection:"",ShowFolderView:"",IgnoreSameUploadName:"0",HandlerUrl:"",WsHandlerUrl:"",WsChunkSize:"",DownloadHandlerUrl:"",MessageTitle:"",UseScriptEventControl:"",DevelopLangage:"",ShowCheckBox:"",HideContextMenu:"",
SizeColumnWidth:"",UnitDelimiter:"",UnitAttributeDelimiter:"",DownloadMulti:"",PluginZipDownload:"",CssRootPath:"",ViewerHandlerUrl:"",UseAutoHeight:"",RemoveContextItem:"",DisableDeleteConfirmMessage:"",DisplayFileSizeHtml4:"",ListViewDbclick:"",ListViewDragAndDrop:"",HideListInfo:"",NTLM:"",LargeFiles:"",CacheProtectMode:"",UseFileSort:"",FileSortField:"",FileSortAscDesc:"",AutoSort:"",ShowEditAlign:"",ShowViewAlign:"",FileMoveContextMenu:"",CompleteEventResetUse:"",ImgPreView:"",ImgPreViewWidth:"",
ImgPreViewHeight:"",StatusBarShowLimit:"",StatusBarShowStatus:"",ButtonBarPosition:"",UserMessage:"",UseSingleSelect:"",DisableAlertMessage:{Duplication:"",DeleteUnchosen:"",DownloadUnchosen:"",OpenUnchosen:"",DisableDeleteConfirm:"",FileExtensionDetect:""},AllowedZeroFileSize:"",ChunkSize:"",FileNameRule:"",FileNameRuleEx:"",AsyncUpload:"",SilentUpload:"",DirectDownload:"",ProductKey:"",LicenseKey:"",LicenseKeyEx:"",EnableThread:"",LicenseKeySE:"",Security:{EncryptParam:"",FileExtensionDetector:"",
FileIntegrity:"",FileEncrypt:"",DeleteOpenFile:""},SizeForChunkUpload:"",UploadMethod:"",HeaderBarItem:"",HeaderBarItemWidth:"",HeaderBarItemAlign:"",WsWorkerCount:"",WsWorkerJobSize:"",WsMinSingleWorkerSize:"",UploadTransferWindow:{View:"",ViewWidth:"",ViewHeight:""},GroupId:"",PluginInstallType:"",DefaultDownloadPath:"",UploadMethodHtml4:"",TransferOpenFile:"",SelectByClicked:"",AftertUpload:{SetFileSize:""},SavePathSetting:"",TransferBackgroundStyle:"",UseDropzone:"",AllowOpenExtension:"",FileFilterEx:"",
ImageQuality:"",UseZipDownload:"",HybridDownload:"",EnforceIePlugin:"",UseInstallGuide:"",HybridWindowMode:"",DialogWindow:null,HybridUseSetCookie:"",HybridMethod:"",AllowedRealtimeDownloadAdd:"",HybridShowItemCount:"",DownloadPartialSize:"",Html4LimitFileSize:""};
DEXT5UPLOAD.ajax=function(){var b=function(){if(!DEXT5UPLOAD.browser.ie||"file:"!=location.protocol){try{return new XMLHttpRequest}catch(a){}try{return new ActiveXObject("Msxml2.XHLHTTP")}catch(b){}try{return new ActiveXObject("Microsoft.XMLHTTP")}catch(c){}}return null},c=function(a){return 4==a.readyState&&(200<=a.status&&300>a.status||304==a.status||0===a.status||1223==a.status)},a=function(a){return c(a)?a.responseText:null},d=function(a){if(c(a)){var b=a.responseXML;return b?b:a.responseText}return null},
e=function(a,c,d){var e=!!c,h=b();if(!h)return null;h.open("GET",a,e);e&&(h.onreadystatechange=function(){4==h.readyState&&(c(d(h)),h=null)});try{h.send(null)}catch(k){return null}setTimeout(function(){e||h.abort()},5E3);return e?"":d(h)},h=function(a,c,d,e){var h=!!d,k=b();if(!k)return null;k.open("POST",a,h);k.setRequestHeader("Content-Type","application/x-www-form-urlencoded;charset=UTF-8");h&&(k.onreadystatechange=function(){4==k.readyState&&(d(e(k,c)),k=null)});try{k.send(c)}catch(x){return null}setTimeout(function(){if(!h)try{k.abort()}catch(a){}},
5E3);return h?"":e(k)};return{load:function(b,c){return e(b,c,a)},loadXml:function(a,b){return e(a,b,d)},postData:function(b,c,d){return h(b,c,d,a)},postFileData:function(a,b){return postFileData(a,b)},createXMLHttpRequest:function(){return b()}}}();
DEXT5UPLOAD.util={G_IMG_LIST:{},trim:function(b){return b.trim?b.trim():b.replace(/^[\s\xa0]+|[\s\xa0]+$/g,"")},getDefaultIframeSrc:function(){var b="",b="document.open();"+(DEXT5UPLOAD.browser.isCustomDomain(document)?'document.domain="'+document.domain+'";':"")+" document.close();";return b=DEXT5UPLOAD.browser.ie?"javascript:void(function(){"+encodeURIComponent(b)+"}())":""},makeIframe:function(){var b;try{b=document.createElement('<iframe frameborder="0" >')}catch(c){b=document.createElement("iframe")}b.style.margin=
"0px";b.style.padding="0px";b.frameBorder=0;b.style.overflow="auto";b.style.overflowX="hidden";b.style.backgroundColor="#ffffff";b.title="DEXT5Upload";b.src=this.getDefaultIframeSrc();return b},addEvent:function(b,c,a,d){b.addEventListener?b.addEventListener(c,a,d):b.attachEvent&&b.attachEvent("on"+c,a)},removeEvent:function(b,c,a,d){b.removeEventListener?b.removeEventListener(c,a,d):b.detachEvent&&b.detachEvent("on"+c,a)},stopEvent:function(b){"bubbles"in b?b.bubbles&&b.stopPropagation():b.cancelBubble=
!0},cancelEvent:function(b){b.preventDefault?b.preventDefault():b.returnValue=!1},ajax:{xml_http_request:function(){var b;window.XMLHttpRequest?b=new XMLHttpRequest:window.ActiveXObject&&(b=new ActiveXObject("Microsoft.XMLHTTP"));return b}},url:{full_url:function(b){var c="";if(0==b.indexOf("http://")||0==b.indexOf("https://"))c=b;else if(0==b.indexOf("/"))c=location.protocol+"//"+location.host+b;else var c=location.href,a=c.lastIndexOf("/"),c=c.substring(0,a+1),c=c+b;return c}},xml:{count:function(b,
c){return b?b.getElementsByTagName(c).length:0},getNode:function(b,c){return null==b||void 0==b?null:this.getNodeIdx(b,c,0)},getNodeIdx:function(b,c,a){return b.getElementsByTagName(c)[a]},getNodeValue:function(b,c){return null==b||void 0==b?"":this.getNodeValueIdx(b,c,0)},getNodeValueIdx:function(b,c,a){b=this.getNodeIdx(b,c,a);return this.getValue(b)},getValue:function(b){var c="",a="";if(void 0!=b)try{0<b.childNodes.length&&(a=c=b.firstChild.nodeValue);try{("product_key"==b.nodeName||"font"==b.nodeName||
"encoding"==b.nodeName||"doctype"==b.nodeName)&&2<=b.childNodes.length&&(c=b.textContent?b.textContent:a)}catch(d){c=a}}catch(e){c="parsing error"}return c}},removeEvents:function(b,c,a){b=c.split(",");c=a.length;for(var d=0,e=0;e<c;e++)for(var d=b.length,h=0;h<d;h++)a[e].removeAttribute(b[h])},bytesToSize:function(b){b=parseInt(b,10);var c="0 byte";isNaN(b)&&(b="",c="N/A");c={size:0,unit:"byte",toString:c};if(0==b)return c;var a=parseInt(Math.floor(Math.log(b)/Math.log(1024)));c.size=Math.round(b/
Math.pow(1024,a)*100,2)/100;c.unit=["bytes","KB","MB","GB","TB"][a];c.toString=c.size+" "+c.unit;return c},stringToXML:function(b){var c;try{window.ActiveXObject?(c=new ActiveXObject("Microsoft.XMLDOM"),c.async="false",c.loadXML(b)):c=(new DOMParser).parseFromString(b,"text/xml")}catch(a){c=null}return c},getUnitSize:function(b){var c=1;switch(b.toLowerCase()){case "kb":c*=1024;break;case "mb":c*=1048576;break;case "gb":c*=1073741824}return c},getUnit:function(b){b=b.toLowerCase();var c="";-1<b.indexOf("mb")?
c=b.substring(b.indexOf("mb")):-1<b.indexOf("gb")?c=b.substring(b.indexOf("gb")):-1<b.indexOf("kb")?c=b.substring(b.indexOf("kb")):-1<b.indexOf("b")&&(c=b.substring(b.indexOf("b")));return c},getDate:function(){var b=0,c=new Date,b=""+c.getFullYear(),a=""+(c.getMonth()+1);1==a.length&&(a="0"+a);c=""+c.getDate();1==c.length&&(c="0"+c);return b=parseInt(b+a+c,10)},getMimeFilter:function(b){var c="",c=b.split(",").join(",.");""!=c&&(c="."+c);return c},getMimeFilterEx:function(b){var c="",c=b.split(",").join(";*.");
""!=c&&(c="*."+c);return c},getExtStringFromExtEx:function(b){b=b.toLowerCase().split("|");for(var c=b.length,a="",d=1;d<c;d+=2){var e=b[d].replace(/\*./gi,""),e=e.replace(/\*/gi,""),e=e.replace(/;$/gi,""),e=e.replace(/;/gi,",");""!=a&&(a+=",");a+=e}return a},parseIntOr0:function(b){b=parseInt(b,10);return isNaN(b)?0:b},makeGuidTagName:function(b){var c=0,a=(new Date).getTime().toString(32),d;for(d=0;5>d;d++)a+=Math.floor(65535*Math.random()).toString(32);return(b||"o_")+a+(c++).toString(32)},makeGuid:function(b){var c=
function(){return(65536*(1+Math.random())|0).toString(16).substring(1)},c=(c()+c()+"-"+c()+"-"+c()+"-"+c()+"-"+c()+c()+c()).toUpperCase();void 0!=b&&(c=b+"-"+c);return c},getUserLang:function(b){b=b.toLowerCase();var c="ko-kr";-1<b.indexOf("ko")?c="ko-kr":-1<b.indexOf("en")?c="en-us":-1<b.indexOf("ja")?c="ja-jp":-1<b.indexOf("zh-cn")?c="zh-cn":-1<b.indexOf("zh-tw")&&(c="zh-tw");return c},getDocWindow:function(b){return b.parentWindow||b.defaultView},getClientRect:function(b){var c={left:0,top:0,right:0,
bottom:0};try{c=b.getBoundingClientRect()}catch(a){}return c},getParentbyTagName:function(b,c){for(var a=b;null!=a&&(!a.tagName||a.tagName.toLowerCase()!=c);)a=a.parentNode;return a},getElementsByClass:function(b,c,a){var d=[];null==c&&(c=document);null==a&&(a="*");c=c.getElementsByTagName(a);a=c.length;b=new RegExp("(^|\\s)"+b+"(\\s|$)");for(j=i=0;i<a;i++)b.test(c[i].className)&&(d[j]=c[i],j++);return d},postFormData:function(b,c,a,d){void 0==d&&(d=[]);var e=b.createElement("form");e.method="post";
e.action=c;e.target=a;c=d.length;for(a=0;a<c;a++){var h=b.createElement("input");h.type="hidden";h.name=d[a][0];h.value=d[a][1];e.appendChild(h)}b.body.appendChild(e);e.submit();b.body.removeChild(e)},base64_decode:function(b){var c="",a,d,e,h,g,t=0;for(b=b.replace(/[^A-Za-z0-9\+\/\=]/g,"");t<b.length;)a="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/=".indexOf(b.charAt(t++)),d="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/=".indexOf(b.charAt(t++)),h="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/=".indexOf(b.charAt(t++)),
g="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/=".indexOf(b.charAt(t++)),a=a<<2|d>>4,d=(d&15)<<4|h>>2,e=(h&3)<<6|g,c+=String.fromCharCode(a),64!=h&&(c+=String.fromCharCode(d)),64!=g&&(c+=String.fromCharCode(e));return c=DEXT5UPLOAD.util.utf8_decode(c)},base64_encode:function(b){var c="",a,d,e,h,g,t,E=0;for(b=DEXT5UPLOAD.util.utf8_encode(b);E<b.length;)a=b.charCodeAt(E++),d=b.charCodeAt(E++),e=b.charCodeAt(E++),h=a>>2,a=(a&3)<<4|d>>4,g=(d&15)<<2|e>>6,t=e&63,isNaN(d)?g=t=64:isNaN(e)&&
(t=64),c=c+"ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/=".charAt(h)+"ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/=".charAt(a)+"ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/=".charAt(g)+"ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/=".charAt(t);return c},utf8_encode:function(b){b=b.replace(/\r\n/g,"\n");for(var c="",a=0;a<b.length;a++){var d=b.charCodeAt(a);128>d?c+=String.fromCharCode(d):(127<d&&2048>d?c+=String.fromCharCode(d>>
6|192):(c+=String.fromCharCode(d>>12|224),c+=String.fromCharCode(d>>6&63|128)),c+=String.fromCharCode(d&63|128))}return c},utf8_decode:function(b){for(var c="",a=0,d=c1=c2=0;a<b.length;)d=b.charCodeAt(a),128>d?(c+=String.fromCharCode(d),a++):191<d&&224>d?(c2=b.charCodeAt(a+1),c+=String.fromCharCode((d&31)<<6|c2&63),a+=2):(c2=b.charCodeAt(a+1),c3=b.charCodeAt(a+2),c+=String.fromCharCode((d&15)<<12|(c2&63)<<6|c3&63),a+=3);return c},dataURItoBlob:function(b){var c=atob(b.split(",")[1]);b=b.split(",")[0].split(":")[1].split(";")[0];
for(var a=new ArrayBuffer(c.length),d=new Uint8Array(a),e=0;e<c.length;e++)d[e]=c.charCodeAt(e);c=new DataView(a);return new Blob([c.buffer],{type:b})},makeDecryptReponseMessage:function(b){b=DEXT5UPLOAD.util.base64_decode(b);b=b.substring(1);return b=DEXT5UPLOAD.util.base64_decode(b)},set_handlerUrl:function(b){var c="",c=0==b.length?DEXT5UPLOAD.rootPath:"/"==b.substring(0,1)?location.protocol+"//"+location.host:4<b.length&&"http"==b.substring(0,4).toLowerCase()?"":DEXT5UPLOAD.rootPath;return c+
b},buildFormData:function(b,c,a,d){c=""+("--"+b+'\r\nContent-Disposition: form-data; name="'+c+'"')+"\r\n";c+="\r\n";c+=a;c+="\r\n";d&&(c+="--"+b+"--");return c},HashTable:function(b){this.length=0;this.items={};for(var c in b)b.hasOwnProperty(c)&&(this.items[c]=b[c],this.length++);this.setItem=function(a,b){var c=void 0;this.hasItem(a)?c=this.items[a]:this.length++;this.items[a]=b;return c};this.getItem=function(a){return this.hasItem(a)?this.items[a]:void 0};this.hasItem=function(a){return this.items.hasOwnProperty(a)};
this.removeItem=function(a){if(this.hasItem(a))return previous=this.items[a],this.length--,delete this.items[a],previous};this.keys=function(){var a=[],b;for(b in this.items)this.hasItem(b)&&a.push(b);return a};this.values=function(){var a=[],b;for(b in this.items)this.hasItem(b)&&a.push(this.items[b]);return a};this.each=function(a){for(var b in this.items)this.hasItem(b)&&a(b,this.items[b])};this.clear=function(){this.items={};this.length=0}},setSecuritySetting:function(b,c,a){if(1==a)"NONE"==c.developLang&&
(c.security.encryptParam="0"),c.security.fileExtensionDetector="0",c.security.fileIntegrity="0",c.security.fileEncrypt="0",c.security.deleteOpenFile="0",c.security.keyValue="0";else{a=c.userRunTimeMode;if(DEXT5UPLOAD.config.Security.EncryptParam&&""!=DEXT5UPLOAD.config.Security.EncryptParam)c.security.encryptParam="1"==DEXT5UPLOAD.config.Security.EncryptParam?"1":"0";else{var d=DEXT5UPLOAD.util.xml.getNodeValue(b,"encrypt_param");c.security.encryptParam="1"==d?"1":"0"}DEXT5UPLOAD.config.Security.FileExtensionDetector&&
""!=DEXT5UPLOAD.config.Security.FileExtensionDetector?c.security.fileExtensionDetector="1"==DEXT5UPLOAD.config.Security.FileExtensionDetector?"1":"0":(d=DEXT5UPLOAD.util.xml.getNodeValue(b,"file_extension_detector"),c.security.fileExtensionDetector="1"==d?"1":"0");if(-1<a.indexOf("html5")||"ieplugin"==a)DEXT5UPLOAD.config.Security.FileIntegrity&&""!=DEXT5UPLOAD.config.Security.FileIntegrity?c.security.fileIntegrity="1"==DEXT5UPLOAD.config.Security.FileIntegrity?"1":"0":(d=DEXT5UPLOAD.util.xml.getNodeValue(b,
"file_integrity"),c.security.fileIntegrity="1"==d?"1":"0"),"ieplugin"==a?DEXT5UPLOAD.config.Security.FileEncrypt&&""!=DEXT5UPLOAD.config.Security.FileEncrypt?c.security.fileEncrypt="1"==DEXT5UPLOAD.config.Security.FileEncrypt?"1":"0":(d=DEXT5UPLOAD.util.xml.getNodeValue(b,"file_encrypt"),c.security.fileEncrypt="1"==d?"1":"0"):c.security.fileEncrypt="0";"ieplugin"==a&&(DEXT5UPLOAD.config.Security.DeleteOpenFile&&""!=DEXT5UPLOAD.config.Security.DeleteOpenFile?c.security.deleteOpenFile="1"==DEXT5UPLOAD.config.Security.DeleteOpenFile?
"1":"0":(b=DEXT5UPLOAD.util.xml.getNodeValue(b,"delete_open_file"),c.security.deleteOpenFile="1"==b?"1":"0"))}},makeEncryptParam:function(b){b=DEXT5UPLOAD.util.base64_encode(b);b="R"+b;b=DEXT5UPLOAD.util.base64_encode(b);return b=b.replace(/[+]/g,"%2B")},getIframeDocument:function(b){return"undefined"!=typeof b.contentDocument?b.contentDocument:"undefined"!=typeof b.contentWindow?b.contentWindow.document:null}};
function Dext5Upload_Config(){this.licenseKey=this.productKey="";this.licenseKeySE="0";this.licenseKeyEx="";this.plugin_version=DEXT5UPLOAD.cabVersion;this.webPath={image:DEXT5UPLOAD.rootPath+"images/",skin:DEXT5UPLOAD.rootPath+"images/skin/",page:DEXT5UPLOAD.rootPath+"pages/",js:DEXT5UPLOAD.rootPath+"js/",jsDev:DEXT5UPLOAD.rootPath+"js_dev/",lang:DEXT5UPLOAD.rootPath+"js/lang/",langDev:DEXT5UPLOAD.rootPath+"js_dev/lang/",css:DEXT5UPLOAD.rootPath+"css/",cssDev:DEXT5UPLOAD.rootPath+"css_dev/",config:DEXT5UPLOAD.rootPath+
"config/",plugin:DEXT5UPLOAD.rootPath+"plugin/",hybrid:DEXT5UPLOAD.rootPath+"hybrid/",installGuide:DEXT5UPLOAD.rootPath+"hybrid/installguide/installguide.html"};this.initVisible=!0;this.configUrl=this.webPath.config+"dext5upload.config.xml";this.skinName="blue";this.customTextColor=this.customProgressBarColor=this.customFooterColor=this.customHeaderColor="";this.customWebFileColor="#f9f5f5";this.width="500px";this.height="316px";this.minHeight=120;this.statusBarHeight=26;this.buttonBarHeight=34;this.minHeaderBarHeight=
28;this.originHeight="316px";this.customHeaderHeight="28";this.lang="ko-kr";this.keepLang="";this.isCrossDomain=!1;this.maxOneFileSize=this.maxTotalFileCount=this.maxTotalFileSize=0;this.useLogoImage={use:"0",logoPath:this.webPath.image+"dext5_logo.png",logoVer:""};this.hideListInfo="0";this.extension={allowOrLimit:"1",extArr:[],extToString:"",mimeAccept:""};this.showHeaderBar=this.showStatusBar="1";this.showButtonBarEdit=[];this.showButtonBarView=[];this.uploadBorderStyle="none";this.multiFileSelect=
!0;this.listViewDragAndDrop=this.listViewDbclick="1";this.mode="upload";this.subMode="";this.views="list";this.canvasWidth=88;this.canvasHeight=60;this.userRunTimeMode="html5";this.hybridDownload=this.useWS="0";this.hybridParam="";this.hybridWindowMode=this.enforceIePlugin="1";this.useInstallGuide="0";this.installFileName="DEXT5_Hybrid50.exe";this.developLang="NET";this.handlerUrl=DEXT5UPLOAD.rootPath+"handler/dext5handler.ashx";this.downloadHandlerUrl="";this.viewerUrl=DEXT5UPLOAD.rootPath+"handler/dext5viewer.aspx";
this.folderNameRule="yyyy/mm";this.fileNameRule="REALFILENAME";this.fileNameRuleEx="_";this.asyncUpload=!1;this.chunkSize=1048576;this.useServerFileSize=this.folderDetailHeader=this.folderTransfer=this.resumeDownload=this.resumeUpload=this.multiUpload="0";this.useAfterDownloadEvent=this.useAfterAddEndTimeEvent=this.useAfterAddEvent=this.useDownloadEvent=this.useUploadingCancelEvent=this.useViewOrOpenEvent=this.useDeleteEvent=this.useAddEvent="1";this.addExtIcon=[];this.isPause=!1;this.automaticConnection=
this.timeout="0";this.showFolderView="1";this.handlerUrlCheck=!0;this.messageTitle="";this.useScriptEventControl="1";this.uploadCancel=!1;this.hideContextMenu=this.showCheckBox="0";this.sizeColumnWidth="100";this.unitDelimiter="\x0B";this.unitAttributeDelimiter="\f";this.trans_unitDelimiter="\x0B";this.trans_unitAttributeDelimiter="\f";this.useAutoHeight=this.pluginZipDownload=this.downloadMulti="0";this.removeContextItem="";this.displayFileSizeHtml4=this.disableDeleteConfirmMessage="0";this.NTLM=
"";this.largeFiles={markSize:0,maxCount:0,maxTotalSize:0,text:"",color:"",markBaseTotalSize:0,customMode:0};this.forceReDraw=this.cacheProtectMode="0";this.use_file_sort="1";this.auto_sort=this.sort_ascdesc=this.sort_field="0";this.showViewAlign=this.showEditAlign="left";this.imgPreView=this.completeEventResetUse=this.fileMoveContextMenu="0";this.imgPreViewHeight=this.imgPreViewWidth="100px";this.statusBarShowStatus=this.statusBarShowLimit="1";this.buttonBarPosition="buttom";this.userMessage={edit:"",
view:""};this.useSingleSelect="0";this.disableAlertMessage={duplication:"1",deleteUnchosen:"1",downloadUnchosen:"1",openUnchosen:"1",disableDeleteConfirm:"0",fileExtensionDetect:"0"};this.directDownload=this.silentUpload=this.allowedZeroFileSize="0";this.enableThread="1";this.security={encryptParam:"0",fileExtensionDetector:"0",fileIntegrity:"0",fileEncrypt:"0",deleteOpenFile:"0",keyValue:DEXT5UPLOAD.ReleaseVer.substring(0,11)};this.sizeForChunkUpload=52428800;this.uploadMethod="1";this.headerBarItem=
[];this.headerBarItemWidth=[];this.headerBarItemAlign=[];this.socketWorkerCount=2;this.socketWorkerJobSize=0;this.minSingleSocketWorkerSize=20971520;this.wsHandlerUrl=DEXT5UPLOAD.rootPath+"handler/dext5plushandler.ashx";5>=this.wsHandlerUrl.indexOf("//")&&(this.wsHandlerUrl="ws:"+this.wsHandlerUrl.substring(this.wsHandlerUrl.indexOf("//")));this.wsChunkSize=1048576;this.uploadTransferWindow={view:"standard",viewWidth:"470px",viewHeight:"170px"};this.groupId="";this.pluginInstallType="0";this.defaultDownloadPath=
"";this.transferOpenFile=this.uploadMethodHtml4="1";this.selectByClicked="0";this.aftertUpload={setFileSize:"0"};this.savePathSetting="";this.transferBackgroundStyle="filter:alpha(opacity=50); opacity:0.5; -moz-opacity:0.5; -ms-filter:progid:DXImageTransform.Microsoft.Alpha(Opacity=50); -khtml-opacity: 0.5; background-color:black;";this.useDropzone="0";this.fileFilterEx=this.allowOpenExtension="";this.imageQuality={quality:1,workerCount:7};this.useZipDownload="0";this.useSetCookie="1";this.hybridMethod=
0;this.allowedRealtimeDownloadAdd=1;this.hybridShowItemCount=3;this.downloadPartialSize=0;this.html4LimitFileSize="0"}function isExistUploaderName(b){if(void 0==b||""==b)return 1;var c=DEXT5UPLOAD.DEXTMULTIPLE["dext5uploader_frame_"+b];return void 0==c||null==c?0:""!=DEXT5UPLOAD.config.UploadHolder&&DEXT5UPLOAD.DEXTHOLDER[b]==DEXT5UPLOAD.config.UploadHolder?3:2}
function getNewNextUploaderName(b){var c="",c=b.split("_"),a=c.length;1<a&&(b=b.replace("_"+c[a-1],""));c=b+getNextUploaderNumber();0<isExistUploaderName(c)&&(c=getNewNextUploaderName(c));return c}var getNextUploaderNumber=function(){var b=0;return function(){return"_"+ ++b}}();
function Dext5Upload(b){void 0==b&&(b=DEXT5UPLOAD.util.makeGuidTagName("dext5upload_"));var c=isExistUploaderName(b);if(1==c)alert("uploader's name is empty. Please, check uploader's name");else{if(2==c)if("1"==DEXT5UPLOAD.config.IgnoreSameUploadName)b=getNewNextUploaderName(b);else{alert("uploader's name is already exist. Please, check uploader's name");return}3!=c&&(DEXT5UPLOAD.DEXTMULTIPLEID.push(b),DEXT5UPLOAD.DEXTMULTIPLE["dext5uploader_frame_"+b]=b,DEXT5UPLOAD.DEXTHOLDER[b]=DEXT5UPLOAD.config.UploadHolder);
this.frameID="dext5uploader_frame_"+b;this.ID=b;var a=new Dext5Upload_Config;if(0<DEXT5UPLOAD.config.InitServerXml.length)if(-1<DEXT5UPLOAD.config.InitServerXml.indexOf("f="))a.configUrl=DEXT5UPLOAD.config.InitServerXml+"&dext5CMD=configRequest";else{alert("Error occurred reading the Upload Settings");return}else 0<DEXT5UPLOAD.config.InitXml.length&&(0==DEXT5UPLOAD.config.InitXml.indexOf("http")?a.configUrl=DEXT5UPLOAD.config.InitXml:a.configUrl=DEXT5UPLOAD.rootPath+"config/"+DEXT5UPLOAD.config.InitXml);
a.configUrl=DEXT5UPLOAD.util.set_handlerUrl(a.configUrl);-1<a.configUrl.indexOf("?")?a.configUrl+="&t="+(new Date).getTime():a.configUrl+="?t="+(new Date).getTime();var d=null,d=0<DEXT5UPLOAD.config.InitServerXml.length?DEXT5UPLOAD.ajax.load(a.configUrl):DEXT5UPLOAD.ajax.loadXml(a.configUrl);if(null==d)alert("Error occurred reading the Upload Settings");else{"object"!=typeof d&&(0==d.indexOf("[OK]")||0==d.indexOf("[OK-NE]")?(0==d.indexOf("[OK]")?(d=d.substring(4),d=DEXT5UPLOAD.util.base64_decode(d)):
0==d.indexOf("[OK-NE]")&&(d=d.substring(7),d=DEXT5UPLOAD.util.makeDecryptReponseMessage(d)),d=d.substring(d.indexOf("<?")),d=DEXT5UPLOAD.util.stringToXML(d)):0==d.indexOf("[FAIL]")?alert("Error occurred reading the Upload Settings"):0==d.indexOf("[FAIL-NE]")?alert("Error occurred reading the Upload Settings"):(d=DEXT5UPLOAD.util.stringToXML(d))||alert("Error occurred reading the Upload Settings"));0==DEXT5UPLOAD.config.InitVisible&&(a.initVisible=DEXT5UPLOAD.config.InitVisible);var e=DEXT5UPLOAD.util.xml.getNode(d,
"license");a.productKey=""!=DEXT5UPLOAD.config.ProductKey?DEXT5UPLOAD.config.ProductKey:DEXT5UPLOAD.util.xml.getNodeValue(e,"product_key");a.licenseKey=""!=DEXT5UPLOAD.config.LicenseKey?DEXT5UPLOAD.config.LicenseKey:DEXT5UPLOAD.util.xml.getNodeValue(e,"license_key");a.licenseKeyEx=""!=DEXT5UPLOAD.config.LicenseKeyEx?DEXT5UPLOAD.config.LicenseKeyEx:DEXT5UPLOAD.util.xml.getNodeValue(e,"license_key_ex");if(""!=DEXT5UPLOAD.config.LicenseKeySE)a.licenseKeySE=DEXT5UPLOAD.config.LicenseKeySE;else{var h=
DEXT5UPLOAD.util.xml.getNode(e,"license_key");h&&h.getAttribute("se")&&"1"==h.getAttribute("se")&&(a.licenseKeySE="1")}var g=DEXT5UPLOAD.util.xml.getNode(d,"uploader_setting");if(""!=DEXT5UPLOAD.config.DevelopLangage)a.developLang=DEXT5UPLOAD.config.DevelopLangage;else{var t=DEXT5UPLOAD.util.xml.getNodeValue(g,"develop_langage");0<t.length&&(a.developLang=t)}switch(a.developLang.toUpperCase()){case "JAVA":case "JSP":a.handlerUrl=DEXT5UPLOAD.rootPath+"handler/dext5handler.jsp";a.viewerUrl=DEXT5UPLOAD.rootPath+
"handler/dext5viewer.jsp";break;case "PHP":a.handlerUrl=DEXT5UPLOAD.rootPath+"handler/dext5handler.php";a.viewerUrl=DEXT5UPLOAD.rootPath+"handler/dext5viewer.php";break;case "NONE":a.handlerUrl="";a.viewerUrl="";break;default:a.handlerUrl=DEXT5UPLOAD.rootPath+"handler/dext5handler.ashx",a.viewerUrl=DEXT5UPLOAD.rootPath+"handler/dext5viewer.aspx"}var E;""!=DEXT5UPLOAD.config.HandlerUrl?a.handlerUrl=DEXT5UPLOAD.config.HandlerUrl:(E=DEXT5UPLOAD.util.xml.getNodeValue(g,"handler_url"),0<E.length&&(a.handlerUrl=
E));a.handlerUrl=DEXT5UPLOAD.util.set_handlerUrl(a.handlerUrl);4<a.handlerUrl.length&&"http"==a.handlerUrl.substring(0,4).toLowerCase()&&a.handlerUrl.match(/:\/\/(.[^\/]+)/)[1]!=window.location.host&&(a.isCrossDomain=!0);if(""!=DEXT5UPLOAD.config.ViewerHandlerUrl)a.viewerUrl=DEXT5UPLOAD.config.ViewerHandlerUrl;else{var Ka=DEXT5UPLOAD.util.xml.getNodeValue(g,"viewer_handler_url");""!=Ka&&(a.viewerUrl=Ka)}a.viewerUrl=DEXT5UPLOAD.util.set_handlerUrl(a.viewerUrl);if(""!=DEXT5UPLOAD.config.DownloadHandlerUrl)a.downloadHandlerUrl=
DEXT5UPLOAD.config.DownloadHandlerUrl;else{var ha=DEXT5UPLOAD.util.xml.getNodeValue(g,"download_handler_url");""!=ha&&(a.downloadHandlerUrl=ha)}""!=a.downloadHandlerUrl&&(a.downloadHandlerUrl=DEXT5UPLOAD.util.set_handlerUrl(a.downloadHandlerUrl));if(""!=DEXT5UPLOAD.config.WsHandlerUrl)a.wsHandlerUrl=DEXT5UPLOAD.config.WsHandlerUrl;else{var k=DEXT5UPLOAD.util.xml.getNodeValue(g,"ws_handler_url");""!=k&&(a.wsHandlerUrl=k)}if(""!=DEXT5UPLOAD.config.WsChunkSize)a.wsChunkSize=parseInt(DEXT5UPLOAD.config.WsChunkSize,
10);else{var x=DEXT5UPLOAD.util.xml.getNodeValue(g,"ws_chunk_size");""!=x&&(a.wsChunkSize=parseInt(x,10))}if(""!=DEXT5UPLOAD.config.WsWorkerCount)a.socketWorkerCount=DEXT5UPLOAD.util.parseIntOr0(DEXT5UPLOAD.config.WsWorkerCount);else{var p=DEXT5UPLOAD.util.xml.getNodeValue(g,"ws_worker_count");""!=p&&(a.socketWorkerCount=DEXT5UPLOAD.util.parseIntOr0(p))}""!=DEXT5UPLOAD.config.WsWorkerJobSize?a.socketWorkerJobSize=DEXT5UPLOAD.util.parseIntOr0(DEXT5UPLOAD.config.WsWorkerJobSize):(p=DEXT5UPLOAD.util.xml.getNode(g,
"ws_worker_count"))&&p.getAttribute("job_size")&&""!=p.getAttribute("job_size")&&(a.socketWorkerJobSize=DEXT5UPLOAD.util.parseIntOr0(p.getAttribute("job_size")));""!=DEXT5UPLOAD.config.WsMinSingleWorkerSize?a.minSingleSocketWorkerSize=DEXT5UPLOAD.util.parseIntOr0(DEXT5UPLOAD.config.WsMinSingleWorkerSize):(p=DEXT5UPLOAD.util.xml.getNode(g,"ws_worker_count"))&&p.getAttribute("min_single_worker_size")&&""!=p.getAttribute("min_single_worker_size")&&(a.minSingleSocketWorkerSize=DEXT5UPLOAD.util.parseIntOr0(p.getAttribute("min_single_worker_size")));
if(""!=DEXT5UPLOAD.config.FolderNameRule)a.folderNameRule=DEXT5UPLOAD.config.FolderNameRule;else{var z=DEXT5UPLOAD.util.xml.getNodeValue(g,"folder_name_rule");a.folderNameRule=z}if(""!=DEXT5UPLOAD.config.FileNameRule)a.fileNameRule=DEXT5UPLOAD.config.FileNameRule;else{var B=DEXT5UPLOAD.util.xml.getNodeValue(g,"file_name_rule");""!=B&&(a.fileNameRule=B)}if(""!=DEXT5UPLOAD.config.FileNameRuleEx){if("#"==DEXT5UPLOAD.config.FileNameRuleEx||"i"==DEXT5UPLOAD.config.FileNameRuleEx||"_"==DEXT5UPLOAD.config.FileNameRuleEx)a.fileNameRuleEx=
DEXT5UPLOAD.config.FileNameRuleEx}else{var A=DEXT5UPLOAD.util.xml.getNodeValue(g,"file_name_rule_ex");if("#"==A||"i"==A||""==A)a.fileNameRuleEx=A}""!=DEXT5UPLOAD.config.AsyncUpload?"1"==DEXT5UPLOAD.config.AsyncUpload&&(a.asyncUpload=!0):"1"==DEXT5UPLOAD.util.xml.getNodeValue(g,"async_upload")&&(a.asyncUpload=!0);if(""!=DEXT5UPLOAD.config.ChunkSize){var r=DEXT5UPLOAD.util.getUnit(DEXT5UPLOAD.config.ChunkSize),n=DEXT5UPLOAD.util.getUnitSize(r),M=parseInt(DEXT5UPLOAD.config.ChunkSize,10);a.chunkSize=
M*n}else{var La=DEXT5UPLOAD.util.xml.getNodeValue(g,"chunk_size");if(""!=La){var qa=DEXT5UPLOAD.util.xml.getNode(g,"chunk_size");qa.getAttribute("unit")&&""!=qa.getAttribute("unit")&&(n=DEXT5UPLOAD.util.getUnitSize(qa.getAttribute("unit")),a.chunkSize=parseInt(La,10)*n)}}"1"==DEXT5UPLOAD.util.xml.getNodeValue(g,"multi_upload")&&(a.multiUpload="1");if(""!=DEXT5UPLOAD.config.UploadMethod)a.uploadMethod=DEXT5UPLOAD.config.UploadMethod;else{var Ma=DEXT5UPLOAD.util.xml.getNodeValue(g,"upload_method");
""!=Ma&&(a.uploadMethod=Ma)}if(""!=DEXT5UPLOAD.config.SizeForChunkUpload)a.sizeForChunkUpload=DEXT5UPLOAD.util.parseIntOr0(DEXT5UPLOAD.config.SizeForChunkUpload);else{var Na=DEXT5UPLOAD.util.xml.getNodeValue(g,"size_for_chunk_upload");""!=Na&&(a.sizeForChunkUpload=DEXT5UPLOAD.util.parseIntOr0(Na))}var f=DEXT5UPLOAD.util.xml.getNode(d,"setting");if(""!=DEXT5UPLOAD.config.SkinName)a.skinName=DEXT5UPLOAD.config.SkinName;else{var X=DEXT5UPLOAD.util.xml.getNodeValue(f,"skin_name");0<X.length&&(a.skinName=
X)}var q=DEXT5UPLOAD.util.xml.getNode(f,"skin_name");""!=DEXT5UPLOAD.config.CustomHeaderColor?a.customHeaderColor=DEXT5UPLOAD.config.CustomHeaderColor:q&&q.getAttribute("color1")&&""!=q.getAttribute("color1")&&(a.customHeaderColor=q.getAttribute("color1"));""!=DEXT5UPLOAD.config.CustomFooterColor?a.customFooterColor=DEXT5UPLOAD.config.CustomFooterColor:q&&q.getAttribute("color2")&&""!=q.getAttribute("color2")&&(a.customFooterColor=q.getAttribute("color2"));""!=DEXT5UPLOAD.config.CustomProgressBarColor?
a.customProgressBarColor=DEXT5UPLOAD.config.CustomProgressBarColor:q&&q.getAttribute("color3")&&""!=q.getAttribute("color3")&&(a.customProgressBarColor=q.getAttribute("color3"));""!=DEXT5UPLOAD.config.CustomTextColor?a.customTextColor=DEXT5UPLOAD.config.CustomTextColor:q&&q.getAttribute("text_color")&&""!=q.getAttribute("text_color")&&(a.customTextColor=q.getAttribute("text_color"));""!=DEXT5UPLOAD.config.CustomWebFileColor?a.customWebFileColor=DEXT5UPLOAD.config.CustomWebFileColor:q&&q.getAttribute("webfile_color")&&
""!=q.getAttribute("webfile_color")&&(a.customWebFileColor=q.getAttribute("webfile_color"));""!=DEXT5UPLOAD.config.CssRootPath?(a.webPath.css=DEXT5UPLOAD.config.CssRootPath,a.webPath.cssDev=DEXT5UPLOAD.config.CssRootPath):q&&q.getAttribute("css_root_path")&&""!=q.getAttribute("css_root_path")&&(a.webPath.css=q.getAttribute("css_root_path"),a.webPath.cssDev=q.getAttribute("css_root_path"));a.webPath.css.lastIndexOf("/")<a.webPath.css.length-1&&(a.webPath.css+="/");a.webPath.cssDev.lastIndexOf("/")<
a.webPath.cssDev.length-1&&(a.webPath.cssDev+="/");if(""!=DEXT5UPLOAD.config.Width)a.width=DEXT5UPLOAD.config.Width;else{var Oa=DEXT5UPLOAD.util.xml.getNodeValue(f,"width");0<Oa.length&&(a.width=Oa)}if(""!=DEXT5UPLOAD.config.Height)a.height=DEXT5UPLOAD.config.Height,a.originHeight=DEXT5UPLOAD.config.Height;else{var ra=DEXT5UPLOAD.util.xml.getNodeValue(f,"height");0<ra.length&&(a.height=ra,a.originHeight=ra)}var Pa=DEXT5UPLOAD.util.xml.getNodeValue(f,"lang");""!=DEXT5UPLOAD.config.Lang?a.lang=DEXT5UPLOAD.util.getUserLang(DEXT5UPLOAD.config.Lang):
0<Pa.length&&(a.lang=DEXT5UPLOAD.util.getUserLang(Pa));if(""!=DEXT5UPLOAD.config.KeepLang)a.keepLang=DEXT5UPLOAD.config.KeepLang;else{var ia=DEXT5UPLOAD.util.xml.getNode(f,"lang");ia&&ia.getAttribute("keep_lang")&&""!=ia.getAttribute("keep_lang")&&(a.keepLang=ia.getAttribute("keep_lang"))}""==a.keepLang&&(a.keepLang=a.lang);if(""!=DEXT5UPLOAD.config.MaxTotalFileSize){var r=DEXT5UPLOAD.util.getUnit(DEXT5UPLOAD.config.MaxTotalFileSize),n=DEXT5UPLOAD.util.getUnitSize(r),Y=parseInt(DEXT5UPLOAD.config.MaxTotalFileSize,
10);a.maxTotalFileSize=Y*n}else{var Qa=DEXT5UPLOAD.util.xml.getNodeValue(f,"max_total_file_size");if(0<Qa.length){var sa=DEXT5UPLOAD.util.xml.getNode(f,"max_total_file_size");sa.getAttribute("unit")&&""!=sa.getAttribute("unit")&&(n=DEXT5UPLOAD.util.getUnitSize(sa.getAttribute("unit")),a.maxTotalFileSize=parseInt(Qa,10)*n)}}if(""!=DEXT5UPLOAD.config.MaxTotalFileCount)a.maxTotalFileCount=parseInt(DEXT5UPLOAD.config.MaxTotalFileCount,10);else{var Ra=DEXT5UPLOAD.util.xml.getNodeValue(f,"max_total_file_count");
0<parseInt(Ra,10)&&(a.maxTotalFileCount=parseInt(Ra,10))}if(""!=DEXT5UPLOAD.config.MaxOneFileSize)r=DEXT5UPLOAD.util.getUnit(DEXT5UPLOAD.config.MaxOneFileSize),n=DEXT5UPLOAD.util.getUnitSize(r),Y=parseInt(DEXT5UPLOAD.config.MaxOneFileSize,10),a.maxOneFileSize=Y*n;else{var Sa=DEXT5UPLOAD.util.xml.getNodeValue(f,"max_one_file_size");if(0<Sa.length){var ta=DEXT5UPLOAD.util.xml.getNode(f,"max_one_file_size");ta.getAttribute("unit")&&""!=ta.getAttribute("unit")&&(n=DEXT5UPLOAD.util.getUnitSize(ta.getAttribute("unit")),
a.maxOneFileSize=parseInt(Sa,10)*n)}}var Z=DEXT5UPLOAD.util.xml.getNode(f,"upload_transfer_window"),Ta=DEXT5UPLOAD.util.xml.getNodeValue(Z,"view"),F=DEXT5UPLOAD.util.xml.getNode(Z,"view");DEXT5UPLOAD.config.UploadTransferWindow.View&&""!=DEXT5UPLOAD.config.UploadTransferWindow.View?a.uploadTransferWindow.view=DEXT5UPLOAD.config.UploadTransferWindow.View:""!=Ta&&(a.uploadTransferWindow.view=Ta);DEXT5UPLOAD.config.UploadTransferWindow.ViewWidth&&""!=DEXT5UPLOAD.config.UploadTransferWindow.ViewWidth?
a.uploadTransferWindow.viewWidth=DEXT5UPLOAD.config.UploadTransferWindow.ViewWidth:F&&F.getAttribute("width")&&""!=F.getAttribute("width")&&(a.uploadTransferWindow.viewWidth=F.getAttribute("width"),250>=DEXT5UPLOAD.util.parseIntOr0(a.uploadTransferWindow.viewWidth)&&(a.uploadTransferWindow.viewWidth="250px"));DEXT5UPLOAD.config.UploadTransferWindow.viewHeight&&""!=DEXT5UPLOAD.config.UploadTransferWindow.viewHeight?a.uploadTransferWindow.viewHeight=DEXT5UPLOAD.config.UploadTransferWindow.viewHeight:
F&&F.getAttribute("height")&&""!=F.getAttribute("height")&&(a.uploadTransferWindow.viewHeight=F.getAttribute("height"),150>=DEXT5UPLOAD.util.parseIntOr0(a.uploadTransferWindow.viewHeight)&&(a.uploadTransferWindow.viewHeight="150px"));var Ua=DEXT5UPLOAD.util.xml.getNodeValue(Z,"use_logo_image"),N=DEXT5UPLOAD.util.xml.getNode(Z,"use_logo_image");if("1"==Ua)a.useLogoImage.use="1",N.getAttribute("logo_path")&&""!=N.getAttribute("logo_path")&&(a.useLogoImage.logoPath=N.getAttribute("logo_path")),N.getAttribute("logo_ver")&&
""!=N.getAttribute("logo_ver")&&(a.useLogoImage.logoVer=N.getAttribute("logo_ver"));else if("0"==Ua)a.useLogoImage.use="0";else if("1"==DEXT5UPLOAD.util.xml.getNodeValue(f,"use_logo_image")){a.useLogoImage.use="1";var O=DEXT5UPLOAD.util.xml.getNode(f,"use_logo_image");O.getAttribute("logo_path")&&""!=O.getAttribute("logo_path")&&(a.useLogoImage.logoPath=O.getAttribute("logo_path"));O.getAttribute("logo_ver")&&""!=O.getAttribute("logo_ver")&&(a.useLogoImage.logoVer=O.getAttribute("logo_ver"))}var ua=
DEXT5UPLOAD.util.xml.getNodeValue(Z,"silent_upload");if(""!=ua)""!=DEXT5UPLOAD.config.SilentUpload?a.silentUpload=DEXT5UPLOAD.config.SilentUpload:""!=ua&&(a.silentUpload=ua);else if(""!=DEXT5UPLOAD.config.SilentUpload)a.silentUpload=DEXT5UPLOAD.config.SilentUpload;else{var Va=DEXT5UPLOAD.util.xml.getNodeValue(f,"silent_upload");""!=Va&&(a.silentUpload=Va)}""!=DEXT5UPLOAD.config.HideListInfo?a.hideListInfo=DEXT5UPLOAD.config.HideListInfo:"1"==DEXT5UPLOAD.util.xml.getNodeValue(f,"hide_list_info")&&
(a.hideListInfo="1");if(""!=DEXT5UPLOAD.config.ExtensionAllowOrLimit.toString()&&""!=DEXT5UPLOAD.config.ExtensionArr){if("0"==DEXT5UPLOAD.config.ExtensionAllowOrLimit)a.extension.allowOrLimit="0";else{var va=DEXT5UPLOAD.util.getMimeFilter(DEXT5UPLOAD.config.ExtensionArr.toLowerCase());a.extension.mimeAccept=va}-1<DEXT5UPLOAD.config.ExtensionArr.indexOf("|")?a.extension.extToString=DEXT5UPLOAD.config.ExtensionArr:(a.extension.extArr=DEXT5UPLOAD.config.ExtensionArr.toLowerCase().split(","),a.extension.extToString=
a.extension.extArr.toString())}else{var aa=DEXT5UPLOAD.util.xml.getNodeValue(f,"extension").toLowerCase();if(""!=aa){var Wa=DEXT5UPLOAD.util.xml.getNode(f,"extension");Wa.getAttribute("allow_or_limit")&&"0"==Wa.getAttribute("allow_or_limit")?a.extension.allowOrLimit="0":(va=DEXT5UPLOAD.util.getMimeFilter(aa),a.extension.mimeAccept=va);-1<aa.indexOf("|")?a.extension.extToString=aa:(a.extension.extArr=aa.split(","),a.extension.extToString=a.extension.extArr.toString())}}if(""!=DEXT5UPLOAD.config.BorderStyle)a.uploadBorderStyle=
DEXT5UPLOAD.config.BorderStyle;else{var Xa=DEXT5UPLOAD.util.xml.getNodeValue(f,"border_style");""!=Xa&&(a.uploadBorderStyle=Xa)}""!=DEXT5UPLOAD.config.MultiFileSelect?(a.multiFileSelect=DEXT5UPLOAD.config.MultiFileSelect,"0"==a.multiFileSelect&&(a.multiFileSelect=!1)):"0"==DEXT5UPLOAD.util.xml.getNodeValue(f,"multi_file_select")&&(a.multiFileSelect=!1);if(""!=DEXT5UPLOAD.config.Mode)"form"==DEXT5UPLOAD.config.Mode?(a.subMode=DEXT5UPLOAD.config.Mode,a.mode="upload"):a.mode=DEXT5UPLOAD.config.Mode;
else{var G=DEXT5UPLOAD.util.xml.getNodeValue(f,"mode");""!=G.length&&("form"==G?(a.subMode=G,a.mode="upload"):a.mode=G)}"form"==a.subMode?a.listViewDbclick="0":""!=DEXT5UPLOAD.config.ListViewDbclick?a.listViewDbclick=DEXT5UPLOAD.config.ListViewDbclick:"0"==DEXT5UPLOAD.util.xml.getNodeValue(f,"list_view_dbclick")&&(a.listViewDbclick="0");"form"==a.subMode?a.listViewDragAndDrop="0":""!=DEXT5UPLOAD.config.ListViewDragAndDrop?a.listViewDragAndDrop=DEXT5UPLOAD.config.ListViewDragAndDrop:"0"==DEXT5UPLOAD.util.xml.getNodeValue(f,
"list_view_drag_and_drop")&&(a.listViewDragAndDrop="0");if(""!=DEXT5UPLOAD.config.Runtimes)a.userRunTimeMode=DEXT5UPLOAD.config.Runtimes;else{var P=DEXT5UPLOAD.util.xml.getNodeValue(f,"runtimes");""!=P&&(a.userRunTimeMode=P)}""!=DEXT5UPLOAD.config.RunTimes&&(a.userRunTimeMode=DEXT5UPLOAD.config.RunTimes);""!=DEXT5UPLOAD.config.UseWS?a.useWS=DEXT5UPLOAD.config.UseWS:(P=DEXT5UPLOAD.util.xml.getNode(f,"runtimes"))&&P.getAttribute("use_ws")&&""!=P.getAttribute("use_ws")&&(a.useWS=P.getAttribute("use_ws"),
"1"!=a.useWS&&(a.useWS="0"));"html5plus"==a.userRunTimeMode&&(a.useWS="1");if(""!=DEXT5UPLOAD.config.HybridDownload)"1"==DEXT5UPLOAD.config.HybridDownload&&"windows"==DEXT5UPLOAD.UserAgent.os.name.toLowerCase()?a.hybridDownload="1":a.hybridDownload="0";else{var Q=DEXT5UPLOAD.util.xml.getNode(f,"runtimes");Q&&Q.getAttribute("hybrid_download")&&"1"==Q.getAttribute("hybrid_download")&&"windows"==DEXT5UPLOAD.UserAgent.os.name.toLowerCase()&&0==DEXT5UPLOAD.browser.mobile&&(a.hybridDownload="1")}var u=
DEXT5UPLOAD.util.xml.getNode(f,"hybrid");""!=DEXT5UPLOAD.config.HybridWindowMode?a.hybridWindowMode=DEXT5UPLOAD.config.HybridWindowMode:u&&"0"==DEXT5UPLOAD.util.xml.getNodeValue(u,"window_mode")&&(a.hybridWindowMode="0");if(""!=DEXT5UPLOAD.config.UseInstallGuide)a.useInstallGuide=DEXT5UPLOAD.config.UseInstallGuide;else if(u){var Ya=DEXT5UPLOAD.util.xml.getNodeValue(u,"use_install_guide");""!=Ya&&(a.useInstallGuide=Ya)}if(""!=DEXT5UPLOAD.config.HybridUseSetCookie)a.useSetCookie=DEXT5UPLOAD.config.HybridUseSetCookie;
else if(u){var Za=DEXT5UPLOAD.util.xml.getNodeValue(u,"use_set_cookie");""!=Za&&(a.useSetCookie=Za)}if(""!=DEXT5UPLOAD.config.HybridMethod)"1"==DEXT5UPLOAD.config.HybridMethod&&(a.hybridMethod=1);else if(u){var $a=DEXT5UPLOAD.util.xml.getNodeValue(u,"method");""!=$a&&"1"==$a&&(a.hybridMethod=1)}if(""!=DEXT5UPLOAD.config.AllowedRealtimeDownloadAdd)a.allowedRealtimeDownloadAdd=DEXT5UPLOAD.util.parseIntOr0(DEXT5UPLOAD.config.AllowedRealtimeDownloadAdd);else if(u){var ab=DEXT5UPLOAD.util.xml.getNodeValue(u,
"allowed_realtime_download_add");""!=ab&&"0"==ab&&(a.allowedRealtimeDownloadAdd=0)}if(""!=DEXT5UPLOAD.config.HybridShowItemCount)a.hybridShowItemCount=DEXT5UPLOAD.util.parseIntOr0(DEXT5UPLOAD.config.HybridShowItemCount);else if(u){var bb=DEXT5UPLOAD.util.xml.getNodeValue(u,"show_item_count");""!=bb&&(a.hybridShowItemCount=DEXT5UPLOAD.util.parseIntOr0(bb))}3>a.hybridShowItemCount?a.hybridShowItemCount=3:15<a.hybridShowItemCount&&(a.hybridShowItemCount=15);DEXT5UPLOAD.browser.safari&&(a.useInstallGuide=
0);""!=DEXT5UPLOAD.config.EnforceIePlugin?"0"==DEXT5UPLOAD.config.EnforceIePlugin&&(a.enforceIePlugin="0"):(Q=DEXT5UPLOAD.util.xml.getNode(f,"runtimes"))&&Q.getAttribute("enforce_ieplugin")&&"0"==Q.getAttribute("enforce_ieplugin")&&"windows"==DEXT5UPLOAD.UserAgent.os.name.toLowerCase()&&0==DEXT5UPLOAD.browser.mobile&&(a.enforceIePlugin="0");a.userRunTimeMode=GetUserRunTimeUpload(a.userRunTimeMode,a.useWS);if("html5"==a.userRunTimeMode&&DEXT5UPLOAD.browser.WorkerSupported){var ba="",C=DEXT5UPLOAD.ReleaseVer;
"1"==a.cacheProtectMode&&(C=(new Date).getTime());ba=DEXT5UPLOAD.isRelease?a.webPath.js+"dext5upload.uploadchunk.min.js?ver="+C:a.webPath.jsDev+"dext5upload.uploadchunk.js?ver="+C;try{(new Worker(ba)).terminate()}catch(ac){DEXT5UPLOAD.browser.WorkerSupported=!1}}"ieplugin"!=a.userRunTimeMode&&"1"==a.hybridDownload&&DEXT5UPLOAD.browser.ie&&"html4"==a.userRunTimeMode&&(a.userRunTimeMode="ieplugin");"ieplugin"==a.userRunTimeMode&&(a.hybridDownload="1"==a.enforceIePlugin?"0":"1");if("ieplugin"!=a.userRunTimeMode&&
""!=a.extension.extToString&&-1<a.extension.extToString.indexOf("|"))if(-1<a.extension.extToString.indexOf("*.*"))a.extension.extArr=[],a.extension.mimeAccept="";else{var Ob=DEXT5UPLOAD.util.getExtStringFromExtEx(a.extension.extToString);a.extension.extArr=Ob.split(",");"1"==a.extension.allowOrLimit&&(a.extension.mimeAccept=DEXT5UPLOAD.util.getMimeFilter(a.extension.extArr.toString()))}if(DEXT5UPLOAD.browser.WorkerSupported)if(""!=DEXT5UPLOAD.config.EnableThread)a.enableThread="0"==DEXT5UPLOAD.config.EnableThread?
"0":"1";else{var Pb=DEXT5UPLOAD.util.xml.getNodeValue(g,"enable_thread");a.enableThread="0"==Pb?"0":"1"}"0"==a.enableThread&&(DEXT5UPLOAD.browser.WorkerSupported=!1);if("html5plus"==a.userRunTimeMode&&DEXT5UPLOAD.browser.WorkerSupported){ba="";C=DEXT5UPLOAD.ReleaseVer;"1"==a.cacheProtectMode&&(C=(new Date).getTime());ba=DEXT5UPLOAD.isRelease?a.webPath.js+"dext5upload.uploadplus.min.js?ver="+C:a.webPath.jsDev+"dext5upload.uploadplus.js?ver="+C;try{(new Worker(ba)).terminate()}catch(bc){DEXT5UPLOAD.browser.WorkerSupported=
!1}}if(1==DEXT5UPLOAD.browser.WorkerSupported){var ca=new Worker(DEXT5UPLOAD.isRelease?a.webPath.js+"dext5upload.processfile.min.js?ver="+C:a.webPath.jsDev+"dext5upload.processfile.js?ver="+C);ca.onmessage=function(a){a=a.data;switch(a.type){case "check_formdata":DEXT5UPLOAD.browser.WorkerSupported=a.isFormDataSupport,ca.terminate()}};ca.onerror=function(a){ca.terminate()};ca.postMessage({type:"check_formdata"})}var cb=DEXT5UPLOAD.util.xml.getNodeValue(f,"plugin_version");""!=cb&&(a.plugin_version=
cb);a.mode=a.mode.toLowerCase();"edit"==a.mode&&(a.mode="upload");var wa,H=DEXT5UPLOAD.util.xml.getNode(f,"show_status_bar");""!=DEXT5UPLOAD.config.StatusBar?a.showStatusBar=DEXT5UPLOAD.config.StatusBar:(wa=DEXT5UPLOAD.util.xml.getNodeValue(f,"show_status_bar"),""!=wa&&(a.showStatusBar=wa));"1"==a.showStatusBar&&("0"==DEXT5UPLOAD.config.StatusBarShowLimit?a.statusBarShowLimit=DEXT5UPLOAD.config.StatusBarShowLimit:H&&H.getAttribute("show_limit")&&""!=H.getAttribute("show_limit")&&(a.statusBarShowLimit=
H.getAttribute("show_limit")),"0"==DEXT5UPLOAD.config.StatusBarShowStatus?a.statusBarShowStatus=DEXT5UPLOAD.config.StatusBarShowStatus:H&&H.getAttribute("show_status")&&""!=H.getAttribute("show_status")&&(a.statusBarShowStatus=H.getAttribute("show_status")));if(""!=DEXT5UPLOAD.config.HeaderBar)a.showHeaderBar=DEXT5UPLOAD.config.HeaderBar;else{"0"==DEXT5UPLOAD.util.xml.getNodeValue(f,"show_header_bar")&&(a.showHeaderBar="0");var ja=DEXT5UPLOAD.util.xml.getNode(f,"show_header_bar");ja&&ja.getAttribute("header_height")&&
""!=ja.getAttribute("header_height")&&(a.customHeaderHeight=ja.getAttribute("header_height"),DEXT5UPLOAD.util.parseIntOr0(a.customHeaderHeight)<a.minHeaderBarHeight&&(a.customHeaderHeight="28px"))}if(""!=DEXT5UPLOAD.config.ButtonBar||""!=DEXT5UPLOAD.config.ButtonBarEdit){var ka="";""!=DEXT5UPLOAD.config.ButtonBar&&(ka=DEXT5UPLOAD.config.ButtonBar);""!=DEXT5UPLOAD.config.ButtonBarEdit&&(ka=DEXT5UPLOAD.config.ButtonBarEdit);a.showButtonBarEdit="0"==ka?"":ka.split(",")}else{var R=DEXT5UPLOAD.util.xml.getNodeValue(f,
"show_button_bar_edit");""!=R&&(a.showButtonBarEdit=R.split(","))}""!=DEXT5UPLOAD.config.ShowEditAlign?a.showEditAlign=DEXT5UPLOAD.config.ShowEditAlign:(R=DEXT5UPLOAD.util.xml.getNode(f,"show_button_bar_edit"))&&R.getAttribute("align")&&""!=R.getAttribute("align")&&(a.showEditAlign=R.getAttribute("align"));if(""!=DEXT5UPLOAD.config.ButtonBarView)a.showButtonBarView="0"==DEXT5UPLOAD.config.ButtonBarView?"":DEXT5UPLOAD.config.ButtonBarView.split(",");else{var S=DEXT5UPLOAD.util.xml.getNodeValue(f,"show_button_bar_view");
""!=S&&(a.showButtonBarView=S.split(","))}""!=DEXT5UPLOAD.config.ShowViewAlign?a.showViewAlign=DEXT5UPLOAD.config.ShowViewAlign:(S=DEXT5UPLOAD.util.xml.getNode(f,"show_button_bar_view"))&&S.getAttribute("align")&&""!=S.getAttribute("align")&&(a.showViewAlign=S.getAttribute("align"));if(""!=DEXT5UPLOAD.config.ButtonBarPosition)a.buttonBarPosition=DEXT5UPLOAD.config.ButtonBarPosition;else{var db=DEXT5UPLOAD.util.xml.getNodeValue(f,"button_bar_position");""!=db&&(a.buttonBarPosition=db)}var I=DEXT5UPLOAD.util.xml.getNode(f,
"resume_mode");""!=DEXT5UPLOAD.config.ResumeUpload?a.resumeUpload=DEXT5UPLOAD.config.ResumeUpload:I&&I.getAttribute("upload")&&""!=I.getAttribute("upload")&&(a.resumeUpload=I.getAttribute("upload"));""!=DEXT5UPLOAD.config.ResumeDownload?a.resumeDownload=DEXT5UPLOAD.config.ResumeDownload:I&&I.getAttribute("download")&&""!=I.getAttribute("download")&&(a.resumeDownload=I.getAttribute("download"));if(""!=DEXT5UPLOAD.config.FolderTransfer)a.folderTransfer=DEXT5UPLOAD.config.FolderTransfer;else{var da=
DEXT5UPLOAD.util.xml.getNodeValue(f,"folder_transfer");""!=da&&(a.folderTransfer=da)}"0"!=a.folderTransfer&&"ieplugin"==a.userRunTimeMode&&(""!=DEXT5UPLOAD.config.FolderDetailHeader?a.folderDetailHeader=DEXT5UPLOAD.config.FolderDetailHeader:(da=DEXT5UPLOAD.util.xml.getNode(f,"folder_transfer"))&&da.getAttribute("folder_detail_header")&&(a.folderDetailHeader=da.getAttribute("folder_detail_header")));if(""!=DEXT5UPLOAD.config.UseServerFileSize)a.useServerFileSize=DEXT5UPLOAD.config.UseServerFileSize;
else{var eb=DEXT5UPLOAD.util.xml.getNodeValue(f,"use_server_file_size");""!=eb&&(a.useServerFileSize=eb)}if(""!=DEXT5UPLOAD.config.UseAddEvent)a.useAddEvent=DEXT5UPLOAD.config.UseAddEvent;else{var fb=DEXT5UPLOAD.util.xml.getNodeValue(f,"use_add_event");""!=fb&&(a.useAddEvent=fb)}if(""!=DEXT5UPLOAD.config.UseDeleteEvent)a.useDeleteEvent=DEXT5UPLOAD.config.UseDeleteEvent;else{var gb=DEXT5UPLOAD.util.xml.getNodeValue(f,"use_delete_event");""!=gb&&(a.useDeleteEvent=gb)}if(""!=DEXT5UPLOAD.config.UseViewOrOpenEvent)a.useViewOrOpenEvent=
DEXT5UPLOAD.config.UseViewOrOpenEvent;else{var hb=DEXT5UPLOAD.util.xml.getNodeValue(f,"use_view_or_open_event");""!=hb&&(a.useViewOrOpenEvent=hb)}if(""!=DEXT5UPLOAD.config.UseUploadingCancelEvent)a.useUploadingCancelEvent=DEXT5UPLOAD.config.UseUploadingCancelEvent;else{var ib=DEXT5UPLOAD.util.xml.getNodeValue(f,"use_uploading_cancel_event");""!=ib&&(a.useUploadingCancelEvent=ib)}if(""!=DEXT5UPLOAD.config.UseDownloadEvent)a.useDownloadEvent=DEXT5UPLOAD.config.UseDownloadEvent;else{var jb=DEXT5UPLOAD.util.xml.getNodeValue(f,
"use_download_event");""!=jb&&(a.useDownloadEvent=jb)}if(""!=DEXT5UPLOAD.config.UseAfterAddEvent)a.useAfterAddEvent=DEXT5UPLOAD.config.UseAfterAddEvent;else{var kb=DEXT5UPLOAD.util.xml.getNodeValue(f,"use_after_add_event");""!=kb&&(a.useAfterAddEvent=kb)}if(""!=DEXT5UPLOAD.config.UseAfterAddEndTimeEvent)a.useAfterAddEndTimeEvent=DEXT5UPLOAD.config.UseAfterAddEndTimeEvent;else{var lb=DEXT5UPLOAD.util.xml.getNodeValue(f,"use_after_add_end_time_event");""!=lb&&(a.useAfterAddEndTimeEvent=lb)}if(""!=DEXT5UPLOAD.config.UseAfterDownloadEvent)a.useAfterDownloadEvent=
DEXT5UPLOAD.config.UseAfterDownloadEvent;else{var mb=DEXT5UPLOAD.util.xml.getNodeValue(f,"use_after_download_event");""!=mb&&(a.useAfterDownloadEvent=mb)}if(""!=DEXT5UPLOAD.config.Timeout)a.timeout=DEXT5UPLOAD.config.Timeout;else{var nb=DEXT5UPLOAD.util.xml.getNodeValue(f,"timeout");""!=nb&&(a.timeout=nb)}if(""!=DEXT5UPLOAD.config.AutomaticConnection)a.automaticConnection=DEXT5UPLOAD.config.automaticConnection;else{var ob=DEXT5UPLOAD.util.xml.getNodeValue(f,"automatic_connection");""!=ob&&(a.automaticConnection=
ob)}""!=DEXT5UPLOAD.config.ShowFolderView?a.showFolderView=DEXT5UPLOAD.config.ShowFolderView:"0"==DEXT5UPLOAD.util.xml.getNodeValue(f,"show_folder_view")&&(a.showFolderView="0");if(""!=DEXT5UPLOAD.config.MessageTitle)a.messageTitle=DEXT5UPLOAD.config.MessageTitle;else{var pb=DEXT5UPLOAD.util.xml.getNodeValue(f,"message_title");""!=pb&&(a.messageTitle=pb)}""!=DEXT5UPLOAD.config.UseScriptEventControl?a.useScriptEventControl=DEXT5UPLOAD.config.UseScriptEventControl:"0"==DEXT5UPLOAD.util.xml.getNodeValue(f,
"use_script_event_control")&&(a.useScriptEventControl="0");for(var qb=DEXT5UPLOAD.util.xml.getNode(d,"add_ext_icon"),Qb=DEXT5UPLOAD.util.xml.count(qb,"icon"),y=0;y<Qb;y++){var Rb=DEXT5UPLOAD.util.xml.getNodeValueIdx(qb,"icon",y);a.addExtIcon[y]=Rb}""!=DEXT5UPLOAD.config.SkinName?a.skinName=DEXT5UPLOAD.config.SkinName:(X=DEXT5UPLOAD.util.xml.getNodeValue(f,"skin_name"),0<X.length&&(a.skinName=X));if(""!=DEXT5UPLOAD.config.ShowCheckBox)a.showCheckBox=DEXT5UPLOAD.config.ShowCheckBox;else{var rb=DEXT5UPLOAD.util.xml.getNodeValue(f,
"show_checkbox");""!=rb&&(a.showCheckBox=rb)}if(""!=DEXT5UPLOAD.config.HideContextMenu)a.hideContextMenu=DEXT5UPLOAD.config.HideContextMenu;else{var sb=DEXT5UPLOAD.util.xml.getNodeValue(f,"hide_context_menu");""!=sb&&(a.hideContextMenu=sb)}"0"==DEXT5UPLOAD.config.SizeColumnWidth?a.sizeColumnWidth=DEXT5UPLOAD.config.SizeColumnWidth:"0"==DEXT5UPLOAD.util.xml.getNodeValue(f,"use_size_column")&&(a.sizeColumnWidth="0");var J=DEXT5UPLOAD.util.xml.getNode(f,"file_delimiter");""!=DEXT5UPLOAD.config.UnitDelimiter?
a.unitDelimiter=String.fromCharCode(DEXT5UPLOAD.config.UnitDelimiter):J&&J.getAttribute("unit_delimiter")&&""!=J.getAttribute("unit_delimiter")&&(a.unitDelimiter=String.fromCharCode(J.getAttribute("unit_delimiter")));""!=DEXT5UPLOAD.config.UnitDelimiter?a.unitAttributeDelimiter=String.fromCharCode(DEXT5UPLOAD.config.UnitAttributeDelimiter):J&&J.getAttribute("unit_attribute_delimiter")&&""!=J.getAttribute("unit_attribute_delimiter")&&(a.unitAttributeDelimiter=String.fromCharCode(J.getAttribute("unit_attribute_delimiter")));
""!=DEXT5UPLOAD.config.UseAutoHeight?a.useAutoHeight=DEXT5UPLOAD.config.UseAutoHeight:"1"==DEXT5UPLOAD.util.xml.getNodeValue(f,"use_auto_height")&&(a.useAutoHeight="1");if(""!=DEXT5UPLOAD.config.RemoveContextItem)a.removeContextItem=DEXT5UPLOAD.config.RemoveContextItem;else{var tb=DEXT5UPLOAD.util.xml.getNodeValue(f,"remove_context_item");""!=tb&&(a.removeContextItem=tb)}"form"==a.subMode&&(a.hideContextMenu="1");""!=DEXT5UPLOAD.config.DisplayFileSizeHtml4?a.displayFileSizeHtml4=DEXT5UPLOAD.config.DisplayFileSizeHtml4:
"1"==DEXT5UPLOAD.util.xml.getNodeValue(f,"display_file_size_html4")&&(a.displayFileSizeHtml4="1");""!=DEXT5UPLOAD.config.AllowedZeroFileSize?a.allowedZeroFileSize=DEXT5UPLOAD.config.AllowedZeroFileSize:"1"==DEXT5UPLOAD.util.xml.getNodeValue(f,"allowed_zero_file_size")&&(a.allowedZeroFileSize="1");""!=DEXT5UPLOAD.config.UseDropzone?a.useDropzone=DEXT5UPLOAD.config.UseDropzone:"1"==DEXT5UPLOAD.util.xml.getNodeValue(f,"use_dropzone")&&(a.useDropzone="1");""!=DEXT5UPLOAD.config.UseZipDownload?a.useZipDownload=
DEXT5UPLOAD.config.UseZipDownload:"1"==DEXT5UPLOAD.util.xml.getNodeValue(f,"use_zip_download")&&(a.useZipDownload="1");if(""!=DEXT5UPLOAD.config.AllowOpenExtension)a.allowOpenExtension=DEXT5UPLOAD.config.AllowOpenExtension;else{var xa=DEXT5UPLOAD.util.xml.getNodeValue(f,"allow_open_extension");xa&&""!=xa&&(a.allowOpenExtension=xa)}""!=a.allowOpenExtension&&"1"==a.hybridDownload&&(a.allowOpenExtension="");if(""!=DEXT5UPLOAD.config.FileFilterEx)a.fileFilterEx=DEXT5UPLOAD.config.FileFilterEx;else{var ya=
DEXT5UPLOAD.util.xml.getNodeValue(f,"file_filter_ex");ya&&""!=ya&&(a.fileFilterEx=ya)}if(""!=DEXT5UPLOAD.config.DownloadMulti)a.downloadMulti=DEXT5UPLOAD.config.DownloadMulti;else{var ub=DEXT5UPLOAD.util.xml.getNodeValue(g,"download_multi");0<ub.length&&(a.downloadMulti=ub)}if(""!=DEXT5UPLOAD.config.PluginZip)a.pluginZip=DEXT5UPLOAD.config.PluginZip;else{var za=DEXT5UPLOAD.util.xml.getNode(g,"download_multi").getAttribute("plugin_zip");za&&0<za.length&&(a.pluginZip=za)}""!=DEXT5UPLOAD.config.NTLM&&
-1<DEXT5UPLOAD.config.NTLM.indexOf("Basic")&&(a.NTLM=DEXT5UPLOAD.config.NTLM);if(""!=DEXT5UPLOAD.config.LargeFiles){var vb=DEXT5UPLOAD.config.LargeFiles.Size?DEXT5UPLOAD.config.LargeFiles.Size:"0",r=DEXT5UPLOAD.util.getUnit(vb),n=DEXT5UPLOAD.util.getUnitSize(r),M=parseInt(vb,10);a.largeFiles.markSize=M*n;var wb=DEXT5UPLOAD.config.LargeFiles.MaxTotalSize?DEXT5UPLOAD.config.LargeFiles.MaxTotalSize:"0",r=DEXT5UPLOAD.util.getUnit(wb),n=DEXT5UPLOAD.util.getUnitSize(r),M=parseInt(wb,10);a.largeFiles.maxTotalSize=
M*n;a.largeFiles.maxCount=DEXT5UPLOAD.config.LargeFiles.MaxCount?DEXT5UPLOAD.config.LargeFiles.MaxCount:0;a.largeFiles.text=DEXT5UPLOAD.config.LargeFiles.Text?DEXT5UPLOAD.config.LargeFiles.Text:"";a.largeFiles.color=DEXT5UPLOAD.config.LargeFiles.Color?DEXT5UPLOAD.config.LargeFiles.Color:"";var xb=DEXT5UPLOAD.config.LargeFiles.BaseTotalSize?DEXT5UPLOAD.config.LargeFiles.BaseTotalSize:"0",r=DEXT5UPLOAD.util.getUnit(xb),n=DEXT5UPLOAD.util.getUnitSize(r),M=parseInt(xb,10);a.largeFiles.markBaseTotalSize=
M*n;a.largeFiles.customMode=DEXT5UPLOAD.config.LargeFiles.CustomMode?DEXT5UPLOAD.config.LargeFiles.CustomMode:"0"}else{var Aa=DEXT5UPLOAD.util.xml.getNodeValue(f,"large_files"),l=DEXT5UPLOAD.util.xml.getNode(f,"large_files");if(0<Aa.length&&0<Aa||l&&l.getAttribute("base_total_size")&&0<l.getAttribute("base_total_size").length||l&&l.getAttribute("custom_mode")&&0<l.getAttribute("custom_mode").length){if(l.getAttribute("unit")&&""!=l.getAttribute("unit")){var n=DEXT5UPLOAD.util.getUnitSize(l.getAttribute("unit")),
Sb=DEXT5UPLOAD.util.parseIntOr0(Aa,10)*n;a.largeFiles.markSize=Sb}l.getAttribute("max_count")&&""!=l.getAttribute("max_count")&&(a.largeFiles.maxCount=DEXT5UPLOAD.util.parseIntOr0(l.getAttribute("max_count")));if(l.getAttribute("max_total_size")&&""!=l.getAttribute("max_total_size")){var r=l.getAttribute("unit")?l.getAttribute("unit"):"b",n=DEXT5UPLOAD.util.getUnitSize(r),Tb=DEXT5UPLOAD.util.parseIntOr0(l.getAttribute("max_total_size"))*n;a.largeFiles.maxTotalSize=Tb}l.getAttribute("color")&&""!=
l.getAttribute("color")&&(a.largeFiles.color=l.getAttribute("color"));l.getAttribute("text")&&""!=l.getAttribute("text")&&(a.largeFiles.text=l.getAttribute("text"));l.getAttribute("base_total_size")&&""!=l.getAttribute("base_total_size")&&(n=1,l.getAttribute("unit")&&""!=l.getAttribute("unit")&&(n=DEXT5UPLOAD.util.getUnitSize(l.getAttribute("unit"))),a.largeFiles.markBaseTotalSize=DEXT5UPLOAD.util.parseIntOr0(l.getAttribute("base_total_size"))*n);l.getAttribute("custom_mode")&&"1"==l.getAttribute("custom_mode")&&
(a.largeFiles.customMode="1")}}""!=DEXT5UPLOAD.config.Views?a.views=DEXT5UPLOAD.config.Views:(G=DEXT5UPLOAD.util.xml.getNode(f,"mode"))&&G.getAttribute("views")&&""!=G.getAttribute("views")&&(a.views=G.getAttribute("views"));if(""!=DEXT5UPLOAD.config.UploadMethodHtml4)a.uploadMethodHtml4=DEXT5UPLOAD.config.UploadMethodHtml4;else{var yb=DEXT5UPLOAD.util.xml.getNodeValue(g,"upload_method_html4");"0"==yb&&(a.uploadMethodHtml4=yb)}if("html4"==a.userRunTimeMode&&"1"==a.uploadMethodHtml4)if(""!=DEXT5UPLOAD.config.Html4LimitFileSize)a.html4LimitFileSize=
DEXT5UPLOAD.config.Html4LimitFileSize;else{var la=DEXT5UPLOAD.util.xml.getNode(g,"upload_method_html4");la&&la.getAttribute("html4_limit_file_size")&&""!=la.getAttribute("html4_limit_file_size")&&(a.html4LimitFileSize=la.getAttribute("html4_limit_file_size"))}"html4"==a.userRunTimeMode&&"0"==a.uploadMethodHtml4&&(a.imgPreView="0",a.views="list");"thumbs"==a.views&&(a.largeFiles={markSize:0,maxCount:0,maxTotalSize:0,text:"",color:""});""!=DEXT5UPLOAD.config.CacheProtectMode?a.cacheProtectMode=DEXT5UPLOAD.config.CacheProtectMode:
"1"==DEXT5UPLOAD.util.xml.getNodeValue(f,"cache_protect_mode")&&(a.cacheProtectMode="1");"1"==DEXT5UPLOAD.util.xml.getNodeValue(f,"force_re_draw")&&(a.forceReDraw="1");var v=DEXT5UPLOAD.util.xml.getNode(f,"file_sort");if("form"==a.subMode)a.use_file_sort="0";else if("0"==DEXT5UPLOAD.config.UseFileSort||"1"==DEXT5UPLOAD.config.UseFileSort){if(a.use_file_sort=DEXT5UPLOAD.config.UseFileSort,"1"==DEXT5UPLOAD.config.FileSortField&&(a.sort_field=DEXT5UPLOAD.config.FileSortField),"1"==DEXT5UPLOAD.config.FileSortAscDesc&&
(a.sort_ascdesc=DEXT5UPLOAD.config.FileSortAscDesc),"1"==DEXT5UPLOAD.config.AutoSort||"2"==DEXT5UPLOAD.config.AutoSort)a.auto_sort=DEXT5UPLOAD.config.AutoSort}else"0"==DEXT5UPLOAD.util.xml.getNodeValue(f,"file_sort")&&(a.use_file_sort="0"),DEXT5UPLOAD.util.xml.getNode(v,"file_sort"),v&&v.getAttribute("sort_field")&&"1"==v.getAttribute("sort_field")&&(a.sort_field="1"),v&&v.getAttribute("sort_ascdesc")&&"1"==v.getAttribute("sort_ascdesc")&&(a.sort_ascdesc="1"),v&&v.getAttribute("auto_sort")&&("1"==
v.getAttribute("auto_sort")||"2"==v.getAttribute("auto_sort"))&&(a.auto_sort=v.getAttribute("auto_sort"));"1"==DEXT5UPLOAD.config.FileMoveContextMenu?a.fileMoveContextMenu=DEXT5UPLOAD.config.FileMoveContextMenu:"1"==DEXT5UPLOAD.util.xml.getNodeValue(f,"file_move_context_menu")&&(a.fileMoveContextMenu="1");"1"==DEXT5UPLOAD.config.CompleteEventResetUse?a.completeEventResetUse=DEXT5UPLOAD.config.CompleteEventResetUse:"1"==DEXT5UPLOAD.util.xml.getNodeValue(f,"complete_event_reset_use")&&(a.completeEventResetUse=
"1");"thumbs"==a.views&&(a.fileMoveContextMenu="0");var zb,K=DEXT5UPLOAD.util.xml.getNode(f,"img_preview");""!=DEXT5UPLOAD.config.ImgPreView?a.imgPreView=DEXT5UPLOAD.config.ImgPreView:(zb=DEXT5UPLOAD.util.xml.getNodeValue(f,"img_preview"),"1"==zb&&(a.imgPreView="1"));1==DEXT5UPLOAD.browser.mobile&&(a.imgPreView="0");"1"==a.imgPreView&&(""!=DEXT5UPLOAD.config.ImgPreViewWidth?(a.imgPreViewWidth=DEXT5UPLOAD.config.ImgPreViewWidth,100>=DEXT5UPLOAD.util.parseIntOr0(a.imgPreViewWidth)&&(a.imgPreViewWidth=
"100px")):K&&K.getAttribute("width")&&""!=K.getAttribute("width")&&(a.imgPreViewWidth=K.getAttribute("width"),100>=DEXT5UPLOAD.util.parseIntOr0(a.imgPreViewWidth)&&(a.imgPreViewWidth="100px")),""!=DEXT5UPLOAD.config.ImgPreViewHeight?(a.imgPreViewHeight=DEXT5UPLOAD.config.ImgPreViewHeight,100>=DEXT5UPLOAD.util.parseIntOr0(a.imgPreViewHeight)&&(a.imgPreViewHeight="100px")):K&&K.getAttribute("height")&&""!=K.getAttribute("height")&&(a.imgPreViewHeight=K.getAttribute("height"),100>=DEXT5UPLOAD.util.parseIntOr0(a.imgPreViewHeight)&&
(a.imgPreViewHeight="100px")));if(""!=DEXT5UPLOAD.config.UserMessage)a.userMessage.edit=DEXT5UPLOAD.config.UserMessage.Edit?DEXT5UPLOAD.config.UserMessage.Edit:"",a.userMessage.view=DEXT5UPLOAD.config.UserMessage.View?DEXT5UPLOAD.config.UserMessage.View:"";else if("1"==DEXT5UPLOAD.util.xml.getNodeValue(f,"user_message")){var T=DEXT5UPLOAD.util.xml.getNode(f,"user_message");T.getAttribute("edit")&&""!=T.getAttribute("edit")&&(a.userMessage.edit=T.getAttribute("edit"));T.getAttribute("view")&&""!=T.getAttribute("view")&&
(a.userMessage.view=T.getAttribute("view"))}""!=DEXT5UPLOAD.config.UseSingleSelect?a.useSingleSelect=DEXT5UPLOAD.config.UseSingleSelect:(xmlUseSingleSelect=DEXT5UPLOAD.util.xml.getNodeValue(f,"use_single_select"),"1"==xmlUseSingleSelect&&(a.useSingleSelect="1"));var U=DEXT5UPLOAD.util.xml.getNode(f,"disable_alert_message");if(DEXT5UPLOAD.config.DisableAlertMessage.Duplication&&""!=DEXT5UPLOAD.config.DisableAlertMessage.Duplication)a.disableAlertMessage.duplication=DEXT5UPLOAD.config.DisableAlertMessage.Duplication;
else{var Ab=DEXT5UPLOAD.util.xml.getNodeValue(U,"duplication");"0"==Ab&&(a.disableAlertMessage.duplication=Ab)}if(DEXT5UPLOAD.config.DisableAlertMessage.DeleteUnchosen&&""!=DEXT5UPLOAD.config.DisableAlertMessage.DeleteUnchosen)a.disableAlertMessage.deleteUnchosen=DEXT5UPLOAD.config.DisableAlertMessage.DeleteUnchosen;else{var Bb=DEXT5UPLOAD.util.xml.getNodeValue(U,"delete_unchosen");"0"==Bb&&(a.disableAlertMessage.deleteUnchosen=Bb)}if(DEXT5UPLOAD.config.DisableAlertMessage.DownloadUnchosen&&""!=DEXT5UPLOAD.config.DisableAlertMessage.DownloadUnchosen)a.disableAlertMessage.downloadUnchosen=
DEXT5UPLOAD.config.DisableAlertMessage.DownloadUnchosen;else{var Cb=DEXT5UPLOAD.util.xml.getNodeValue(U,"download_unchosen");"0"==Cb&&(a.disableAlertMessage.downloadUnchosen=Cb)}if(DEXT5UPLOAD.config.DisableAlertMessage.OpenUnchosen&&""!=DEXT5UPLOAD.config.DisableAlertMessage.OpenUnchosen)a.disableAlertMessage.openUnchosen=DEXT5UPLOAD.config.DisableAlertMessage.OpenUnchosen;else{var Db=DEXT5UPLOAD.util.xml.getNodeValue(U,"open_unchosen");"0"==Db&&(a.disableAlertMessage.openUnchosen=Db)}if(""!=DEXT5UPLOAD.config.DisableDeleteConfirmMessage)a.disableAlertMessage.disableDeleteConfirm=
DEXT5UPLOAD.config.DisableDeleteConfirmMessage;else{var ma=DEXT5UPLOAD.util.xml.getNodeValue(f,"disable_delete_confirm_message");if("1"==ma||"2"==ma||"3"==ma)a.disableAlertMessage.disableDeleteConfirm=ma}if(DEXT5UPLOAD.config.DisableAlertMessage.DisableDeleteConfirm&&""!=DEXT5UPLOAD.config.DisableAlertMessage.DisableDeleteConfirm)a.disableAlertMessage.disableDeleteConfirm=DEXT5UPLOAD.config.DisableAlertMessage.DisableDeleteConfirm;else{var ea=DEXT5UPLOAD.util.xml.getNodeValue(U,"disable_delete_confirm");
if("0"==ea||"1"==ea||"2"==ea||"3"==ea)a.disableAlertMessage.disableDeleteConfirm=ea}if(DEXT5UPLOAD.config.DisableAlertMessage.FileExtensionDetect&&""!=DEXT5UPLOAD.config.DisableAlertMessage.FileExtensionDetect)a.disableAlertMessage.fileExtensionDetect=DEXT5UPLOAD.config.DisableAlertMessage.FileExtensionDetect;else{var Eb=DEXT5UPLOAD.util.xml.getNodeValue(U,"file_extension_detect");"1"==Eb&&(a.disableAlertMessage.fileExtensionDetect=Eb)}if(""!=DEXT5UPLOAD.config.DirectDownload.toString())a.directDownload=
DEXT5UPLOAD.config.DirectDownload;else{var Fb=DEXT5UPLOAD.util.xml.getNodeValue(f,"direct_download");""!=Fb&&(a.directDownload=Fb)}1==a.directDownload&&(a.downloadMulti=1);var Ub=DEXT5UPLOAD.util.xml.getNode(f,"security");DEXT5UPLOAD.util.setSecuritySetting(Ub,a,!1);if("1"==a.security.fileIntegrity||"1"==a.security.fileEncrypt)a.uploadMethod="0";"0"==a.uploadMethod&&(DEXT5UPLOAD.browser.ajaxOnProgressSupported=!1);var na=DEXT5UPLOAD.util.xml.getNode(d,"header_item");DEXT5UPLOAD.util.xml.getNode(na,
"item");var Vb=DEXT5UPLOAD.util.xml.count(na,"item");if(""!=DEXT5UPLOAD.config.HeaderBarItem){var Ba=DEXT5UPLOAD.config.HeaderBarItem.split(",");DEXT5UPLOAD.config.HeaderBarItemWidth=DEXT5UPLOAD.config.HeaderBarItemWidth.replace(/\%/gi,"px");var Ca=DEXT5UPLOAD.config.HeaderBarItemWidth.split(","),Da=DEXT5UPLOAD.config.HeaderBarItemAlign.split(",");Ba&&""!=Ba&&(a.headerBarItem=Ba);Ca&&""!=Ca&&(a.headerBarItemWidth=Ca);Da&&""!==Da&&(a.headerBarItemAlign=Da)}else for(y=0;y<Vb;y++){var Wb=DEXT5UPLOAD.util.xml.getNodeValueIdx(na,
"item",y);a.headerBarItem.push(Wb);var Ea=DEXT5UPLOAD.util.xml.getNodeIdx(na,"item",y);a.headerBarItemWidth.push(Ea.getAttribute("width").replace(/\%/gi,"px"));Ea.getAttribute("align")?a.headerBarItemAlign[y]=Ea.getAttribute("align").toLowerCase():a.headerBarItemAlign[y]="left"}DEXT5UPLOAD.config.GroupId&&""!=DEXT5UPLOAD.config.GroupId&&(a.groupId=DEXT5UPLOAD.config.GroupId);if(""!=DEXT5UPLOAD.config.TransferOpenFile)a.transferOpenFile=DEXT5UPLOAD.config.TransferOpenFile;else{var Gb=DEXT5UPLOAD.util.xml.getNodeValue(f,
"transfer_open_file");""!=Gb&&(a.transferOpenFile=Gb)}if(""!=DEXT5UPLOAD.config.SelectByClicked)a.selectByClicked=DEXT5UPLOAD.config.SelectByClicked;else{var Hb=DEXT5UPLOAD.util.xml.getNodeValue(f,"select_by_clicked");""!=Hb&&(a.selectByClicked=Hb)}if(-1<a.userRunTimeMode.indexOf("html5"))if(""!=DEXT5UPLOAD.config.ImageQuality)DEXT5UPLOAD.config.ImageQuality.Quality&&""!=DEXT5UPLOAD.config.ImageQuality.Quality&&(a.imageQuality.quality=parseFloat(DEXT5UPLOAD.config.ImageQuality.Quality),DEXT5UPLOAD.config.ImageQuality.WorkerCount&&
""!=DEXT5UPLOAD.config.ImageQuality.WorkerCount&&(a.imageQuality.workerCount=DEXT5UPLOAD.util.parseIntOr0(DEXT5UPLOAD.config.ImageQuality.WorkerCount)));else{var Ib=DEXT5UPLOAD.util.xml.getNodeValue(f,"image_quality");if(""!=Ib){a.imageQuality.quality=parseFloat(Ib);var Fa=DEXT5UPLOAD.util.xml.getNode(f,"image_quality");Fa.getAttribute("worker_count")&&""!=Fa.getAttribute("worker_count")&&(a.imageQuality.workerCount=DEXT5UPLOAD.util.parseIntOr0(Fa.getAttribute("worker_count")))}}if(""!=DEXT5UPLOAD.config.DownloadPartialSize)r=
DEXT5UPLOAD.util.getUnit(DEXT5UPLOAD.config.DownloadPartialSize),n=DEXT5UPLOAD.util.getUnitSize(r),Y=parseInt(DEXT5UPLOAD.config.DownloadPartialSize,10),a.downloadPartialSize=Y*n;else{var Jb=DEXT5UPLOAD.util.xml.getNodeValue(f,"download_partial_size");if(0<Jb.length){var Ga=DEXT5UPLOAD.util.xml.getNode(f,"download_partial_size");Ga.getAttribute("unit")&&""!=Ga.getAttribute("unit")&&(n=DEXT5UPLOAD.util.getUnitSize(Ga.getAttribute("unit")),a.downloadPartialSize=parseInt(Jb,10)*n)}}0<a.downloadPartialSize&&
"1"==a.resumeDownload&&(a.downloadPartialSize=0);var L=document.location.href;-1<L.indexOf("?")&&(L=L.substring(0,L.indexOf("?")));if("NONE"==a.developLang.toUpperCase()&&""!=a.licenseKeyEx){if(DEXT5UPLOAD.util.setSecuritySetting(null,a,!0),a.sizeForChunkUpload=0,a.uploadMethod="1",0==a.maxOneFileSize||2147483648<a.maxOneFileSize)a.maxOneFileSize=2147483648}else{var V=a.handlerUrl,V=-1<V.indexOf("?")?V+("&t="+(new Date).getTime()):V+("?t="+(new Date).getTime()),W=a.licenseKey;"1"==a.licenseKeySE&&
"0"==a.security.encryptParam&&(W=DEXT5UPLOAD.util.base64_encode(W));if(a.isCrossDomain){var D=document.createElement("div"),Xb=DEXT5UPLOAD.util.getDefaultIframeSrc();D.innerHTML='<iframe name="initCheckframe" id="initCheckframe" style="display:none;" src="'+Xb+'"></iframe>';D.style.display="none";document.body.appendChild(D);var oa;if("1"==a.security.encryptParam){var m="",m=m+("d01"+a.trans_unitAttributeDelimiter+"initRequest"+a.trans_unitDelimiter),m=m+("d40"+a.trans_unitAttributeDelimiter+L+a.trans_unitDelimiter),
m=m+("d02"+a.trans_unitAttributeDelimiter+a.productKey+a.trans_unitDelimiter),m=m+("d03"+a.trans_unitAttributeDelimiter+W+a.trans_unitDelimiter),m=m+("d04"+a.trans_unitAttributeDelimiter+"1"+a.trans_unitDelimiter),m=m+("d06"+a.trans_unitAttributeDelimiter+"DEXT5U"+a.trans_unitDelimiter),m=DEXT5UPLOAD.util.makeEncryptParam(m);oa=[["d00",m]]}else oa=[["dext5CMD","initRequest"],["domain",L],["productKey",a.productKey],["licenseKey",W],["cd","1"],["pn","DEXT5U"]],"1"==a.licenseKeySE&&oa.push(["Se","Y"]);
DEXT5UPLOAD.util.postFormData(document,V,"initCheckframe",oa);DEXT5UPLOAD.util.addEvent(D.firstChild,"load",function(){D.firstChild.contentWindow.postMessage("check","*")},!0);if(window.postMessage){var Kb=function(b){b=DEXT5UPLOAD.util.trim(b.data);initLicenseCheck(b,a);document.body.removeChild(D);DEXT5UPLOAD.util.removeEvent(window,"message",Kb)};DEXT5UPLOAD.util.addEvent(window,"message",Kb)}}else{var fa="";"1"==a.security.encryptParam?(m="",m+="d01"+a.trans_unitAttributeDelimiter+"initRequest"+
a.trans_unitDelimiter,m+="d40"+a.trans_unitAttributeDelimiter+L+a.trans_unitDelimiter,m+="d02"+a.trans_unitAttributeDelimiter+a.productKey+a.trans_unitDelimiter,m+="d03"+a.trans_unitAttributeDelimiter+W+a.trans_unitDelimiter,m+="d06"+a.trans_unitAttributeDelimiter+"DEXT5U"+a.trans_unitDelimiter,m=DEXT5UPLOAD.util.makeEncryptParam(m),fa="d00="+m):(fa="dext5CMD=initRequest&domain="+L+"&productKey="+a.productKey+"&licenseKey="+W+"&pn=DEXT5U","1"==a.licenseKeySE&&(fa+="&Se=Y"));DEXT5UPLOAD.ajax.postData(V,
fa,function(c){initLicenseCheck(c,a,b)})}}if(DEXT5UPLOAD.config.PluginInstallType&&""!=DEXT5UPLOAD.config.PluginInstallType.toString())a.pluginInstallType=DEXT5UPLOAD.config.PluginInstallType;else{var Yb=DEXT5UPLOAD.util.xml.getNodeValue(f,"plugin_install_type");a.pluginInstallType=Yb}if(DEXT5UPLOAD.config.DefaultDownloadPath&&""!=DEXT5UPLOAD.config.DefaultDownloadPath.toString())a.defaultDownloadPath=DEXT5UPLOAD.config.DefaultDownloadPath;else{var Ha=DEXT5UPLOAD.util.xml.getNodeValue(f,"default_download_path");
Ha&&""!=Ha&&(a.defaultDownloadPath=Ha)}if(DEXT5UPLOAD.config.SavePathSetting&&""!=DEXT5UPLOAD.config.SavePathSetting.toString())a.savePathSetting=DEXT5UPLOAD.config.SavePathSetting;else{var Ia=DEXT5UPLOAD.util.xml.getNodeValue(f,"save_path_setting");Ia&&""!=Ia&&(a.savePathSetting=Ia)}var Zb=DEXT5UPLOAD.util.xml.getNode(f,"after_upload");if(DEXT5UPLOAD.config.AftertUpload.SetFileSize&&""!=DEXT5UPLOAD.config.AftertUpload.SetFileSize.toString())a.aftertUpload.setFileSize=DEXT5UPLOAD.config.AftertUpload.SetFileSize;
else{var Ja=DEXT5UPLOAD.util.xml.getNodeValue(Zb,"set_file_size");Ja&&""!=Ja.toString()&&(a.aftertUpload.setFileSize=Ja)}if(""!=DEXT5UPLOAD.config.TransferBackgroundStyle)a.transferBackgroundStyle=DEXT5UPLOAD.config.TransferBackgroundStyle;else{var Lb=DEXT5UPLOAD.util.xml.getNodeValue(f,"transfer_background_style");""!=Lb&&(a.transferBackgroundStyle=Lb)}var pa="",w=a.minHeight,w="1"==a.showHeaderBar?w+DEXT5UPLOAD.util.parseIntOr0(a.customHeaderHeight)-a.minHeaderBarHeight:w-a.minHeaderBarHeight;"0"==
a.showStatusBar&&(w-=a.statusBarHeight);"upload"==a.mode?0==a.showButtonBarEdit.length&&"html4"!=a.userRunTimeMode&&(w-=a.buttonBarHeight):0==a.showButtonBarView.length&&(w-=a.buttonBarHeight);a.minHeight=w;0>a.height.indexOf("%")&&w>DEXT5UPLOAD.util.parseIntOr0(a.height)&&(a.height=w+"px");pa=a.initVisible?'<div id="dext5uploader_holder_'+b+'" style="width:'+a.width+"; height:"+a.height+'"></div>':'<div id="dext5uploader_holder_'+b+'" style="width:'+a.width+'; height:0px; display:none;"></div>';
if(""!=DEXT5UPLOAD.config.UploadHolder){var Mb=document.getElementById(DEXT5UPLOAD.config.UploadHolder);Mb?Mb.innerHTML=pa:document.write(pa)}else document.write(pa);var $b=document.getElementById("dext5uploader_holder_"+b);createUploaderIframe(a,$b,this,"dext5uploader_frame_"+b,"",b);if("1"==a.useDropzone&&"ieplugin"==a.userRunTimeMode&&null==document.getElementById("dext5dropzonePL")){var ga='<object id="dext5dropzonePL" name="dext5dropzonePL" classid="CLSID:F7FEF85C-B9A4-421C-BD01-099E534ABFB0" width="0" height="0" style="width:0px; height:0px;">',
ga=ga+('<param name="nUseDropzone" value="'+a.useDropzone+'">'),ga=ga+"</object>",D=document.createElement("div");D.innerHTML=ga;var Nb=D.firstChild;document.body.appendChild(Nb);11<=DEXT5UPLOAD.browser.ieVersion?createEvent("dext5dropzonePL","d5_event_dropZone_drop(strID, strFullPath, bFolder, nDropCount)","dext5_dropZone_drop(strID, strFullPath, bFolder, nDropCount)"):Nb.attachEvent("d5_event_dropZone_drop",dext5_dropZone_drop)}}}}
function createEvent(b,c,a){var d=document.createElement("script");d.setAttribute("for",b);d.event=c;d.appendChild(document.createTextNode(a));document.body.appendChild(d)}function dext5_dropZone_drop(b,c,a,d){try{DEXT5UPLOAD_DropZoneAddItem(null,c,b)}catch(e){}}
function initLicenseCheck(b,c){if(b&&("hi, dext5 upload !!!"==b.toLowerCase()||-1<b.toLowerCase().indexOf("hi, dext5 upload !!!"))){-1<b.indexOf("-")&&(DEXT5UPLOAD.ServerReleaseVer=b.split("-")[1],b.split("-"),0!=b.split("-")[3].toLowerCase().indexOf("s")&&DEXT5UPLOAD.util.setSecuritySetting(null,c,!0));try{if(""==c.licenseKeyEx&&window.localStorage){var a=DEXT5UPLOAD.util.getDate();window.localStorage.Dext5Upload_gabageCall?a>window.localStorage.Dext5Upload_gabageCall&&(window.localStorage.Dext5Upload_gabageCall=
a,gcRequest_postMessage(c)):(window.localStorage.Dext5Upload_gabageCall=a,gcRequest_postMessage(c))}else gcRequest_postMessage(c)}catch(d){}}else if(b&&0<b.length)-1<b.indexOf(c.unitDelimiter)?(a=b.split(c.unitDelimiter),DEXT5UPLOAD.ServerReleaseVer=a[1],alert(a[0])):alert(b);else{var a="",e=0<DEXT5UPLOAD.config.InitXml.length?DEXT5UPLOAD.config.InitXml:"dext5upload.config.xml";"ko-kr"==c.lang?(a="Uploader\uc758 \uc124\uc815\uac12\uc774 \uc62c\ubc14\ub974\uc9c0 \uc54a\uc2b5\ub2c8\ub2e4. \uc544\ub798 URL \uc811\uadfc\uc774 \uc720\ud6a8\ud558\uc9c0 \uc54a\uc2b5\ub2c8\ub2e4.\n\n"+
(c.handlerUrl+"\n\n"),a+=e+" \ud30c\uc77c\uc758 uploader_setting \uc139\uc158\uc758 <develop_langage>\uc640 <handler_url> \uc124\uc815\uac12\uc744 \ud655\uc778\ud558\uc138\uc694."):(a="Uploader's setting is not correct. Access the following URL is not valid.\n\n"+(c.handlerUrl+"\n\n"),a+='Please check the settings, <handler_url> and <develop_langage> in "uploader_setting" section in the "'+e+'."');c.handlerUrlCheck=!1;alert(a)}}
function createUploaderIframe(b,c,a,d,e,h){var g=document.createElement("iframe");c.appendChild(g);g.id=d;g.title=e;""==g.title&&(g.title="DEXT5Upload");g.frameBorder=0;g.style.width="100%";g.style.height=DEXT5UPLOAD.browser.quirks?b.height:"100%";g.style.borderWidth="0px";c=DEXT5UPLOAD.util.getDefaultIframeSrc();g.src=c;c=function(){try{g.contentWindow.dext_frame_loaded_event(h,b,a);var c=UPLOADTOP.G_CURRUPLOADER.frameWin.getDialogDocument(),d=c.getElementsByTagName("head")[0],e=d.getElementsByTagName("link"),
ha=e.length,k="dext5upload.popup.min.css";DEXT5UPLOAD.isRelease||(k="dext5upload.popup.css");for(var x=!1,p=0;p<ha;p++)-1<e[p].href.indexOf(k)&&(x=!0);if(!x){var z=c.createElement("link");z.type="text/css";z.rel="stylesheet";var B=UPLOADTOP.DEXT5UPLOAD.ReleaseVer;"1"==UPLOADTOP.G_CURRUPLOADER._config.cacheProtectMode&&(B=(new Date).getTime());z.href=DEXT5UPLOAD.isRelease?b.webPath.css+"dext5upload.popup.min.css?ver="+B:b.webPath.cssDev+"dext5upload.popup.css?ver="+B;d.appendChild(z)}}catch(A){null!=
DEXT5UPLOAD&&void 0!=DEXT5UPLOAD&&null!=g&&void 0!=g&&null!=g.contentWindow&&void 0!=g.contentWindow||alert("Error occurred load Frame")}};g.addEventListener?g.addEventListener("load",c,!1):g.attachEvent&&g.attachEvent("onload",c);c=DEXT5UPLOAD.util.getIframeDocument(g);d='<!DOCTYPE html><html lang="ko">';d+="<head>";d+="<title>Dext5 Upload</title>";e=DEXT5UPLOAD.ReleaseVer;"1"==b.cacheProtectMode&&(e=(new Date).getTime());if(DEXT5UPLOAD.isRelease){d+='<link rel="stylesheet" type="text/css" href="'+
b.webPath.css+"dext5upload.min.css?ver="+e+'" />';d+='<link rel="stylesheet" type="text/css" href="'+b.webPath.css+"dext5upload.context.min.css?ver="+e+'" />';DEXT5UPLOAD.browser.isCustomDomain(document)&&(d+='<script type="text/javascript"> document.domain = "'+document.domain+'"; \x3c/script>');d+='<script type="text/javascript" src="'+b.webPath.js+"dext5upload.xhr.js?ver="+e+'">\x3c/script>';1>b.imageQuality.quality&&0==DEXT5UPLOAD.browser.imageProcessWorkerSupported&&(d+='<script type="text/javascript" src="'+
b.webPath.jsDev+"dext5upload.image.exif.js?ver="+e+'">\x3c/script>');d+='<script type="text/javascript" src="'+b.webPath.js+"dext5upload.core.js?ver="+e+'">\x3c/script>';d+='<script type="text/javascript" src="'+b.webPath.js+"json2.min.js?ver="+e+'">\x3c/script>';if("1"==b.security.fileIntegrity||"1"==b.security.fileEncrypt)d+='<script type="text/javascript" src="'+b.webPath.js+"dext5upload.fdi.aes.js?ver="+e+'">\x3c/script>';"1"==b.security.fileIntegrity&&(d+='<script type="text/javascript" src="'+
b.webPath.js+"hmac-sha256.js?ver="+e+'">\x3c/script>');"1"==b.security.fileEncrypt&&(d+='<script type="text/javascript" src="'+b.webPath.js+"aes.js?ver="+e+'">\x3c/script>');d+='<script type="text/javascript" src="'+b.webPath.lang+b.lang+".js?ver="+e+'">\x3c/script>';"html4"==b.userRunTimeMode&&"0"==b.uploadMethodHtml4&&(d+='<script type="text/javascript" src="'+b.webPath.js+"swfupload/swfupload.min.js?ver="+e+'">\x3c/script>',d+='<script type="text/javascript" src="'+b.webPath.js+"dext5upload.swf.handlers.min.js?ver="+
e+'">\x3c/script>')}else{d+='<link rel="stylesheet" type="text/css" href="'+b.webPath.cssDev+"dext5upload.css?ver="+e+'" />';d+='<link rel="stylesheet" type="text/css" href="'+b.webPath.cssDev+"dext5upload.context.css?ver="+e+'" />';DEXT5UPLOAD.browser.isCustomDomain(document)&&(d+='<script type="text/javascript"> document.domain = "'+document.domain+'"; \x3c/script>');d+='<script type="text/javascript" src="'+b.webPath.jsDev+"dext5upload.xhr.js?ver="+e+'">\x3c/script>';d+='<script type="text/javascript" src="'+
b.webPath.jsDev+"dext5upload.src.js?ver="+e+'">\x3c/script>';d+='<script type="text/javascript" src="'+b.webPath.jsDev+"dext5upload.api.js?ver="+e+'">\x3c/script>';d+='<script type="text/javascript" src="'+b.webPath.jsDev+"dext5upload.control.js?ver="+e+'">\x3c/script>';d+='<script type="text/javascript" src="'+b.webPath.jsDev+"dext5upload.base64.js?ver="+e+'">\x3c/script>';d+='<script type="text/javascript" src="'+b.webPath.jsDev+"dext5pl.js?ver="+e+'">\x3c/script>';d+='<script type="text/javascript" src="'+
b.webPath.jsDev+"dext5upload.context.js?ver="+e+'">\x3c/script>';d+='<script type="text/javascript" src="'+b.webPath.jsDev+"json2.min.js?ver="+e+'">\x3c/script>';d+='<script type="text/javascript" src="'+b.webPath.jsDev+"dext5upload.detector.js?ver="+e+'">\x3c/script>';1>b.imageQuality.quality&&0==DEXT5UPLOAD.browser.imageProcessWorkerSupported&&(d+='<script type="text/javascript" src="'+b.webPath.jsDev+"dext5upload.image.exif.js?ver="+e+'">\x3c/script>');if("1"==b.security.fileIntegrity||"1"==b.security.fileEncrypt)d+=
'<script type="text/javascript" src="'+b.webPath.jsDev+"dext5upload.fdi.aes.js?ver="+e+'">\x3c/script>';"1"==b.security.fileIntegrity&&(d+='<script type="text/javascript" src="'+b.webPath.jsDev+"hmac-sha256.js?ver="+e+'">\x3c/script>');"1"==b.security.fileEncrypt&&(d+='<script type="text/javascript" src="'+b.webPath.jsDev+"aes.js?ver="+e+'">\x3c/script>');d+='<script type="text/javascript" src="'+b.webPath.langDev+b.lang+".js?ver="+e+'">\x3c/script>';"html4"==b.userRunTimeMode&&"0"==b.uploadMethodHtml4&&
(d+='<script type="text/javascript" src="'+b.webPath.jsDev+"swfupload/swfupload.js?ver="+e+'">\x3c/script>',d+='<script type="text/javascript" src="'+b.webPath.jsDev+"dext5upload.swf.handlers.js?ver="+e+'">\x3c/script>')}d+="</head>";d+='<body oncontextmenu="return false">';d+="</body>";d+="</html>";c.open("text/html","replace");c.write(d);c.close();return g}
function GetUserRunTimeUpload(b,c){b=b.toLowerCase();var a="";"html5plus"==b?a=1==DEXT5UPLOAD.browser.HTML5PlusSupported&&"1"==c?"html5plus":1==DEXT5UPLOAD.browser.HTML5Supported?"html5":"html4":""==b||"html5"==b?a=1==DEXT5UPLOAD.browser.HTML5Supported?"html5":"html4":"html4"==b?a="html4":"ieplugin"==b?a=1==DEXT5UPLOAD.browser.ie&&12>DEXT5UPLOAD.browser.ieVersion?"ieplugin":1==DEXT5UPLOAD.browser.HTML5PlusSupported&&"1"==c?"html5plus":1==DEXT5UPLOAD.browser.HTML5Supported?"html5":"html4":-1<b.indexOf("ieplugin")&&
8<b.length?(a=DEXT5UPLOAD.util.parseIntOr0(b),a=1==DEXT5UPLOAD.browser.ie&&a>=DEXT5UPLOAD.browser.ieVersion?"ieplugin":1==DEXT5UPLOAD.browser.HTML5PlusSupported&&"1"==c?"html5plus":1==DEXT5UPLOAD.browser.HTML5Supported?"html5":"html4"):a=1==DEXT5UPLOAD.browser.HTML5PlusSupported&&"1"==c?"html5plus":1==DEXT5UPLOAD.browser.HTML5Supported?"html5":"html4";return a}
function gcRequest_postMessage(b){if("html4"==b.userRunTimeMode&&"1"==b.uploadMethodHtml4&&b.isCrossDomain){var c=document.createElement("div"),a=DEXT5UPLOAD.util.getDefaultIframeSrc();c.innerHTML='<iframe name="initCheckframe" id="initCheckframe" style="display:none;" src="'+a+'"></iframe>';c.style.display="none";document.body.appendChild(c);DEXT5UPLOAD.util.postFormData(document,b.handlerUrl,"initCheckframe",[["dext5CMD","gcRequest"]]);document.body.removeChild(c)}else DEXT5UPLOAD.ajax.postData(b.handlerUrl,
"dext5CMD=gcRequest",function(){})};
