/*
 Copyright (c) 2013, Raonwiz Technology Inc. All rights reserved.
*/
window.DEXT5||(window.DEXT5=function(){return{isRelease:!0,isPopUpCssLoaded:!1,version:"DEXT5 Editor",ReleaseVer:"3.5.1123682.0942.01",ServerReleaseVer:"",cabVersion:"5,0,0,5",rootPath:function(){var b=window.DEXT5_ROOTPATH||"";if(!b)for(var c=document.getElementsByTagName("script"),a=c.length,e=null,h=0;h<a;h++){var e=c[h],g=e.src.match(/(^|.*[\\\/])dext5editor.js(?:\?.*)?$/i);"samsung.net"==document.domain&&(g=e.src.match(/(^|.*[\\\/])helloeditor.js(?:\?.*)?$/i));if(g){b=g[1];break}}-1==b.indexOf(":/")&&
(b=0===b.indexOf("/")?location.href.match(/^.*?:\/\/[^\/]*/)[0]+b:location.href.match(/^[^\?]*\/(?:)/)[0]+b);b=b.substring(0,b.length-1);b=b.substring(0,b.lastIndexOf("/"))+"/";if(!b)throw"DEXT5 Editor installation path could not be automatically detected.";return b}(),getUrl:function(b){-1==b.indexOf(":/")&&0!==b.indexOf("/")&&(b=this.rootPath+b);this.ReleaseVer&&"/"!=b.charAt(b.length-1)&&!/[&?]ver=/.test(b)&&(b+=(0<=b.indexOf("?")?"&":"?")+"ver="+this.ReleaseVer);return b},DEXTMULTIPLE:{},DEXTHOLDER:{},
DEXTMULTIPLEID:[],ShowTextChangeAlert:!0}}(),DEXT5.brower||(DEXT5.browser=function(){var b=navigator.userAgent.toLowerCase(),c=window.opera,c={ie:-1<b.search("trident")||-1<b.search("msie")||-1<b.search("edge/12")||-1<b.search("edge/13")?!0:!1,opera:!!c&&c.version,webkit:-1<b.indexOf(" applewebkit/"),mac:-1<b.indexOf("macintosh"),quirks:"BackCompat"==document.compatMode,mobile:-1<b.indexOf("mobile"),iOS:/(ipad|iphone|ipod)/.test(b),isCustomDomain:function(){if(!this.ie)return!1;var a=document.domain,
b=window.location.hostname;return a!=b&&a!="["+b+"]"},isHttps:"https:"==location.protocol};c.gecko="Gecko"==navigator.product&&!c.webkit&&!c.opera;c.ie&&(c.gecko=!1);c.webkit&&(-1<b.indexOf("chrome")?(c.chrome=!0,-1<b.indexOf("opr")&&(c.opera=!0,c.chrome=!1)):c.safari=!0);var a;c.ieVersion=0;c.ie&&(c.quirks||!document.documentMode?-1<b.indexOf("msie")?a=parseFloat(b.match(/msie (\d+)/)[1]):-1<b.indexOf("trident")?a=parseFloat(b.match(/rv:([\d\.]+)/)[1]):-1<b.indexOf("edge/12")||-1<b.indexOf("edge/13")?
(a=12,c.chrome=!1):a=7:a=document.documentMode,c.ieVersion=a,c.ie12=12==a,c.ie11=11==a,c.ie10=10==a,c.ie9=9==a,c.ie8=8==a,c.ie7=7==a,c.ie6=7>a||c.quirks,-1<b.indexOf("trident")?c.trident=parseFloat(b.match(/ trident\/(\d+)/)[1]):c.trident="");c.gecko&&(a=b.match(/rv:([\d\.]+)/))&&(a=a[1].split("."),a=1E4*a[0]+100*(a[1]||0)+1*(a[2]||0));c.webkit&&(a=parseFloat(b.match(/ applewebkit\/(\d+)/)[1]));return c}()),DEXT5.UserAgent||(DEXT5.UserAgent=function(){var b=window&&window.navigator&&window.navigator.userAgent?
window.navigator.userAgent:"",c={extend:function(a,b){for(var c in b)-1!=="browser cpu device engine os".indexOf(c)&&0===b[c].length%2&&(a[c]=b[c].concat(a[c]));return a},has:function(a,b){return"string"===typeof a?-1!==b.toLowerCase().indexOf(a.toLowerCase()):!1},lowerize:function(a){return a.toLowerCase()},major:function(a){return"string"===typeof a?a.split(".")[0]:void 0}},a=function(){for(var a,c=0,d,e,h,g,q,r,y=arguments;c<y.length&&!q;){var A=y[c],u=y[c+1];if("undefined"===typeof a)for(h in a=
{},u)g=u[h],"object"===typeof g?a[g[0]]=void 0:a[g]=void 0;for(d=e=0;d<A.length&&!q;)if(q=A[d++].exec(b))for(h=0;h<u.length;h++)r=q[++e],g=u[h],"object"===typeof g&&0<g.length?2==g.length?a[g[0]]="function"==typeof g[1]?g[1].call(this,r):g[1]:3==g.length?a[g[0]]="function"!==typeof g[1]||g[1].exec&&g[1].test?r?r.replace(g[1],g[2]):void 0:r?g[1].call(this,r,g[2]):void 0:4==g.length&&(a[g[0]]=r?g[3].call(this,r.replace(g[1],g[2])):void 0):a[g]=r?r:void 0;c+=2}return a},e=function(a,b){for(var d in b)if("object"===
typeof b[d]&&0<b[d].length)for(var e=0;e<b[d].length;e++){if(c.has(b[d][e],a))return"?"===d?void 0:d}else if(c.has(b[d],a))return"?"===d?void 0:d;return a},h={ME:"4.90","NT 3.11":"NT3.51","NT 4.0":"NT4.0",2E3:"NT 5.0",XP:["NT 5.1","NT 5.2"],Vista:"NT 6.0",7:"NT 6.1",8:"NT 6.2","8.1":"NT 6.3",10:["NT 6.4","NT 10.0"],RT:"ARM"},g=[[/\((ipad|playbook);[\w\s\);-]+(rim|apple)/i],["model","vendor",["type","tablet"]],[/applecoremedia\/[\w\.]+ \((ipad)/],["model",["vendor","Apple"],["type","tablet"]],[/(apple\s{0,1}tv)/i],
[["model","Apple TV"],["vendor","Apple"]],[/(archos)\s(gamepad2?)/i,/(hp).+(touchpad)/i,/(kindle)\/([\w\.]+)/i,/\s(nook)[\w\s]+build\/(\w+)/i,/(dell)\s(strea[kpr\s\d]*[\dko])/i],["vendor","model",["type","tablet"]],[/(kf[A-z]+)\sbuild\/[\w\.]+.*silk\//i],["model",["vendor","Amazon"],["type","tablet"]],[/(sd|kf)[0349hijorstuw]+\sbuild\/[\w\.]+.*silk\//i],[["model",e,{"Fire Phone":["SD","KF"]}],["vendor","Amazon"],["type","mobile"]],[/\((ip[honed|\s\w*]+);.+(apple)/i],["model","vendor",["type","mobile"]],
[/\((ip[honed|\s\w*]+);/i],["model",["vendor","Apple"],["type","mobile"]],[/(blackberry)[\s-]?(\w+)/i,/(blackberry|benq|palm(?=\-)|sonyericsson|acer|asus|dell|huawei|meizu|motorola|polytron)[\s_-]?([\w-]+)*/i,/(hp)\s([\w\s]+\w)/i,/(asus)-?(\w+)/i],["vendor","model",["type","mobile"]],[/\(bb10;\s(\w+)/i],["model",["vendor","BlackBerry"],["type","mobile"]],[/android.+(transfo[prime\s]{4,10}\s\w+|eeepc|slider\s\w+|nexus 7)/i],["model",["vendor","Asus"],["type","tablet"]],[/(sony)\s(tablet\s[ps])\sbuild\//i,
/(sony)?(?:sgp.+)\sbuild\//i],[["vendor","Sony"],["model","Xperia Tablet"],["type","tablet"]],[/(?:sony)?(?:(?:(?:c|d)\d{4})|(?:so[-l].+))\sbuild\//i],[["vendor","Sony"],["model","Xperia Phone"],["type","mobile"]],[/\s(ouya)\s/i,/(nintendo)\s([wids3u]+)/i],["vendor","model",["type","console"]],[/android.+;\s(shield)\sbuild/i],["model",["vendor","Nvidia"],["type","console"]],[/(playstation\s[3portablevi]+)/i],["model",["vendor","Sony"],["type","console"]],[/(sprint\s(\w+))/i],[["vendor",e,{HTC:"APA",
Sprint:"Sprint"}],["model",e,{"Evo Shift 4G":"7373KT"}],["type","mobile"]],[/(lenovo)\s?(S(?:5000|6000)+(?:[-][\w+]))/i],["vendor","model",["type","tablet"]],[/(htc)[;_\s-]+([\w\s]+(?=\))|\w+)*/i,/(zte)-(\w+)*/i,/(alcatel|geeksphone|huawei|lenovo|nexian|panasonic|(?=;\s)sony)[_\s-]?([\w-]+)*/i],["vendor",["model",/_/g," "],["type","mobile"]],[/(nexus\s9)/i],["model",["vendor","HTC"],["type","tablet"]],[/[\s\(;](xbox(?:\sone)?)[\s\);]/i],["model",["vendor","Microsoft"],["type","console"]],[/(kin\.[onetw]{3})/i],
[["model",/\./g," "],["vendor","Microsoft"],["type","mobile"]],[/\s(milestone|droid(?:[2-4x]|\s(?:bionic|x2|pro|razr))?(:?\s4g)?)[\w\s]+build\//i,/mot[\s-]?(\w+)*/i,/(XT\d{3,4}) build\//i],["model",["vendor","Motorola"],["type","mobile"]],[/android.+\s(mz60\d|xoom[\s2]{0,2})\sbuild\//i],["model",["vendor","Motorola"],["type","tablet"]],[/android.+((sch-i[89]0\d|shw-m380s|gt-p\d{4}|gt-n8000|sgh-t8[56]9|nexus 10))/i,/((SM-T\w+))/i],[["vendor","Samsung"],"model",["type","tablet"]],[/((s[cgp]h-\w+|gt-\w+|galaxy\snexus|sm-n900))/i,
/(sam[sung]*)[\s-]*(\w+-?[\w-]*)*/i,/sec-((sgh\w+))/i],[["vendor","Samsung"],"model",["type","mobile"]],[/(samsung);smarttv/i],["vendor","model",["type","smarttv"]],[/\(dtv[\);].+(aquos)/i],["model",["vendor","Sharp"],["type","smarttv"]],[/sie-(\w+)*/i],["model",["vendor","Siemens"],["type","mobile"]],[/(maemo|nokia).*(n900|lumia\s\d+)/i,/(nokia)[\s_-]?([\w-]+)*/i],[["vendor","Nokia"],"model",["type","mobile"]],[/android\s3\.[\s\w;-]{10}(a\d{3})/i],["model",["vendor","Acer"],["type","tablet"]],[/android\s3\.[\s\w;-]{10}(lg?)-([06cv9]{3,4})/i],
[["vendor","LG"],"model",["type","tablet"]],[/(lg) netcast\.tv/i],["vendor","model",["type","smarttv"]],[/(nexus\s[45])/i,/lg[e;\s\/-]+(\w+)*/i],["model",["vendor","LG"],["type","mobile"]],[/android.+(ideatab[a-z0-9\-\s]+)/i],["model",["vendor","Lenovo"],["type","tablet"]],[/linux;.+((jolla));/i],["vendor","model",["type","mobile"]],[/((pebble))app\/[\d\.]+\s/i],["vendor","model",["type","wearable"]],[/android.+;\s(glass)\s\d/i],["model",["vendor","Google"],["type","wearable"]],[/android.+(\w+)\s+build\/hm\1/i,
/android.+(hm[\s\-_]*note?[\s_]*(?:\d\w)?)\s+build/i,/android.+(mi[\s\-_]*(?:one|one[\s_]plus)?[\s_]*(?:\d\w)?)\s+build/i],[["model",/_/g," "],["vendor","Xiaomi"],["type","mobile"]],[/(mobile|tablet);.+rv\:.+gecko\//i],[["type",c.lowerize],"vendor","model"]],h=[[/microsoft\s(windows)\s(vista|xp)/i],["name","version"],[/(windows)\snt\s6\.2;\s(arm)/i,/(windows\sphone(?:\sos)*|windows\smobile|windows)[\s\/]?([ntce\d\.\s]+\w)/i],["name",["version",e,h]],[/(win(?=3|9|n)|win\s9x\s)([nt\d\.]+)/i],[["name",
"Windows"],["version",e,h]],[/\((bb)(10);/i],[["name","BlackBerry"],"version"],[/(blackberry)\w*\/?([\w\.]+)*/i,/(tizen)[\/\s]([\w\.]+)/i,/(android|webos|palm\sos|qnx|bada|rim\stablet\sos|meego|contiki)[\/\s-]?([\w\.]+)*/i,/linux;.+(sailfish);/i],["name","version"],[/(symbian\s?os|symbos|s60(?=;))[\/\s-]?([\w\.]+)*/i],[["name","Symbian"],"version"],[/\((series40);/i],["name"],[/mozilla.+\(mobile;.+gecko.+firefox/i],[["name","Firefox OS"],"version"],[/(nintendo|playstation)\s([wids3portablevu]+)/i,
/(mint)[\/\s\(]?(\w+)*/i,/(mageia|vectorlinux)[;\s]/i,/(joli|[kxln]?ubuntu|debian|[open]*suse|gentoo|arch|slackware|fedora|mandriva|centos|pclinuxos|redhat|zenwalk|linpus)[\/\s-]?([\w\.-]+)*/i,/(hurd|linux)\s?([\w\.]+)*/i,/(gnu)\s?([\w\.]+)*/i],["name","version"],[/(cros)\s[\w]+\s([\w\.]+\w)/i],[["name","Chromium OS"],"version"],[/(sunos)\s?([\w\.]+\d)*/i],[["name","Solaris"],"version"],[/\s([frentopc-]{0,4}bsd|dragonfly)\s?([\w\.]+)*/i],["name","version"],[/(ip[honead]+)(?:.*os\s*([\w]+)*\slike\smac|;\sopera)/i],
[["name","iOS"],["version",/_/g,"."]],[/(mac\sos\sx)\s?([\w\s\.]+\w)*/i,/(macintosh|mac(?=_powerpc)\s)/i],[["name","Mac OS"],["version",/_/g,"."]],[/((?:open)?solaris)[\/\s-]?([\w\.]+)*/i,/(haiku)\s(\w+)/i,/(aix)\s((\d)(?=\.|\)|\s)[\w\.]*)*/i,/(plan\s9|minix|beos|os\/2|amigaos|morphos|risc\sos|openvms)/i,/(unix)\s?([\w\.]+)*/i],["name","version"]],e=a.apply(this,[[/(opera\smini)\/([\w\.-]+)/i,/(opera\s[mobiletab]+).+version\/([\w\.-]+)/i,/(opera).+version\/([\w\.]+)/i,/(opera)[\/\s]+([\w\.]+)/i],
["name","version"],[/\s(opr)\/([\w\.]+)/i],[["name","Opera"],"version"],[/(kindle)\/([\w\.]+)/i,/(lunascape|maxthon|netfront|jasmine|blazer)[\/\s]?([\w\.]+)*/i,/(avant\s|iemobile|slim|baidu)(?:browser)?[\/\s]?([\w\.]*)/i,/(?:ms|\()(ie)\s([\w\.]+)/i,/(rekonq)\/([\w\.]+)*/i,/(chromium|flock|rockmelt|midori|epiphany|silk|skyfire|ovibrowser|bolt|iron|vivaldi)\/([\w\.-]+)/i],["name","version"],[/(trident).+rv[:\s]([\w\.]+).+like\sgecko/i],[["name","IE"],"version"],[/(edge)\/((\d+)?[\w\.]+)/i],["name",
"version"],[/(yabrowser)\/([\w\.]+)/i],[["name","Yandex"],"version"],[/(comodo_dragon)\/([\w\.]+)/i],[["name",/_/g," "],"version"],[/(chrome|omniweb|arora|[tizenoka]{5}\s?browser)\/v?([\w\.]+)/i,/(uc\s?browser|qqbrowser)[\/\s]?([\w\.]+)/i],["name","version"],[/(dolfin)\/([\w\.]+)/i],[["name","Dolphin"],"version"],[/((?:android.+)crmo|crios)\/([\w\.]+)/i],[["name","Chrome"],"version"],[/XiaoMi\/MiuiBrowser\/([\w\.]+)/i],["version",["name","MIUI Browser"]],[/android.+version\/([\w\.]+)\s+(?:mobile\s?safari|safari)/i],
["version",["name","Android Browser"]],[/FBAV\/([\w\.]+);/i],["version",["name","Facebook"]],[/version\/([\w\.]+).+?mobile\/\w+\s(safari)/i],["version",["name","Mobile Safari"]],[/version\/([\w\.]+).+?(mobile\s?safari|safari)/i],["version","name"],[/webkit.+?(mobile\s?safari|safari)(\/[\w\.]+)/i],["name",["version",e,{"1.0":"/8","1.2":"/1","1.3":"/3","2.0":"/412","2.0.2":"/416","2.0.3":"/417","2.0.4":"/419","?":"/"}]],[/(konqueror)\/([\w\.]+)/i,/(webkit|khtml)\/([\w\.]+)/i],["name","version"],[/(navigator|netscape)\/([\w\.-]+)/i],
[["name","Netscape"],"version"],[/(swiftfox)/i,/(icedragon|iceweasel|camino|chimera|fennec|maemo\sbrowser|minimo|conkeror)[\/\s]?([\w\.\+]+)/i,/(firefox|seamonkey|k-meleon|icecat|iceape|firebird|phoenix)\/([\w\.-]+)/i,/(mozilla)\/([\w\.]+).+rv\:.+gecko\/\d+/i,/(polaris|lynx|dillo|icab|doris|amaya|w3m|netsurf)[\/\s]?([\w\.]+)/i,/(links)\s\(([\w\.]+)/i,/(gobrowser)\/?([\w\.]+)*/i,/(ice\s?browser)\/v?([\w\._]+)/i,/(mosaic)[\/\s]([\w\.]+)/i],["name","version"]]);e.major=c.major(e.version);h=a.apply(this,
h);if(a=a.apply(this,g))void 0==a.model&&(a.model=""),void 0==a.type&&(a.type=""),void 0==a.vendor&&(a.vendor="");return{browser:e,os:h,device:a}}()));
DEXT5.config={Width:"",Height:"",SkinName:"",InitXml:"",InitServerXml:"",ToSavePathURL:"",ToSaveFilePathURL:"",ServerDomain:"",HandlerUrl:"",InitVisible:!0,DefaultMessage:"",FirstLoadType:"",FirstLoadMessage:"",FileFieldID:"",EditorHolder:"",zTopMenu:"",zToolBar:"",zTopStatusBar:"",zStatusBar:"",zXssUse:"",zXssRemoveTags:"",zXssRemoveEvents:"",Mode:"",zIndex:"",NextTabElementId:"",IgnoreSameEditorName:"0",ChangeMultiValueMode:"",EditorBorder:"",InitLang:"",Lang:"",IconName:"icon",CustomCode:"",EnterTag:"",
userFontFamily:"",userFontSize:"",UserFieldID:"",UserFieldValue:"",LicenseKey:"",mimeCharset:"",mimeConentEncodingType:"",mimeFileTypeFilter:"",mimeLocalOnly:"",mimeRemoveHeader:"",userOpenDlgTitle:"",userOpenDlgType:"",userOpenDlgInitDir:"",userImageDlgStyle:"",mimeBaseURL:"",focusInitObjId:"",focusInitEditorObjId:"",tabIndexObjId:"",pluginUse:"",imageEditorUse:"",mimeUse:"",officeLineFix:"",useLog:"0",RootPath:"",EditorTabDisable:"",FormListUrl:"",RunTimes:"",MouseEventCancel:!1,KeyEventCancel:!1,
SetValueObjId:"",LoadedEvent:"",scrollOverflow:"",DocType:"",DevelopLangage:"",UnitDelimiter:"",UnitAttributeDelimiter:"",EditorBodyEditable:"",SymbolUrl:"",AccessibilityValidationItems:"",ViewModeAutoHeight:"",ViewModeAutoWidth:"",ShowDialogPosition:"",StatusBarItem:"",StatusBarItemTitle:"",StatusBarInitMode:"",ImageBaseUrl:"",DragResize:"",DragResizeApplyBrowser:"",ReplaceOutsideImage:"",ReplaceOutsideImageExceptDomain:"",RemoveItem:"",RemoveContextItem:"",ManagerMode:"",EventList:"",TableLock:{Use:"",
LockName:"",ShowLockIconUserMode:"",TableLockMode:""},FontFamilyList:"",FontSizeList:"",LineHeightList:"",FormattingList:"",FrameFullScreen:"",DialogWindow:null,AdminTableLock:{DefaultShowLockIconUserMode:"",DefaultLockName:"",CheckLockName:"",DefaultTableLockMode:""},UserTableLock:{Use:"",LockName:"",DefaultTableLockMode:"",DefaultShowLockIcon:""},RemoveComment:"",SaveFolderNameRule:"",SaveFileFolderNameRule:"",ToolBarGrouping:"",SetDefaultValueInEmptyTag:"",LoadErrorCustomMessage:"",PhotoEditorId:"",
ProductKey:"",LicenseKey:"",DirectEditHtmlUrl:"",UserHelpUrl:"",UseGZip:"0",StatusBarLoading:"",TopStatusBarLoading:"",HandlerUrlSaveForNotes:"",HasContainer:"",Security:{EncryptParam:""},TabSpace:"",AutoBodyFit:"",Ruler:{Use:"",InitPosition:"",ViewPointer:"",ViewGuideLine:"",ViewRuler:""},UseConfigTimeStamp:"1",UseHorizontalLine:"",Document:{DocTitle:""},ImgUploadContenttype:"",ImageCustomPropertyDelimiter:"",LineHeightMode:"",PrintMarginltrb:"",ApplyStyleEmptyTag:""};
DEXT5.ajax=function(){var b=function(){if(!DEXT5.browser.ie||"file:"!=location.protocol){try{return new XMLHttpRequest}catch(a){}try{return new ActiveXObject("Msxml2.XHLHTTP")}catch(b){}try{return new ActiveXObject("Microsoft.XMLHTTP")}catch(c){}}return null},c=function(a){return 4==a.readyState&&(200<=a.status&&300>a.status||304==a.status||0===a.status||1223==a.status)},a=function(a){return c(a)?a.responseText:null},e=function(a){if(c(a)){var b=a.responseXML;return b?b:a.responseText}return null},
h=function(a,c,d){var e=!!c,g=b();if(!g)return null;g.open("GET",a,e);e&&(g.onreadystatechange=function(){4==g.readyState&&(c(d(g)),g=null)});try{g.send(null)}catch(h){return null}setTimeout(function(){e||g.abort()},5E3);return e?"":d(g)},g=function(a,c,d,e){var g=!!d,h=b();if(!h)return null;h.open("POST",a,g);h.setRequestHeader("Content-Type","application/x-www-form-urlencoded;charset=UTF-8");g&&(h.onreadystatechange=function(){4==h.readyState&&(d(e(h,c)),h=null)});try{h.send(c)}catch(q){return null}setTimeout(function(){if(!g)try{h.abort()}catch(a){}},
5E3);return g?"":e(h)};return{load:function(b,c){return h(b,c,a)},loadXml:function(a,b){return h(a,b,e)},postData:function(a,c){var d;a:if(d=b()){try{d.open("POST",a,!1),d.setRequestHeader("Content-Type","application/x-www-form-urlencoded;charset=UTF-8"),d.send(c)}catch(e){d=null;break a}d=d.responseText}else d=null;return d},postDataCallback:function(b,c,d){return g(b,c,d,a)},postFileData:function(a,c){var d;a:if(d=b()){try{d.open("POST",a,!1);var e="--------------------"+(new Date).getTime();d.setRequestHeader("Content-Type",
"multipart/form-data; boundary="+e);for(var e="--"+e,g="",h=c.split("&"),q=h.length,r=null,y="",A="",u=0;u<q;u++)r=h[u].split("="),"imagedata"==r[0]?y=r[1]:(g+=e+"\r\n",g+='Content-Disposition: form-data; name="'+r[0]+'"\r\n\r\n',g+=r[1]+"\r\n");for(var h=null,q="",H=window.atob(y),I=H.length,h=new Uint8Array(new ArrayBuffer(I)),u=0;u<I;u++)h[u]=H.charCodeAt(u),q+=String.fromCharCode(h[u]);String.fromCharCode.apply([],new Uint8Array(h));new Uint8Array(h);A=q;g+=e+"\r\n";g+='Content-Disposition: form-data; name="Filedata"; filename="'+
(new Date).getTime()+'"\r\n';g+="Content-Type: image/png\r\n";g+="\r\n";g+=A+"\r\n";d.send(g+(e+"--\r\n"))}catch(P){d=null;break a}d=d.responseText}else d=null;return d}}}();
DEXT5.util={G_IMG_LIST:{},trim:function(b){return b.trim?b.trim():b.replace(/^[\s\xa0]+|[\s\xa0]+$/g,"")},setClass:function(b,c){b.className=c},getClass:function(b){return b.className},checkUrl:function(b){var c=!1;return c=(new RegExp(/(http|ftp|https|news):\/\/[\S-]+(\.[\S-]+)+([\S.,@?^=%&amp;:\/~+#-]*[\S@?^=%&amp;\/~+#-])?/)).test(b)},getDefaultIframeSrc:function(){var b="",b="document.open();"+(DEXT5.browser.isCustomDomain()?'document.domain="'+document.domain+'";':"")+" document.close();";return b=
DEXT5.browser.ie?"javascript:void(function(){"+encodeURIComponent(b)+"}())":""},makeIframe:function(){var b;try{b=document.createElement('<iframe frameborder="0" >')}catch(c){b=document.createElement("iframe")}b.style.margin="0px";b.style.padding="0px";b.frameBorder=0;b.style.overflow="auto";b.style.overflowX="hidden";b.style.backgroundColor="#ffffff";return b},addEvent:function(b,c,a,e){b.addEventListener?b.addEventListener(c,a,e):b.attachEvent&&b.attachEvent("on"+c,a)},removeEvent:function(b,c,
a,e){b.removeEventListener?b.removeEventListener(c,a,e):b.detachEvent&&b.detachEvent("on"+c,a)},stopEvent:function(b){"bubbles"in b?b.bubbles&&b.stopPropagation():b.cancelBubble=!0},cancelEvent:function(b){b.preventDefault?b.preventDefault():b.returnValue=!1},ajax:{xml_http_request:function(){var b;window.XMLHttpRequest?b=new XMLHttpRequest:window.ActiveXObject&&(b=new ActiveXObject("Microsoft.XMLHTTP"));return b}},url:{full_url:function(b){var c="";if(0==b.indexOf("http://")||0==b.indexOf("https://"))c=
b;else if(0==b.indexOf("/"))c=location.protocol+"//"+location.host+b;else var c=location.href,a=c.lastIndexOf("/"),c=c.substring(0,a+1),c=c+b;return c}},xml:{count:function(b,c){return b?b.getElementsByTagName(c).length:0},getNode:function(b,c){return null==b||void 0==b?null:this.getNodeIdx(b,c,0)},getNodeIdx:function(b,c,a){return b.getElementsByTagName(c)[a]},getNodeValue:function(b,c){return null==b||void 0==b?"":this.getNodeValueIdx(b,c,0)},getNodeValueIdx:function(b,c,a){b=this.getNodeIdx(b,
c,a);return this.getValue(b)},getValue:function(b){var c="",a="";if(void 0!=b)try{0<b.childNodes.length&&(a=c=b.firstChild.nodeValue);try{("product_key"==b.nodeName||"font"==b.nodeName||"encoding"==b.nodeName||"doctype"==b.nodeName)&&2<=b.childNodes.length&&(c=b.textContent?b.textContent:a)}catch(e){c=a}}catch(h){c="parsing error"}return c}},htmlToLowerCase:function(b){if("1"!=DEXTTOP.G_CURREDITOR._config.useGetHtmlToLowerCase||8<DEXTTOP.DEXT5.browser.ieVersion&&0==DEXTTOP.DEXT5.browser.quirks||11==
DEXTTOP.DEXT5.browser.ieVersion&&1==DEXTTOP.DEXT5.browser.quirks)return b;var c=RegExp("<[^>]+>","g");results=b.match(c);if(null==results)return b;var a=c=-1,e=0,h=results.length;for(i=0;i<h;i++){original=results[i];c=original.indexOf("'");a=original.indexOf('"');e=2;1<c*a&&(-1<original.indexOf('="')?(results[i]=results[i].replace(/\'/g,"dext5_1q"),e=2):-1<original.indexOf("='")&&(results[i]=results[i].replace(/\"/g,"dext5_2q"),e=1));stripquoted=1==e?results[i].replace(/ [^=]+= *\'[^\']*\'/g,""):
results[i].replace(/ [^=]+= *"[^"]*"/g,"");c=RegExp(" [^=]+=[^ >]+","g");if(unquoted=stripquoted.match(c))for(c=unquoted.length,j=0;j<c;j++)addquotes=1==e?unquoted[j].replace(/( [^=]+=)([^ >]+)/g,"$1'$2'"):unquoted[j].replace(/( [^=]+=)([^ >]+)/g,'$1"$2"'),results[i]=results[i].replace(unquoted[j],addquotes);results[i]=results[i].replace(/<\/?[^>|^ ]+/,function(a){return a.toLowerCase()});results[i]=1==e?results[i].replace(/ [^=|^ ]+=\'/g,function(a){return a.toLowerCase()}):results[i].replace(/ [^=|^ ]+="/g,
function(a){return a.toLowerCase()});results[i]=results[i].replace(/dext5_1q/g,"'");results[i]=results[i].replace(/dext5_2q/g,'"');b=b.replace(original,results[i])}return b},hexDigits:"0123456789abcdef".split(""),hex:function(b){return isNaN(b)?"00":this.hexDigits[(b-b%16)/16]+this.hexDigits[b%16]},rgb2hex:function(b){b=b.match(/^rgb\((\d+),\s*(\d+),\s*(\d+)\)$/);if(!(null==b||4>b.length))return"#"+this.hex(b[1])+this.hex(b[2])+this.hex(b[3])},dextSetAttribute:function(b,c,a,e){"string"==typeof a?
0<a.length&&(b.style[c]=a+e):"number"==typeof a&&(b.style[c]=a)},getRealBackgoundImagePath:function(b){return b=b.replace(/url\(\s*(["']?)\s*([^\)]*)\s*\1\s*\)/i,function(b,a,e){return e})},replaceForXSS:function(b,c,a,e){var h=!1;try{if(""!=a)for(var g=a.split(","),f=g.length,k=0;k<f;k++){var d=g[k],l=new RegExp("<"+d+"[^>]*>[\\s\\S]*?</"+d+">","gim");1==l.test(b)&&(h=!0,b=b.replace(l,""));var m=new RegExp("<"+d+"[^>]*>","gi");1==m.test(b)&&(h=!0,b=b.replace(m,""))}if(""!=e)for(var t=e.split(","),
q=t.length,k=0;k<q;k++){var r=t[k],y=new RegExp("(?:"+r+')\\s*=\\s*"[^"]*"\\s*',"gi"),A=new RegExp("(?:"+r+")\\s*=\\s*'[^']*'\\s*","gi");if(y.test(b)||A.test(b))h=!0,b=b.replace(y,""),b=b.replace(A,"")}if(""!=c)for(var u=c.split(","),H=u.length,k=0;k<H;k++){var I=new RegExp("<\\/"+u[k]+">","gi"),P=b.match(new RegExp("<"+u[k]+"[^>]*>","gi"));if(P){var h=!0,W=P.length;c="";for(a=0;a<W;a++)c=P[a].toLowerCase(),c=c.replace("<","&lt;"),c=c.replace(">","&gt;"),b=b.replace(P[a],c);b=b.replace(I,"&lt;/"+
u[k]+"&gt;")}}}catch(Da){}0==h&&(b="");return b},removeTags:function(b,c){if(""!=c)for(var a=c.split(","),e=null,h=a.length,g=0,f=0;f<h;f++)for(e=b.getElementsByTagName(a[f]),g=e.length,--g;0<=g;g--){var k=e[g];k.parentNode.removeChild(k)}},removeEvents:function(b,c,a){if(""!=c){b=c.split(",");c=a.length;for(var e=0,h=0;h<c;h++)for(var e=b.length,g=0;g<e;g++)a[h].removeAttribute(b[g])}},removeElement:function(b){for(;b.firstChild;)b.parentNode.insertBefore(b.firstChild,b);b.parentNode.removeChild(b)},
officeClean:function(b,c){if(""==b||void 0==b)return"";var a=null,e=[],a=!1;/([:| ])([-]{0,1}[0-9]+|[-]{0,1}[0-9]*[.]{1}[0-9]+)pt/gi.test(b)&&(a=!0);/([:| ])([:| ][-]{0,1}[0-9]+|[-]{0,1}[0-9]*[.]{1}[0-9]+)cm/gi.test(b)&&(a=!0);if(1==a){a=document.createElement("div");a.innerHTML=b;for(var e=a.getElementsByTagName("*"),h=e.length,g=0;g<h;g++){var f=e[g];if(f.style.width){var k=f.style.width.toLowerCase();-1<k.indexOf("pt")?(k=4*parseFloat(k)/3,0<k&&1>k&&(k=1),0>k&&(k=0),k=Math.round(k)+"px",f.style.width=
k):-1<k.indexOf("cm")&&(_cm=37.795275593333*parseFloat(k),0<_cm&&1>_cm&&(_cm=1),0>_cm&&(_cm=0),k=Math.round(_cm)+"px",f.style.width=k)}f.style.height&&(k=f.style.height.toLowerCase(),-1<k.indexOf("pt")?(k=4*parseFloat(k)/3,0<k&&1>k&&(k=1),0>k&&(k=0),k=Math.round(k)+"px",f.style.height=k):-1<k.indexOf("cm")&&(_cm=37.795275593333*parseFloat(k),0<_cm&&1>_cm&&(_cm=1),0>_cm&&(_cm=0),k=Math.round(_cm)+"px",f.style.height=k));k="";f.style.borderStyle&&(k=f.style.borderStyle);""!=f.style.borderTop&&(f.style.borderTop=
replacePtOrCmToPx(f.style.borderTop));""!=f.style.borderRight&&(f.style.borderRight=replacePtOrCmToPx(f.style.borderRight));""!=f.style.borderBottom&&(f.style.borderBottom=replacePtOrCmToPx(f.style.borderBottom));""!=f.style.borderLeft&&(f.style.borderLeft=replacePtOrCmToPx(f.style.borderLeft));""!=f.style.borderWidth&&(f.style.borderWidth=replacePtOrCmToPx(f.style.borderWidth));""!=k&&(f.style.borderStyle=k);try{if(-1<f.style.borderTop.indexOf("currentColor")){var d="",l="",m="",d=DEXT5.util.getStyle(f,
"borderTopColor"),l=DEXT5.util.getStyle(f,"borderTopStyle"),m=DEXT5.util.getStyle(f,"borderTopWidth");f.style.borderTop=l+" "+m+" "+d}-1<f.style.borderRight.indexOf("currentColor")&&(m=l=d="",d=DEXT5.util.getStyle(f,"borderRightColor"),l=DEXT5.util.getStyle(f,"borderRightStyle"),m=DEXT5.util.getStyle(f,"borderRightWidth"),f.style.borderRight=l+" "+m+" "+d);-1<f.style.borderBottom.indexOf("currentColor")&&(m=l=d="",d=DEXT5.util.getStyle(f,"borderBottomColor"),l=DEXT5.util.getStyle(f,"borderBottomStyle"),
m=DEXT5.util.getStyle(f,"borderBottomWidth"),f.style.borderBottom=l+" "+m+" "+d);-1<f.style.borderLeft.indexOf("currentColor")&&(m=l=d="",d=DEXT5.util.getStyle(f,"borderLeftColor"),l=DEXT5.util.getStyle(f,"borderLeftStyle"),m=DEXT5.util.getStyle(f,"borderLeftWidth"),f.style.borderLeft=l+" "+m+" "+d)}catch(t){}}b=a.innerHTML}b=b.replace(/\.0px/g,"px");b=b.replace(/\t/g,"");b=DEXT5.util.removeOfficeDummyTag(b,"\x3c!--[if supportFields]>","<![endif]--\x3e");a=RegExp("<o:p></o:p>","gi");b=b.replace(a,
"");a=RegExp("<o:p>\\s+</o:p>","gi");b=b.replace(a,"");a=RegExp("<o:p ([^>]+)></o:p>","gi");b=b.replace(a,"");a=RegExp("<o:p ([^>]+)>\\s+</o:p>","gi");b=b.replace(a,"");b=b.replace(/\slang=[\"]?en-us[\"]?/gi,"");b=b.replace(/\sclass=[\"]?(mso)\w+[\"]?/gi,"");a=RegExp('mso-[^:]+:[^;">]+;',"gi");b=b.replace(a,"");a=RegExp('mso-[^:]+:[^;">]+("|\')',"gi");b=b.replace(a,"$1");b=DEXT5.util.replaceAll(b,"hairline","dotted");for(d=0;5>d;d++){e=["o:p","span","font"];m=e.length;for(l=0;l<m;l++)a=new RegExp("<"+
e[l]+"[^>]*></"+e[l]+">","gi"),b=b.replace(a,""),a=new RegExp("<"+e[l]+"[^>]*>&nbsp;</"+e[l]+">","gi"),b=b.replace(a,"&nbsp;"),"span"!=e[l]&&(a=new RegExp("<"+e[l]+"[^>]*> </"+e[l]+">","gi"),b=b.replace(a,"&nbsp;"));e=["o","v","w","m","x"];m=e.length;for(l=0;l<m;l++)0==l&&(b=b.replace(/<o:p/gi,"<dexto:p")),a=new RegExp("<"+e[l]+":[^/>]+/>","gi"),b=b.replace(a,""),a=new RegExp("<"+e[l]+":[^>]+>[^<]*</"+e[l]+":[^>]+>","gi"),b=b.replace(a,""),l==m-1&&(b=b.replace(/<dexto:p/gi,"<o:p"))}b=b.replace(/style=""/gi,
"");b=b.replace(/style=''/gi,"");b=b.replace(/\s>/gi,">");b=DEXTTOP.DEXT5.util.replaceOneSpaceToNbsp(b);b=b.replace(/<\/td>&nbsp;<\/tr>/g,"</td></tr>");b=b.replace(/<\/td>&nbsp;<\/td>/g,"</td></td>");b=b.replace(/<\/th>&nbsp;<\/tr>/g,"</th></tr>");b=b.replace(/<\/th>&nbsp;<\/th>/g,"</th></th>");if(DEXTTOP.DEXT5.browser.ie&&10>DEXTTOP.DEXT5.browser.ieVersion){l=b.length;a=m=!1;g=h=e="";if(-1==b.indexOf("<")&&-1==b.indexOf(">"))for(d=0;d<l;d++)e=b.charAt(d),h=b.charAt(d+1)," "!=e&&32!=e.charCodeAt(0)||
" "!=h&&32!=h.charCodeAt(0)||(e="&nbsp;"),g+=e;else for(d=0;d<l;d++)e=b.charAt(d),h=b.charAt(d+1),"<"==e?(m=!1,a="p"==h.toLowerCase()?!0:!1):">"==e&&1==a?m=!0:1!=m||" "!=e&&32!=e.charCodeAt(0)||" "!=h&&32!=h.charCodeAt(0)||(e="&nbsp;"),g+=e;b=g}0==c&&(b=DEXTTOP.DEXT5.util.removeLocalFileImage(b));return b},removeLocalFileImage:function(b){if(""==b||void 0==b)return"";b=b.replace(/file:\/\/\//gi,"dext_local_file_image");reg_exp=RegExp("<img[^>]+dext_local_file_image[^>]+>","gi");return b=b.replace(reg_exp,
"")},html2xhtml:function(b){if(""==b||void 0==b)return"";for(var c="area base br col embed frame hr img input link meta param".split(" "),a=c.length,e=null,h=RegExp(),g=0;g<a;g++)e=c[g],h=new RegExp("<"+e+" ([^>]*)>","gi"),b=b.replace(h,"<"+e+" $1 />"),h=new RegExp("<"+e+">","gi"),b=b.replace(h,"<"+e+" />");return b},emptyTagRemove:function(b){if(""==b||void 0==b)return"";try{if("1"==DEXTTOP.G_CURREDITOR._config.empty_tag_remove){var c=document.createElement("div");c.innerHTML=b;for(var a=c.getElementsByTagName("p"),
e=a.length,h,g,f="",k=[],d=["br","img","a","hr","table"],l=!1,m=0;m<e;m++)if(h=a[m],f="textContent"in h?h.textContent:h.innerText,""==f){g=h.innerHTML;for(var l=!1,t=d.length,q=0;q<t;q++)if(-1<g.toLowerCase().indexOf("<"+d[q])){l=!0;break}0==l&&k.push(h)}for(var r=k.length;0<r;)h=k.pop(),h.parentNode.removeChild(h);b=c.innerHTML}}catch(y){}return b},emptyTagRemoveCheckInContentTag:function(b,c){if(""==b||void 0==b)return"";try{if("1"==DEXTTOP.G_CURREDITOR._config.empty_tag_remove){var a=document.createElement("div");
a.innerHTML=b;for(var e=a.getElementsByTagName("p"),h=e.length,g,f,k="",d=[],l=!1,m=0;m<h;m++)if(g=e[m],k="textContent"in g?g.textContent:g.innerText,""==k){f=g.innerHTML;for(var l=!1,t=c.length,q=0;q<t;q++)if(-1<f.toLowerCase().indexOf("<"+c[q])){l=!0;break}0==l&&d.push(g)}for(var r=d.length;0<r;)g=d.pop(),a.removeChild(g);b=a.innerHTML}}catch(y){}return b},htmlRevision:function(b,c){if(""==b||void 0==b)return"";var a=null;"1"==DEXTTOP.G_CURREDITOR._config.removeComment&&(b=b.replace(/\x3c!--[\w\s\d@{}:.;,'"%!#_=&|?~()[*+\/\-\]]*--\x3e/gi,
""));DEXT5.browser.ie&&11>DEXT5.browser.ieVersion||c?(a=RegExp("><p><br></p></td>","gi"),b=b.replace(a,"><p>&nbsp;</p></td>")):(a=RegExp(">&nbsp;</td>","gi"),b=b.replace(a,"><p><br></p></td>"));for(var e=DEXTTOP.G_CURREDITOR._config.setDefaultValueInEmptyTag,h=e.length,g=0;g<h;g++){var f=e[g];DEXT5.browser.ie&&11>DEXT5.browser.ieVersion||c?(a=new RegExp("<"+f+"><br></"+f+">","gi"),b=b.replace(a,"<"+f+">&nbsp;</"+f+">"),a=new RegExp("<"+f+"><br/></"+f+">","gi"),b=b.replace(a,"<"+f+">&nbsp;</"+f+">"),
a=new RegExp("<"+f+"><br /></"+f+">","gi"),b=b.replace(a,"<"+f+">&nbsp;</"+f+">"),a=new RegExp("<"+f+"></"+f+">","gi"),b=b.replace(a,"<"+f+">&nbsp;</"+f+">"),a=new RegExp("<"+f+">\\s+</"+f+">","gi"),b=b.replace(a,"<"+f+">&nbsp;</"+f+">"),a=new RegExp("<"+f+" ([^>]+)><br></"+f+">","gi"),b=b.replace(a,"<"+f+" $1>&nbsp;</"+f+">"),a=new RegExp("<"+f+" ([^>]+)><br/></"+f+">","gi"),b=b.replace(a,"<"+f+" $1>&nbsp;</"+f+">"),a=new RegExp("<"+f+" ([^>]+)><br /></"+f+">","gi"),b=b.replace(a,"<"+f+" $1>&nbsp;</"+
f+">"),a=new RegExp("<"+f+" ([^>]+)></"+f+">","gi"),b=b.replace(a,"<"+f+" $1>&nbsp;</"+f+">"),a=new RegExp("<"+f+" ([^>]+)>\\s+</"+f+">","gi"),b=b.replace(a,"<"+f+" $1>&nbsp;</"+f+">")):DEXT5.browser.ie&&11==DEXT5.browser.ieVersion&&0==f.indexOf("h")?(a=new RegExp("<"+f+"></"+f+">","gi"),b=b.replace(a,"<"+f+">"+unescape("%u2060")+"</"+f+">"),a=new RegExp("<"+f+">&nbsp;</"+f+">","gi"),b=b.replace(a,"<"+f+">"+unescape("%u2060")+"</"+f+">"),a=new RegExp("<"+f+">\\s+</"+f+">","gi"),b=b.replace(a,"<"+
f+">"+unescape("%u2060")+"</"+f+">"),a=new RegExp("<"+f+" ([^>]+)></"+f+">","gi"),b=b.replace(a,"<"+f+" $1>"+unescape("%u2060")+"</"+f+">"),a=new RegExp("<"+f+" ([^>]+)>&nbsp;</"+f+">","gi"),b=b.replace(a,"<"+f+" $1>"+unescape("%u2060")+"</"+f+">"),a=new RegExp("<"+f+" ([^>]+)>\\s+</"+f+">","gi"),b=b.replace(a,"<"+f+" $1>"+unescape("%u2060")+"</"+f+">")):(a=new RegExp("<"+f+"></"+f+">","gi"),b=b.replace(a,"<"+f+"><br></"+f+">"),a=new RegExp("<"+f+">&nbsp;</"+f+">","gi"),b=b.replace(a,"<"+f+"><br></"+
f+">"),a=new RegExp("<"+f+">\\s+</"+f+">","gi"),b=b.replace(a,"<"+f+"><br></"+f+">"),a=new RegExp("<"+f+" ([^>]+)></"+f+">","gi"),b=b.replace(a,"<"+f+" $1><br></"+f+">"),a=new RegExp("<"+f+" ([^>]+)>&nbsp;</"+f+">","gi"),b=b.replace(a,"<"+f+" $1><br></"+f+">"),a=new RegExp("<"+f+" ([^>]+)>\\s+</"+f+">","gi"),b=b.replace(a,"<"+f+" $1><br></"+f+">"))}if(0==DEXTTOP.DEXT5.browser.ie&&(a=b.match(RegExp("<([^>]*)>","igm"))))for(e=a.length,h="",g=0;g<e;g++)h=a[g].toString(),h=h.replace(/\r?\n|\r/g,""),b=
b.replace(a[g],h);a=RegExp("<c:foreach","gi");b=b.replace(a,"<c:forEach");a=RegExp("</c:foreach","gi");return b=b.replace(a,"</c:forEach")},nbspRemove:function(b){if(""==b||void 0==b)return"";var c=null,c=RegExp("<p>&nbsp;</p>","gi");b=b.replace(c,"<p></p>");c=RegExp("<p ([^>]+)>&nbsp;</p>","gi");return b=b.replace(c,"<p $1></p>")},ImageSrcConvert:function(b,c,a){var e=document.createElement("div");e.innerHTML=b;b=e.getElementsByTagName("img");var h=b.length,g=null,f="",k="";a+="_dext5_base64_image_";
for(var d=0;d<h;d++)g=b[d],k=a+d,f=g.src,1==c?-1<f.indexOf("data:image")&&-1<f.indexOf("base64,")&&(this.G_IMG_LIST[k]=f,g.src=k):-1<f.indexOf(a)&&(g.src=this.G_IMG_LIST[k],this.G_IMG_LIST[k]="");return b=e.innerHTML},getUrlString:function(b){b=DEXT5.util.replaceAll(b," ","%20");b=DEXT5.util.replaceAll(b,"&nbsp;","%21");b=DEXT5.util.replaceAll(b,"!","%20");b=DEXT5.util.replaceAll(b,'"',"%22");b=DEXT5.util.replaceAll(b,"#","%23");b=DEXT5.util.replaceAll(b,"$","%24");b=DEXT5.util.replaceAll(b,"%","%25");
b=DEXT5.util.replaceAll(b,"&","%26");b=DEXT5.util.replaceAll(b,"'","%27");b=DEXT5.util.replaceAll(b,"+","%2B");b=DEXT5.util.replaceAll(b,"/","%2F");b=DEXT5.util.replaceAll(b,":","%3A");b=DEXT5.util.replaceAll(b,";","%3B");b=DEXT5.util.replaceAll(b,"<","%3C");b=DEXT5.util.replaceAll(b,"=","%3D");b=DEXT5.util.replaceAll(b,">","%3E");b=DEXT5.util.replaceAll(b,"?","%3F");return b=DEXT5.util.replaceAll(b,"@","%40")},replaceAll:function(b,c,a){for(var e=b.indexOf(c);-1!=e;)b=b.replace(c,a),e=b.indexOf(c);
return b},getSkinNames:function(){return"blue brown darkgray gold gray green orange pink purple red silver yellow".split(" ")},CustomSetting:function(b,c,a){switch(b){case "function":CustomSettingFunction(a);break;case "remove_item":return CustomRemoveItem(c)}},replaceOneSpaceToNbsp:function(b){var c=b,a,e="";try{for(var h="span font a b strong i em strike u sup sub".split(" "),g=h.length,f=0;f<g;f++)for(var k=0;k<g;k++){e=c;a=new RegExp("<"+h[f]+" *([^>?+])*>(\\s+)</"+h[k]+">","gi");reg_exp2=new RegExp("</"+
h[f]+">(\\s+)<"+h[k]+" *([^>?+])*>","gi");reg_exp3=new RegExp("<"+h[f]+" *([^>?+])*>(\\s+)<"+h[k]+">","gi");reg_exp4=new RegExp("</"+h[f]+">(\\s+)</"+h[k]+" *([^>?+])*>","gi");try{var d=c.match(a);if(d)for(var l=d.length,m=0;m<l;m++)var t=d[m],q=/>\s+</.exec(t),r=q[0].replace(RegExp("\\s\\s","gi"),"&nbsp;&nbsp;"),t=t.replace(q,r),c=c.replace(d[m],t);if(d=c.match(reg_exp2))for(l=d.length,m=0;m<l;m++)t=d[m],"b"==h[k]&&-1<match_string.toLowerCase().indexOf("<br")||(q=/>\s+</.exec(t),r=q[0].replace(RegExp("\\s\\s",
"gi"),"&nbsp;&nbsp;"),t=t.replace(q,r),c=c.replace(d[m],t));if(d=c.match(reg_exp3))for(l=d.length,m=0;m<l;m++)t=d[m],"b"==h[f]&&-1<match_string.toLowerCase().indexOf("<br")||(q=/>\s+</.exec(t),r=q[0].replace(RegExp("\\s\\s","gi"),"&nbsp;&nbsp;"),t=t.replace(q,r),c=c.replace(d[m],t));if(d=c.match(reg_exp4))for(l=d.length,m=0;m<l;m++)t=d[m],q=/>\s+</.exec(t),r=q[0].replace(RegExp("\\s\\s","gi"),"&nbsp;&nbsp;"),t=t.replace(q,r),c=c.replace(d[m],t)}catch(y){c=e}}for(f=0;f<g;f++)for(k=0;k<g;k++)e="","b"==
h[k]&&(e="[^r]"),a=new RegExp("/"+h[f]+">\\s<"+h[k],"gi"),c=c.replace(a,"/"+h[f]+">&nbsp;<"+h[k]),a=new RegExp("/"+h[f]+">\\s\\n<"+h[k]+e,"gi"),c=c.replace(a,"/"+h[f]+">&nbsp;<"+h[k]);return c}catch(A){return b}},parseIntOr0:function(b){b=parseInt(b,10);return isNaN(b)?0:b},getUserLang:function(b){b=b.toLowerCase();var c="ko-kr";if(-1<b.indexOf("ko"))c="ko-kr";else if(-1<b.indexOf("en"))c="en-us";else if(-1<b.indexOf("ja"))c="ja-jp";else if(-1<b.indexOf("zh-cn")||0==b.indexOf("cn"))c="zh-cn";else if(-1<
b.indexOf("zh-tw")||0==b.indexOf("tw"))c="zh-tw";return c},postFormData:function(b,c,a,e){void 0==e&&(e=[]);var h=b.createElement("form");h.method="post";h.action=c;h.target=a;c=e.length;for(a=0;a<c;a++){var g=b.createElement("input");g.type="hidden";g.name=e[a][0];g.value=e[a][1];h.appendChild(g)}b.body.appendChild(h);h.submit();b.body.removeChild(h)},base64_encode:function(b){var c="",a,e,h,g,f,k,d=0;for(b=DEXT5.util.utf8_decode(b);d<b.length;)a=b.charCodeAt(d++),e=b.charCodeAt(d++),h=b.charCodeAt(d++),
g=a>>2,a=(a&3)<<4|e>>4,f=(e&15)<<2|h>>6,k=h&63,isNaN(e)?f=k=64:isNaN(h)&&(k=64),c=c+"ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/=".charAt(g)+"ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/=".charAt(a)+"ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/=".charAt(f)+"ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/=".charAt(k);return c},base64_decode:function(b){var c="",a,e,h,g,f,k=0;for(b=b.replace(/[^A-Za-z0-9\+\/\=]/g,"");k<b.length;)a=
"ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/=".indexOf(b.charAt(k++)),e="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/=".indexOf(b.charAt(k++)),g="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/=".indexOf(b.charAt(k++)),f="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/=".indexOf(b.charAt(k++)),a=a<<2|e>>4,e=(e&15)<<4|g>>2,h=(g&3)<<6|f,c+=String.fromCharCode(a),64!=g&&(c+=String.fromCharCode(e)),64!=f&&(c+=String.fromCharCode(h));
return c=DEXT5.util.utf8_decode(c)},makeEncryptParam:function(b){b=DEXT5.util.base64_encode(b);b="R"+b;b=DEXT5.util.base64_encode(b);return b=b.replace(/[+]/g,"%2B")},utf8_decode:function(b){for(var c="",a=0,e=c1=c2=0;a<b.length;)e=b.charCodeAt(a),128>e?(c+=String.fromCharCode(e),a++):191<e&&224>e?(c2=b.charCodeAt(a+1),c+=String.fromCharCode((e&31)<<6|c2&63),a+=2):(c2=b.charCodeAt(a+1),c3=b.charCodeAt(a+2),c+=String.fromCharCode((e&15)<<12|(c2&63)<<6|c3&63),a+=3);return c},stringToXML:function(b){var c;
try{window.ActiveXObject?(c=new ActiveXObject("Microsoft.XMLDOM"),c.async="false",c.loadXML(b)):c=(new DOMParser).parseFromString(b,"text/xml")}catch(a){c=null}return c},removeOfficeDummyTag:function(b,c,a){var e=b;try{for(var h=b.indexOf(c),g=b.indexOf(a);-1<h&&-1<g;)var f=e.substring(0,h),k=e.substring(g+a.length),e=f+k,h=e.indexOf(c),g=e.indexOf(a)}catch(d){e=b}return e},getStyle:function(b,c){var a;b.currentStyle?a=b.currentStyle:_iframeWin.getComputedStyle&&(a=_iframeWin.getComputedStyle(b,""));
return a?a.getProperty?a.getProperty(c):a[c]:""}};
function DEXT_CONFIG(){""!=DEXT5.config.RootPath&&(DEXT5.rootPath=DEXT5.config.RootPath);this.defaultLineHeight=this.defaultFontFamily=this.defaultFontSize=this.lang=this.dext_path="";this.tabSequenceMode=this.accessibility="0";this.visibility=!0;this.status_bar=this.top_status_bar=this.tool_bar=this.top_menu="0";this.toSaveFilePathURL=this.toSavePathURL="dext5editordata";this.saveFileFolderNameRule=this.saveFolderNameRule="YYYY/MM";this.serverDomain="";this.saveFileNameRule="GUID";this.showDialogPosition=
"1";this.image_convert_height=this.image_convert_width=this.image_convert_format="";this.image_auto_fit="0";this.productKey="";this.imageEditorUse=this.plugInUse="0";this.fileFieldID=this.firstLoadMessage=this.firstLoadType=this.defaultMessage="";this.printPreview="0";this.basePrintFooter=this.basePrintHeader=this.printMarginltrb=this.printFooter=this.printHeader="";this.userCssUrl=this.useSelectionMark=this.sourceViewtype="0";this.nextTabElementId="";this.xhtml_value=this.empty_tag_remove=this.paste_image_base64=
"0";this.system_title="DEXT5";this.view_mode_auto_width=this.view_mode_auto_height="0";this.changeMultiValueMode="doctype";this.tableAutoAdjust="1";this.trustSites="";this.contextMenuDisable="0";this.userFieldValue=this.userFieldID=this.enterTag="";this.mimeCharset="utf-8";this.mimeConentEncodingType="3";this.mimeLocalOnly=this.mimeFileTypeFilter="1";this.mimeRemoveHeader="0";this.imgDefaultMarginBottom=this.imgDefaultMarginTop=this.imgDefaultMarginRight=this.imgDefaultMarginLeft=this.imgDefaultHeight=
this.imgDefaultWidth=this.mimeBaseURL=this.userImageDlgStyle=this.userOpenDlgInitDir=this.userOpenDlgType=this.userOpenDlgTitle="";this.officeLineFix="1";this.useLog="0";this.EditorTabDisable="";this.unitDelimiter="\f";this.unitAttributeDelimiter="\x0B";this.style={skinName:"blue",width:"100%",height:"600px",InitVisible:!0,isFontSizeUse:!0,defaultMinHeight:"300px",iconName:"icon"};this.webPath={image:DEXT5.rootPath+"images/editor/",page:DEXT5.rootPath+"pages/",js:DEXT5.rootPath+"js/",js_dev:DEXT5.rootPath+
"js_dev/",css:DEXT5.rootPath+"css/",css_dev:DEXT5.rootPath+"css_dev/",include:DEXT5.rootPath+"include/",config:DEXT5.rootPath+"config/",help:DEXT5.rootPath+"help/"};this.holderID="";this.config_url=DEXT5.rootPath+"config/dext_editor.xml";this.emoticon_url=DEXT5.rootPath+"config/dext_emoticon.xml";this.forms_url=DEXT5.rootPath+"config/dext_formlist.xml";this.post_url=DEXT5.rootPath+"handler/upload_handler.ashx";this.proxy_url=this.post_url_save_for_notes="";this.plugin_root=DEXT5.rootPath+"plugin/";
this.plugin_version=DEXT5.cabVersion;this.editor_url=DEXT5.isRelease?DEXT5.rootPath+"pages/editor_release.html?ver="+DEXT5.ReleaseVer:DEXT5.rootPath+"pages/editor.html?ver="+DEXT5.ReleaseVer;this.pages={find:"editor_find.html?ver="+DEXT5.ReleaseVer,replace:"editor_replace.html?ver="+DEXT5.ReleaseVer,image:"editor_image.html?ver="+DEXT5.ReleaseVer,horizontal_line:"editor_horizontal_line.html?ver="+DEXT5.ReleaseVer,bg_image:"dext_bg_image.html?ver="+DEXT5.ReleaseVer,doc_bg_img:"editor_doc_bg_img.html?ver="+
DEXT5.ReleaseVer,flash:"editor_flash.html?ver="+DEXT5.ReleaseVer,media:"editor_media.html?ver="+DEXT5.ReleaseVer,table:"editor_table.html?ver="+DEXT5.ReleaseVer,table_property:"editor_table_property.html?ver="+DEXT5.ReleaseVer,cell_property:"editor_cell_property.html?ver="+DEXT5.ReleaseVer,insert_row_column:"editor_insert_row_column.html?ver="+DEXT5.ReleaseVer,row_property:"editor_row_property.html?ver="+DEXT5.ReleaseVer,column_property:"editor_column_property.html?ver="+DEXT5.ReleaseVer,emoticon:"editor_emoticon.html?ver="+
DEXT5.ReleaseVer,bookmark:"editor_bookmark.html?ver="+DEXT5.ReleaseVer,iframe:"editor_iframe.html?ver="+DEXT5.ReleaseVer,hyperlink:"editor_hyperlink.html?ver="+DEXT5.ReleaseVer,split_cell:"editor_split_cell.html?ver="+DEXT5.ReleaseVer,about:"editor_about.html?ver="+DEXT5.ReleaseVer,symbol:"editor_symbol.html?ver="+DEXT5.ReleaseVer,setting:"editor_setting.html?ver="+DEXT5.ReleaseVer,template:"editor_template.html?ver="+DEXT5.ReleaseVer,tool_replace:"editor_tool_replace.html?ver="+DEXT5.ReleaseVer,
insert_link_media:"editor_insert_link_media.html?ver="+DEXT5.ReleaseVer,m_insert_link_media:"editor_m_insert_link_media.html?ver="+DEXT5.ReleaseVer,m_image:"editor_m_image.html?ver="+DEXT5.ReleaseVer,m_emoticon:"editor_m_emoticon.html?ver="+DEXT5.ReleaseVer,cell_border:"editor_cell_border.html?ver="+DEXT5.ReleaseVer,paste_dialog:"editor_paste.html?ver="+DEXT5.ReleaseVer,shortcut:"editor_shortcut.html?ver="+DEXT5.ReleaseVer,layout:"editor_layout.html?ver="+DEXT5.ReleaseVer,insert_file:"editor_insert_file.html?ver="+
DEXT5.ReleaseVer,file_open:"editor_file_open.html?ver="+DEXT5.ReleaseVer,blockquote:"editor_blockquote.html?ver="+DEXT5.ReleaseVer,input_text:"editor_input_text.html?ver="+DEXT5.ReleaseVer,input_radio:"editor_input_radio.html?ver="+DEXT5.ReleaseVer,input_checkbox:"editor_input_checkbox.html?ver="+DEXT5.ReleaseVer,input_button:"editor_input_button.html?ver="+DEXT5.ReleaseVer,input_hidden:"editor_input_hidden.html?ver="+DEXT5.ReleaseVer,input_textarea:"editor_input_textarea.html?ver="+DEXT5.ReleaseVer,
input_select:"editor_input_select.html?ver="+DEXT5.ReleaseVer,input_image:"editor_input_image.html?ver="+DEXT5.ReleaseVer,accessibility_validation:"editor_accessibility_validation.html?ver="+DEXT5.ReleaseVer,table_lock_property:"editor_table_lock_property.html?ver="+DEXT5.ReleaseVer};this.editor_id=this.xss_use=this.xss_remove_events=this.xss_remove_tags=this.replace_tagname="";this.mode="edit";this.mimeUse="0";this.zIndex=1E4;this.ruler={use:"0",view:"0",rulerInitPosition:"0",viewPointer:"1",viewGuideLine:"1",
viewRuler:"1"};this.horizontalLine={use:"0",url:""};this.editorborder="1";this.imageBaseUrl=this.custom_code="";this.allowMediaFileType=[];this.allowImageFileType=[];this.allowFlashFileType=[];this.allowInsertFileType=[];this.attachFileImage="1";this.tableClassList=[];this.tableLineStyleList=[];this.tableDefaultTdHeight=this.tableDefaultClass=this.tableDefaultHeight=this.tableDefaultWidth="";this.tableLineStyleValue={};this.tableLineStyleValue._solid="border-top: 1px solid #5d5d5d;";this.tableLineStyleValue._dotted=
"border-top: 1px dotted #5d5d5d;";this.tableLineStyleValue._dashed="border-top: 1px dashed #5d5d5d;";this.tableLineStyleValue._double="border-top: 3px double #5d5d5d;";this.tableLineStyleValue._groove="border: 3px groove #e1e1e1;";this.tableLineStyleValue._ridge="border: 3px ridge #e1e1e1;";this.tableLineStyleValue._inset="border: 3px inset #e1e1e1;";this.tableLineStyleValue._outset="border: 3px outset #e1e1e1;";this.tableLineStyleValue._none="border: 1px none #5d5d5d;";this.tableLineStyleValue._hidden=
"border: 1px none #5d5d5d;";this.tableDefaultInoutdent=20;this.tableNoSelectionClass=this.tableNoActionClass=this.tableNoResizeClass=this.tableInitInoutdent="";this.tableColMaxCount=this.tableRowMaxCount="13";this.allowInoutdentText="0";this.defaultBorderColor="#000000";this.showLineForBorderNone="0";this.tabIndexObjId=this.focusInitEditorObjId=this.focusInitObjId="";this.setDefaultStyle={value:"0",body_id:"dext_body",dext_set_style:"1"};this.setDefaultUserStyle=[];this.popupCssUrl="../css/editor_popup.css?ver="+
DEXT5.ReleaseVer;this.symbolUrl="../js/editor_symbol.js?ver="+DEXT5.ReleaseVer;this.dialogJSUrl="../js/editor_dialog.js?ver="+DEXT5.ReleaseVer;this.customEventCmd={image:{ondbclick:""}};this.ieCompatible="";this.autoUrlDetect="1";this.scrollOverflow=this.pasteRemoveEmptyTag="0";this.disableKeydown=this.autoBodyFit=this.disableTabletap=this.defaultImemode="";this.dragAndDropAllow="0";this.limitPasteHtmlLength={value:"0",length:13E5};this.pasteToImage="1";this.eventForPasteImage=this.notRepairInViewMode=
this.viewModeAllowCopy=this.viewModeBrowserMenu=this.removeSpaceInTagname=this.wrapPtagToGetApi=this.wrapPtagToSource="0";this.useHtmlCorrection=this.removeColgroup="1";this.runtimes="";this.setAutoSave={mode:"2",interval:.5};this.insertCarriageReturn="0";this.returnEvent={mouse_event:"0",key_event:"0"};this.ie11_BugFixed_JASO=this.useCorrectInOutdent="0";this.isLoadedEditor=!1;this.setValueObjId="";this.replaceEmptyTagWithSpace="1";this.LoadedEvent="";this.frameFullScreen="0";this.currFontFamily=
"";this.allowImgSize="1";this.hyperlinkTargetList=[];this.hyperlinkCategoryList=[];this.hyperlinkProtocolList=[];this.developLang="NET";this.formMode="0";this.openDocument={beforeOpenEvent:"0",useHwp:"0",word:{maxSize:0,maxPage:0},excel:{maxSize:0,maxSheet:0},powerpoint:{maxSize:0,maxSlide:0}};this.removeLastBrTag="0";this.editorBodyEditable=!0;this.inoutdentDefaultSize=40;this.statusBarItem=this.accessibilityValidationItems="";this.statusBarTitle=[];this.statusBarInitMode="design";this.dragResize=
"0";this.dragResizeApplyBrowser=[];this.replaceOutsideImage={use:"0",exceptDomain:[]};this.eventList=[];this.userJsUrl="";this.fontFamilyList=[];this.fontSizeList=[];this.lineHeightList=[];this.formattingList=[];this.adminTableLock={defaultShowLockIconUserMode:"0",defaultLockName:"dext_lock",checkLockName:["dext_lock"],defaultTableLockMode:"2"};this.userTableLock={use:"0",lockName:["dext_lock"],defaultTableLockMode:"2",defaultShowLockIcon:"1"};this.removeComment="1";this.tool_bar_grouping="0";this.setDefaultValueInEmptyTag=
"p div h1 h2 h3 h4 h5".split(" ");this.userHelpUrl=this.metaHttpEquiv=this.directEditHtmlUrl=this.userCssAlwaysSet=this.photoEditorId="";this.useGZip="0";this.topStatusBarLoading=this.statusBarLoading="1";this.hasContainer="0";this.security={encryptParam:"0"};this.tabSpace="&nbsp;&nbsp;&nbsp;&nbsp;";this.document={docTitle:""};this.addHtmlToSetValue={html:"",preOrSub:0};this.imgUploadContenttype="0";this.imageCustomPropertyDelimiter="|";this.useHybrid="0";this.lineHeightMode=this.useGetHtmlToLowerCase=
this.hybridWindowMode="1";this.applyStyleEmptyTag="0"}function isExistEditorName(b){if(void 0==b||""==b)return 1;var c=DEXT5.DEXTMULTIPLE["dext_frame_"+b];return void 0==c||null==c?0:""!=DEXT5.config.EditorHolder&&DEXT5.DEXTHOLDER[b]==DEXT5.config.EditorHolder?3:2}function getNewNextEditorName(b){var c="",c=b.split("_"),a=c.length;1<a&&(b=b.replace("_"+c[a-1],""));c=b+getNextEditorNumber();0<isExistEditorName(c)&&(c=getNewNextEditorName(c));return c}
var getNextEditorNumber=function(){var b=0;return function(){return"_"+ ++b}}();
function Dext5editor(b){var c=isExistEditorName(b);if(1==c)alert("editor's name is empty. Please, check editor's name");else{if(2==c)if("1"==DEXT5.config.IgnoreSameEditorName)b=getNewNextEditorName(b);else{alert("editor's name is already exist. Please, check editor's name");return}var a=new DEXT_CONFIG;if(0<DEXT5.config.InitServerXml.length)if(-1<DEXT5.config.InitServerXml.indexOf("f="))a.config_url=DEXT5.config.InitServerXml+"&dext5CMD=configRequest";else{alert("Error occurred reading the Editor Settings");
return}else 0<DEXT5.config.InitXml.length&&(0==DEXT5.config.InitXml.indexOf("http")?a.config_url=DEXT5.config.InitXml:a.config_url=DEXT5.rootPath+"config/"+DEXT5.config.InitXml);"1"==DEXT5.config.UseConfigTimeStamp?-1<a.config_url.indexOf("?")?a.config_url+="&t="+(new Date).getTime():a.config_url+="?t="+(new Date).getTime():-1<a.config_url.indexOf("?")?a.config_url+="&ver="+DEXT5.ReleaseVer:a.config_url+="?ver="+DEXT5.ReleaseVer;var e=null,e=0<DEXT5.config.InitServerXml.length?DEXT5.ajax.load(a.config_url):
DEXT5.ajax.loadXml(a.config_url);if(null==e)alert("ErrCode : 1000");else{if("object"!=typeof e)if(0==e.indexOf("[OK]"))e=e.substring(4),e=DEXT5.util.base64_decode(e),e=e.substring(e.indexOf("<?")),e=DEXT5.util.stringToXML(e);else{if(0==e.indexOf("[FAIL]")){alert("Error occurred reading the Editor Settings");return}(e=DEXT5.util.stringToXML(e))||alert("Error occurred reading the Editor Settings")}this.configXml=e;3!=c&&(DEXT5.DEXTMULTIPLEID.push(b),DEXT5.DEXTMULTIPLE["dext_frame_"+b]=b,DEXT5.DEXTHOLDER[b]=
DEXT5.config.EditorHolder);DEXT5.isRelease?(a.popupCssUrl="../css/editor_popup.css",a.dialogJSUrl="../js/editor_dialog.js"):(a.popupCssUrl="../css_dev/editor_popup.css",a.dialogJSUrl="../js_dev/editor_dialog.js");var h=DEXT5.util.xml.getNode(e,"xss_protection"),g=DEXT5.util.xml.getNodeValue(h,"xss_use"),f=DEXT5.util.xml.getNodeValue(h,"xss_remove_tags"),k=DEXT5.util.xml.getNodeValue(h,"xss_remove_events");""==g&&(g="0");""!=DEXT5.config.zXssUse&&(g=DEXT5.config.zXssUse);a.xss_use=g;""!=DEXT5.config.zXssRemoveTags&&
(f=DEXT5.config.zXssRemoveTags);a.xss_remove_tags=f.toLowerCase();""!=DEXT5.config.zXssRemoveEvents&&(k=DEXT5.config.zXssRemoveEvents);"all"==k.toLowerCase()?a.xss_remove_events="onabort,onactivate,onafterprint,onafterupdate,onbeforeactivate,onbeforecopy,onbeforecut,onbeforedeactivate,onbeforeeditfocus,onbeforepaste,onbeforeprint,onbeforeunload,onbeforeupdate,onbegin,onblur,onbounce,oncellchange,onchange,onclick,oncontentready,oncontentsave,oncontextmenu,oncontrolselect,oncopy,oncut,ondataavailable, ondatasetchanged, ondatasetcomplete, ondblclick, ondeactivate,ondetach, ondocumentready, ondrag, ondragdrop, ondragend,ondragenter,ondragleave,ondragover,ondragstart,ondrop,onend,onerror,onerrorupdate,onfilterchange,onfinish,onfocus,onfocusin,onfocusout,onhelp,onhide,onkeydown,onkeypress,onkeyup,onlayoutcomplete,onload,onlosecapture,onmediacomplete,onmediaerror,onmedialoadfailed,onmousedown,onmouseenter,onmouseleave,onmousemove,onmouseout,onmouseover,onmouseup,onmousewheel,onmove,onmoveend,onmovestart,onopenstatechange,onoutofsync,onpaste,onpause,onplaystatechange,onpropertychange,onreadystatechange,onrepeat,onreset,onresize,onresizeend,onresizestart,onresume,onreverse,onrowclick,onrowenter,onrowexit,onrowout,onrowover,onrowsdelete,onrowsinserted,onsave,onscroll,onseek,onselect,onselectionchange,onselectstart,onshow,onstart,onstop,onsubmit,onsyncrestored,ontimeerror,ontrackchange,onunload,onurlflip":
a.xss_remove_events=k.toLowerCase();1E4<=parseInt(DEXT5.config.zIndex,10)&&(a.zIndex=parseInt(DEXT5.config.zIndex,10));a.editorborder=""==DEXT5.config.EditorBorder?"1":DEXT5.config.EditorBorder;var d=DEXT5.util.xml.getNode(e,"setting"),l=DEXT5.util.xml.getNodeValue(d,"runtimes"),m=DEXT5.util.xml.getNodeValue(d,"width"),t=DEXT5.util.xml.getNodeValue(d,"height"),q=DEXT5.util.xml.getNodeValue(d,"skinname"),r=DEXT5.util.xml.getNodeValue(d,"lang"),y=DEXT5.util.xml.getNodeValue(d,"accessibility"),A=DEXT5.util.xml.getNodeValue(d,
"showdialog_pos"),u=DEXT5.util.xml.getNodeValue(d,"source_viewtype"),H=DEXT5.util.xml.getNodeValue(d,"user_css_url"),I=DEXT5.util.xml.getNodeValue(d,"user_js_url"),P=DEXT5.util.xml.getNodeValue(d,"xhtml_value"),W=DEXT5.util.xml.getNodeValue(d,"system_title"),Da=DEXT5.util.xml.getNodeValue(d,"table_auto_adjust"),Xb=DEXT5.util.xml.getNodeValue(d,"context_menu_disable"),T=DEXT5.util.xml.getNodeValue(d,"enter_tag"),Ea=DEXT5.util.xml.getNodeValue(d,"office_linefix"),Fa=DEXT5.util.xml.getNodeValue(d,"editor_tab_disable"),
Ga=DEXT5.util.xml.getNodeValue(d,"frame_fullscreen"),Yb=DEXT5.util.xml.getNodeValue(d,"allow_img_size"),la=DEXT5.util.xml.getNode(d,"user_css_url");"0"==Yb&&(a.allowImgSize="0");""!=DEXT5.config.FrameFullScreen?a.frameFullScreen=DEXT5.config.FrameFullScreen:""!=Ga&&(a.frameFullScreen=Ga);var ma="";""!=DEXT5.config.RunTimes?ma=DEXT5.config.RunTimes:""!=l&&(ma=l);a.runtimes=GetUserRunTimeEditor(ma);a.EditorTabDisable=""==DEXT5.config.EditorTabDisable?0==Fa.length?a.EditorTabDisable:Fa:DEXT5.config.EditorTabDisable;
DEXT5.util.xml.getNode(d,"editor_tab_disable");var ca=0;if(""!=DEXT5.config.TabSpace.toString())0<DEXT5.config.TabSpace&&(ca=DEXT5.config.TabSpace);else{var X=DEXT5.util.xml.getNode(d,"editor_tab_disable");X&&X.getAttribute("tab_space")&&""!=X.getAttribute("tab_space")&&0<X.getAttribute("tab_space").toString()&&(ca=X.getAttribute("tab_space"))}if(0<ca){a.tabSpace="";for(var n=0;n<ca;n++)a.tabSpace+="&nbsp;"}a.contextMenuDisable="1"==Xb?"1":"0";var Ha=DEXT5.util.xml.getNodeValue(d,"ie_compatible");
""!=Ha&&(a.ieCompatible=Ha);var Ia=DEXT5.util.xml.getNodeValue(d,"auto_url_detect");""!=Ia&&(a.autoUrlDetect=Ia);a.officeLineFix=""==DEXT5.config.officeLineFix?0==Ea.length?a.officeLineFix:Ea:DEXT5.config.officeLineFix;"1"==DEXT5.util.xml.getNodeValue(d,"paste_remove_empty_tag")&&(a.pasteRemoveEmptyTag="1");var Ja=DEXT5.util.xml.getNodeValue(d,"scroll_overflow");a.scrollOverflow=""==DEXT5.config.scrollOverflow?0==Ja.length?a.scrollOverflow:Ja:DEXT5.config.scrollOverflow;"1"==DEXT5.util.xml.getNodeValue(d,
"default_imemode")&&(a.defaultImemode="1");"1"==DEXT5.util.xml.getNodeValue(d,"disable_tabletap")&&(a.disableTabletap="1");""!=DEXT5.config.AutoBodyFit?a.autoBodyFit=DEXT5.config.AutoBodyFit:"1"==DEXT5.util.xml.getNodeValue(d,"auto_body_fit")&&(a.autoBodyFit="1");"1"==DEXT5.util.xml.getNodeValue(d,"disable_keydown")&&(a.disableKeydown="1");var Zb=DEXT5.util.xml.getNode(d,"custom_event"),$b=DEXT5.util.xml.getNode(Zb,"image"),Ka=DEXT5.util.xml.getNodeValue($b,"ondbclick");""!=Ka&&(a.customEventCmd.image.ondbclick=
Ka);var ac=DEXT5.util.xml.getNode(d,"pageurl"),bc=DEXT5.util.xml.getNode(ac,"script"),La=DEXT5.util.xml.getNodeValue(bc,"symbol");a.symbolUrl=""==DEXT5.config.SymbolUrl?""!=La?La:DEXT5.isRelease?"../js/editor_symbol.js":"../js_dev/editor_symbol.js":DEXT5.config.SymbolUrl;var na=DEXT5.util.xml.getNodeValue(d,"icon_name");""!=na&&(a.style.iconName=na,DEXT5.config.IconName=na);if(""==DEXT5.config.ImageBaseUrl){var Ma=DEXT5.util.xml.getNodeValue(d,"image_base_url");""!=Ma&&(a.imageBaseUrl=Ma)}else a.imageBaseUrl=
DEXT5.config.ImageBaseUrl;if(""==DEXT5.config.DragResize){var Na=DEXT5.util.xml.getNodeValue(d,"drag_resize");""!=Na&&(a.dragResize=Na)}else a.dragResize=DEXT5.config.DragResize;if(""==DEXT5.config.DragResizeApplyBrowser){var da=DEXT5.util.xml.getNode(d,"drag_resize");da&&da.getAttribute("apply_browser")&&""!=da.getAttribute("apply_browser")&&(a.dragResizeApplyBrowser=da.getAttribute("apply_browser").split(","))}else a.dragResizeApplyBrowser=DEXT5.config.DragResizeApplyBrowser.split(",");""!=DEXT5.config.FontFamilyList&&
(a.fontFamilyList=DEXT5.config.FontFamilyList.split(","));""!=DEXT5.config.FontSizeList&&(a.fontSizeList=a.fontSizeList.concat(DEXT5.config.FontSizeList.split(",")));if(""!=DEXT5.config.LineHeightList)a.lineHeightList=a.lineHeightList.concat(DEXT5.config.LineHeightList.split(","));else{var oa=DEXT5.util.xml.getNode(e,"line_height");if(oa)for(var cc=DEXT5.util.xml.count(oa,"line"),pa=0;pa<cc;pa++)a.lineHeightList.push(DEXT5.util.xml.getNodeValueIdx(oa,"line",pa))}0==a.lineHeightList.length&&(a.lineHeightList=
"100% 120% 150% 180% 200% 250% 300%".split(" "));""!=DEXT5.config.FormattingList&&(a.formattingList.push(""),a.formattingList=a.formattingList.concat(DEXT5.config.FormattingList.split(",")));if(""!=DEXT5.config.Ruler.Use)"1"==DEXT5.config.Ruler.Use&&(a.ruler.use="1",a.ruler.view="1"),"1"==a.ruler.use&&DEXT5.config.Ruler.InitPosition&&""!=DEXT5.config.Ruler.InitPosition&&(a.ruler.rulerInitPosition=DEXT5.config.Ruler.InitPosition),"1"==a.ruler.use&&DEXT5.config.Ruler.ViewPointer&&"1"!=DEXT5.config.Ruler.ViewPointer&&
(a.ruler.viewPointer="0"),"1"==a.ruler.use&&DEXT5.config.Ruler.ViewGuideLine&&"1"!=DEXT5.config.Ruler.ViewGuideLine&&(a.ruler.viewGuideLine="0"),"1"==a.ruler.use&&DEXT5.config.Ruler.ViewRuler&&"1"!=DEXT5.config.Ruler.ViewRuler&&(a.ruler.viewRuler="0");else if("1"==DEXT5.util.xml.getNodeValue(d,"use_ruler")){a.ruler.use="1";a.ruler.view="1";var D=DEXT5.util.xml.getNode(d,"use_ruler");D.getAttribute("ruler_init_position")&&""!=D.getAttribute("ruler_init_position")&&(a.ruler.rulerInitPosition=D.getAttribute("ruler_init_position"));
D.getAttribute("view_pointer")&&"1"!=D.getAttribute("view_pointer")&&(a.ruler.viewPointer="0");D.getAttribute("view_guide_line")&&"1"!=D.getAttribute("view_guide_line")&&(a.ruler.viewGuideLine="0");D.getAttribute("view_ruler")&&"1"!=D.getAttribute("view_ruler")&&(a.ruler.viewRuler="0")}if(""!=DEXT5.config.UseHorizontalLine)a.horizontalLine.use="1",a.horizontalLine.url=DEXT5.config.UseHorizontalLine;else if("1"==DEXT5.util.xml.getNodeValue(d,"use_horizontal_line")){var qa=DEXT5.util.xml.getNode(d,
"use_horizontal_line");qa.getAttribute("url")&&""!=qa.getAttribute("url")&&(a.horizontalLine.use="1",a.horizontalLine.url=qa.getAttribute("url"))}if(""==a.enterTag)if(""!=DEXT5.config.EnterTag){if(DEXT5.config.EnterTag=DEXT5.config.EnterTag.toLocaleLowerCase(),"br"==DEXT5.config.EnterTag||"div"==DEXT5.config.EnterTag)a.enterTag=DEXT5.config.EnterTag}else{if(T=T.toLocaleLowerCase(),"br"==T||"div"==T)a.enterTag=T}else a.enterTag=a.enterTag.toLocaleLowerCase(),a.enterTag="br"!=a.enterTag&&"div"!=a.enterTag?
"":T;var ra=DEXT5.util.xml.getNodeValue(d,"set_default_style"),E=DEXT5.util.xml.getNode(d,"set_default_style");""!=ra&&"0"!=ra?(a.setDefaultStyle.value=ra,""!=E.getAttribute("body_id")&&(a.setDefaultStyle.body_id=E.getAttribute("body_id")),E.getAttribute("user_style")&&""!=E.getAttribute("user_style")&&(a.setDefaultUserStyle=E.getAttribute("user_style").split(","))):E&&E.getAttribute("dext_set_style")&&""!=E.getAttribute("dext_set_style")&&(a.setDefaultStyle.dext_set_style=E.getAttribute("dext_set_style"));
var Oa=DEXT5.util.xml.getNodeValue(d,"drag_and_drop_allow");"1"==Oa&&(a.dragAndDropAllow=Oa);if("1"==DEXT5.util.xml.getNodeValue(d,"limit_paste_html_length")){a.limitPasteHtmlLength.value="1";var Pa=DEXT5.util.xml.getNode(d,"limit_paste_html_length");""!=Pa.getAttribute("length")&&(a.limitPasteHtmlLength.length=parseInt(Pa.getAttribute("length"),10))}var ea=DEXT5.util.xml.getNode(d,"wrap_ptag_to_source");if(ea){var Qa=DEXT5.util.xml.getNodeValue(d,"wrap_ptag_to_source");""!=Qa&&(a.wrapPtagToSource=
Qa);DEXT5.browser.gecko&&ea.getAttribute("apply_to_get_api")&&""!=ea.getAttribute("apply_to_get_api")&&(a.wrapPtagToGetApi=ea.getAttribute("apply_to_get_api"))}var sa=DEXT5.util.xml.getNodeValue(d,"paste_to_image");if("0"==sa||"2"==sa)a.pasteToImage=sa;"1"==DEXT5.util.xml.getNodeValue(d,"remove_space_in_tagname")&&(a.removeSpaceInTagname="1");"1"==DEXT5.util.xml.getNodeValue(d,"view_mode_browser_menu")&&(a.viewModeBrowserMenu="1");"1"==DEXT5.util.xml.getNodeValue(d,"view_mode_allow_copy")&&(a.viewModeAllowCopy=
"1");"1"==DEXT5.util.xml.getNodeValue(d,"event_for_paste_image")&&(a.eventForPasteImage="1");"0"==DEXT5.util.xml.getNodeValue(d,"remove_colgroup")&&(a.removeColgroup="0");"0"==DEXT5.util.xml.getNodeValue(d,"use_html_correction")&&(a.useHtmlCorrection="0");var Ra=DEXT5.util.xml.getNodeValue(d,"formlist_url");""!=DEXT5.config.FormListUrl?a.forms_url=DEXT5.config.FormListUrl:""!=Ra&&(a.forms_url=Ra);var ta=DEXT5.util.xml.getNodeValue(d,"set_auto_save");if(""!=ta&&(a.setAutoSave.mode=ta,"1"==ta&&(xmlSetAutoSaveNode=
DEXT5.util.xml.getNode(d,"set_auto_save"),xmlSetAutoSaveNode.getAttribute("interval")&&""!=xmlSetAutoSaveNode.getAttribute("interval")))){var ua;ua=Math.floor(10*xmlSetAutoSaveNode.getAttribute("interval"))/10;.5<=ua&&(a.setAutoSave.interval=ua)}"1"==DEXT5.util.xml.getNodeValue(d,"insert_carriage_return")&&(a.insertCarriageReturn="1");var Y=DEXT5.util.xml.getNode(d,"return_event");Y&&(Y.getAttribute("mouse_event")&&"1"==Y.getAttribute("mouse_event")&&(a.returnEvent.mouse_event="1"),Y.getAttribute("keyboard_event")&&
"1"==Y.getAttribute("keyboard_event")&&(a.returnEvent.key_event="1"));"1"==DEXT5.util.xml.getNodeValue(d,"use_correct_in_outdent")&&(a.useCorrectInOutdent="1");var Sa=DEXT5.util.xml.getNode(d,"browser_bugfixed");if(Sa&&DEXT5.browser.ie&&(7==DEXT5.browser.trident||12<=DEXT5.browser.ieVersion)){var Ta=DEXT5.util.xml.getNodeValue(Sa,"ie11_jaso");Ta&&"1"==Ta&&(a.ie11_BugFixed_JASO="1")}"0"==DEXT5.util.xml.getNodeValue(d,"replace_empty_tag_with_space")&&(a.replaceEmptyTagWithSpace="0");var fa=DEXT5.util.xml.getNodeValue(d,
"image_custom_property_delimiter");""!=DEXT5.config.ImageCustomPropertyDelimiter?a.imageCustomPropertyDelimiter=DEXT5.config.ImageCustomPropertyDelimiter:null!=fa&&""!=fa&&"|"!=fa&&(a.imageCustomPropertyDelimiter=fa);var J=DEXT5.util.xml.getNode(d,"manager_mode");""!=DEXT5.config.ManagerMode?a.formMode=DEXT5.config.ManagerMode:J&&J.getAttribute("use")&&"1"==J.getAttribute("use")&&(a.formMode=J.getAttribute("use"));if("1"==a.formMode&&""!=DEXT5.config.EventList)a.eventList=DEXT5.config.EventList.split(",");
else if(J&&"1"==a.formMode)for(var Ua=DEXT5.util.xml.getNode(J,"event_list"),dc=DEXT5.util.xml.count(Ua,"event"),n=0;n<dc;n++)a.eventList[n]=DEXT5.util.xml.getNodeValueIdx(Ua,"event",n);if(""!=DEXT5.config.AdminTableLock.DefaultShowLockIconUserMode||DEXT5.config.AdminTableLock.DefaultLockName||""!=DEXT5.config.AdminTableLock.CheckLockName||""!=DEXT5.config.AdminTableLock.DefaultTableLockMode)""!=DEXT5.config.AdminTableLock.DefaultShowLockIconUserMode&&(a.adminTableLock.defaultShowLockIconUserMode=
DEXT5.config.AdminTableLock.DefaultShowLockIconUserMode),""!=DEXT5.config.AdminTableLock.DefaultLockName&&(a.adminTableLock.defaultLockName=DEXT5.config.AdminTableLock.DefaultLockName),""!=DEXT5.config.AdminTableLock.CheckLockName&&(a.adminTableLock.checkLockName=DEXT5.config.AdminTableLock.CheckLockName.split(",")),""!=DEXT5.config.AdminTableLock.DefaultTableLockMode&&(a.adminTableLock.defaultTableLockMode=DEXT5.config.AdminTableLock.DefaultTableLockMode);else if(J){var x=DEXT5.util.xml.getNode(J,
"table_lock");x&&(x&&x.getAttribute("default_show_lock_icon_user_mode")&&""!=x.getAttribute("default_show_lock_icon_user_mode")&&(a.adminTableLock.defaultShowLockIconUserMode=x.getAttribute("default_show_lock_icon_user_mode")),x&&x.getAttribute("default_lock_name")&&""!=x.getAttribute("default_lock_name")&&(a.adminTableLock.defaultLockName=x.getAttribute("default_lock_name")),x&&x.getAttribute("check_lock_name")&&""!=x.getAttribute("check_lock_name")&&(a.adminTableLock.checkLockName=x.getAttribute("check_lock_name").split(",")),
x&&x.getAttribute("default_table_lock_mode")&&""!=x.getAttribute("default_table_lock_mode")&&(a.adminTableLock.defaultTableLockMode=x.getAttribute("default_table_lock_mode")))}if(""!=DEXT5.config.UserTableLock.Use)a.userTableLock.use=DEXT5.config.UserTableLock.Use,""!=DEXT5.config.UserTableLock.LockName&&(a.userTableLock.lockName=DEXT5.config.UserTableLock.LockName.split(",")),""!=DEXT5.config.UserTableLock.DefaultTableLockMode&&(a.userTableLock.defaultTableLockMode=DEXT5.config.UserTableLock.DefaultTableLockMode),
""!=DEXT5.config.UserTableLock.DefaultShowLockIcon&&(a.userTableLock.defaultShowLockIcon=DEXT5.config.UserTableLock.DefaultShowLockIcon);else{var Va=DEXT5.util.xml.getNodeValue(d,"table_lock_user_mode");if("1"==Va){a.userTableLock.use=Va;var B=DEXT5.util.xml.getNode(d,"table_lock_user_mode");B&&B.getAttribute("lock_name")&&""!=B.getAttribute("lock_name")&&(a.userTableLock.lockName=B.getAttribute("lock_name").split(","));B&&B.getAttribute("default_table_lock_mode")&&""!=B.getAttribute("default_table_lock_mode")&&
(a.userTableLock.defaultTableLockMode=B.getAttribute("default_table_lock_mode"));B&&B.getAttribute("default_show_lock_icon")&&""!=B.getAttribute("default_show_lock_icon")&&(a.userTableLock.defaultShowLockIcon=B.getAttribute("default_show_lock_icon"))}}var K=DEXT5.util.xml.getNode(d,"open_document");if(K){K.getAttribute("before_open_event")&&""!=K.getAttribute("before_open_event")&&(a.openDocument.beforeOpenEvent=K.getAttribute("before_open_event"));var Q=DEXT5.util.xml.getNode(K,"word");Q&&(Q.getAttribute("max_size")&&
""!=Q.getAttribute("max_size")&&(a.openDocument.word.maxSize=parseInt(Q.getAttribute("max_size"),0)),Q.getAttribute("max_page")&&""!=Q.getAttribute("max_page")&&(a.openDocument.word.maxPage=parseInt(Q.getAttribute("max_page"),0)));var R=DEXT5.util.xml.getNode(K,"excel");R&&(R.getAttribute("max_size")&&""!=R.getAttribute("max_size")&&(a.openDocument.excel.maxSize=parseInt(R.getAttribute("max_size"),0)),R.getAttribute("max_sheet")&&""!=R.getAttribute("max_sheet")&&(a.openDocument.excel.maxSheet=parseInt(R.getAttribute("max_sheet"),
0)));var S=DEXT5.util.xml.getNode(K,"powerpoint");S&&(S.getAttribute("max_size")&&""!=S.getAttribute("max_size")&&(a.openDocument.powerpoint.maxSize=parseInt(S.getAttribute("max_size"),0)),S.getAttribute("max_slide")&&""!=S.getAttribute("max_slide")&&(a.openDocument.powerpoint.maxSlide=parseInt(S.getAttribute("max_slide"),0)));var Wa=K.getAttribute("use_hwp");Wa&&"1"==Wa&&(a.openDocument.useHwp="1")}"1"==DEXT5.util.xml.getNodeValue(d,"remove_last_br_tag")&&(a.removeLastBrTag="1");""!=DEXT5.config.EditorBodyEditable?
"0"==DEXT5.config.EditorBodyEditable&&(a.editorBodyEditable=!1):"0"==DEXT5.util.xml.getNodeValue(d,"editor_body_editable")&&(a.editorBodyEditable=!1);if(""!=DEXT5.config.ReplaceOutsideImage)a.replaceOutsideImage.use=DEXT5.config.ReplaceOutsideImage,""!=DEXT5.config.ReplaceOutsideImageExceptDomain&&(a.replaceOutsideImage.exceptDomain=DEXT5.config.ReplaceOutsideImageExceptDomain.split(","));else if("1"==DEXT5.util.xml.getNodeValue(d,"replace_outside_image")){a.replaceOutsideImage.use="1";var va=DEXT5.util.xml.getNode(d,
"replace_outside_image");va.getAttribute("except_domain")&&""!=va.getAttribute("except_domain")&&(a.replaceOutsideImage.exceptDomain=va.getAttribute("except_domain").split(","))}if(""!=DEXT5.config.RemoveComment)a.removeComment=DEXT5.config.RemoveComment;else{var Xa=DEXT5.util.xml.getNodeValue(d,"remove_comment");"0"==Xa&&(a.removeComment=Xa)}if(""!=DEXT5.config.SetDefaultValueInEmptyTag)a.setDefaultValueInEmptyTag=DEXT5.config.SetDefaultValueInEmptyTag.split(",");else{var Ya=DEXT5.util.xml.getNodeValue(d,
"set_default_value_in_empty_tag");""!=Ya&&(a.setDefaultValueInEmptyTag=Ya.split(","))}if(""!=DEXT5.config.Document.DocTitle)a.document.docTitle=DEXT5.config.Document.DocTitle;else{var Za=DEXT5.util.xml.getNode(d,"document");if(Za){var $a=DEXT5.util.xml.getNodeValue(Za,"doc_title");""!=$a&&(a.document.docTitle=$a)}}var ab=DEXT5.util.xml.getNode(d,"hybrid");ab&&"0"==DEXT5.util.xml.getNodeValue(ab,"hybrid_window_mode")&&(a.hybridWindowMode="0");var bb=DEXT5.util.xml.getNodeValue(d,"use_get_htmltolowercase");
""!=bb&&"1"!=bb&&(a.useGetHtmlToLowerCase="0");if(""!=DEXT5.config.ApplyStyleEmptyTag)a.applyStyleEmptyTag=DEXT5.config.ApplyStyleEmptyTag;else{var cb=DEXT5.util.xml.getNodeValue(d,"apply_style_empty_tag");""!=cb&&(a.applyStyleEmptyTag=cb)}""!=DEXT5.config.PhotoEditorId&&(a.photoEditorId=DEXT5.config.PhotoEditorId);var v=DEXT5.util.xml.getNode(e,"uploader_setting"),L=DEXT5.util.xml.getNodeValue(v,"develop_langage"),C=DEXT5.util.xml.getNodeValue(v,"handler_url"),db=DEXT5.util.xml.getNodeValue(v,"to_save_path_url"),
eb=DEXT5.util.xml.getNodeValue(v,"to_save_file_path_url"),M=DEXT5.util.xml.getNodeValue(v,"save_foldername_rule"),N=DEXT5.util.xml.getNodeValue(v,"save_file_foldername_rule"),ec=DEXT5.util.xml.getNodeValue(v,"server_domain"),wa=DEXT5.util.xml.getNodeValue(v,"save_filename_rule"),fc=DEXT5.util.xml.getNodeValue(v,"image_convert_format"),gc=DEXT5.util.xml.getNodeValue(v,"image_convert_width"),hc=DEXT5.util.xml.getNodeValue(v,"image_convert_height"),ic=DEXT5.util.xml.getNodeValue(v,"image_auto_fit"),
fb=DEXT5.util.xml.getNodeValue(v,"handler_url_save_for_notes");""!=DEXT5.config.HandlerUrlSaveForNotes?a.post_url_save_for_notes=DEXT5.config.HandlerUrlSaveForNotes:""!=fb&&(a.post_url_save_for_notes=fb);var ga=DEXT5.util.xml.getNode(e,"extra_setting");ga&&(a.paste_image_base64=DEXT5.util.xml.getNodeValue(ga,"paste_image_base64"),a.empty_tag_remove=DEXT5.util.xml.getNodeValue(ga,"empty_tag_remove"),a.custom_code=DEXT5.util.xml.getNodeValue(ga,"custom_code"),DEXT5.config.CustomCode=a.custom_code);
a.serverDomain=ec;0<DEXT5.config.ServerDomain.length&&(a.serverDomain=DEXT5.config.ServerDomain);0<DEXT5.config.HandlerUrl.length&&(C=DEXT5.config.HandlerUrl);a.image_convert_format=fc;a.image_convert_width=gc;a.image_convert_height=hc;a.image_auto_fit=ic;var gb=DEXT5.util.xml.getNodeValue(v,"allow_media_file_type");if(0<gb.length)for(var hb=gb.split(","),jc=hb.length,n=0;n<jc;n++)a.allowMediaFileType.push(hb[n]);else a.allowMediaFileType=["wmv","asf"];var ib=DEXT5.util.xml.getNodeValue(v,"allow_image_file_type");
if(0<ib.length)for(var jb=ib.split(","),kc=jb.length,n=0;n<kc;n++)a.allowImageFileType.push(jb[n]);else a.allowImageFileType=["jpg","jpeg","png","gif","bmp"];var kb=DEXT5.util.xml.getNodeValue(v,"allow_flash_file_type");if(0<kb.length)for(var lb=kb.split(","),lc=lb.length,n=0;n<lc;n++)a.allowFlashFileType.push(lb[n]);else a.allowFlashFileType=["swf"];var mb=DEXT5.util.xml.getNodeValue(v,"allow_insert_file_type");if(0<mb.length)for(var nb=mb.split(","),mc=nb.length,n=0;n<mc;n++)a.allowInsertFileType.push(nb[n]);
else a.allowInsertFileType="txt doc docx xls xlsx ppt pptx hwp pdf".split(" ");"0"==DEXT5.util.xml.getNodeValue(v,"attach_file_image")&&(a.attachFileImage="0");var O=DEXT5.util.xml.getNode(d,"file_delimiter");""!=DEXT5.config.UnitDelimiter?a.unitDelimiter=String.fromCharCode(DEXT5.config.UnitDelimiter):O&&O.getAttribute("unit_delimiter")&&""!=O.getAttribute("unit_delimiter")&&(a.unitDelimiter=String.fromCharCode(O.getAttribute("unit_delimiter")));""!=DEXT5.config.UnitDelimiter?a.unitAttributeDelimiter=
String.fromCharCode(DEXT5.config.UnitAttributeDelimiter):O&&O.getAttribute("unit_attribute_delimiter")&&""!=O.getAttribute("unit_attribute_delimiter")&&(a.unitAttributeDelimiter=String.fromCharCode(O.getAttribute("unit_attribute_delimiter")));var xa=DEXT5.util.xml.getNode(d,"inoutdent");xa&&xa.getAttribute("default_size")&&(a.inoutdentDefaultSize=xa.getAttribute("default_size"));var p=DEXT5.util.xml.getNode(d,"table_property");p&&(p.getAttribute("width")&&""!=p.getAttribute("width")&&(a.tableDefaultWidth=
p.getAttribute("width")),p.getAttribute("height")&&""!=p.getAttribute("height")&&(a.tableDefaultHeight=p.getAttribute("height")),p.getAttribute("class")&&""!=p.getAttribute("class")&&(a.tableDefaultClass=p.getAttribute("class")),p.getAttribute("inoutdent")&&""!=p.getAttribute("inoutdent")&&(a.tableDefaultInoutdent=p.getAttribute("inoutdent")),p.getAttribute("init_inoutdent")&&""!=p.getAttribute("init_inoutdent")&&(a.tableInitInoutdent=p.getAttribute("init_inoutdent")),p.getAttribute("td_height")&&
""!=p.getAttribute("td_height")&&(a.tableDefaultTdHeight=p.getAttribute("td_height")),p.getAttribute("row_max_count")&&""!=p.getAttribute("row_max_count")&&(a.tableRowMaxCount=p.getAttribute("row_max_count")),p.getAttribute("col_max_count")&&""!=p.getAttribute("col_max_count")&&(a.tableColMaxCount=p.getAttribute("col_max_count")),p.getAttribute("allow_inoutdent_text")&&""!=p.getAttribute("allow_inoutdent_text")&&(a.allowInoutdentText=p.getAttribute("allow_inoutdent_text")),p.getAttribute("default_border_color")&&
""!=p.getAttribute("default_border_color")&&(a.defaultBorderColor=p.getAttribute("default_border_color")));var ob=DEXT5.util.xml.getNodeValue(p,"class_list");if(0<ob.length)for(var pb=ob.split(","),nc=pb.length,n=0;n<nc;n++)a.tableClassList.push(pb[n]);var qb=DEXT5.util.xml.getNodeValue(p,"show_line_for_border_none");"0"!=qb&&(a.showLineForBorderNone=qb);var rb=DEXT5.util.xml.getNodeValue(p,"line_style");if(0<rb.length)for(var sb=rb.split(","),oc=sb.length,n=0;n<oc;n++)a.tableLineStyleList.push(sb[n]);
var ya=DEXT5.util.xml.getNode(d,"hyperlink_property"),tb=DEXT5.util.xml.getNodeValue(ya,"target");if(0<tb.length)for(var ub=tb.split(","),pc=ub.length,n=0;n<pc;n++)a.hyperlinkTargetList.push(ub[n]);var vb=DEXT5.util.xml.getNodeValue(ya,"category");if(0<vb.length)for(var wb=vb.split(","),qc=wb.length,n=0;n<qc;n++)a.hyperlinkCategoryList.push(wb[n]);var xb=DEXT5.util.xml.getNodeValue(ya,"protocol");if(0<xb.length)for(var yb=xb.split(","),rc=yb.length,n=0;n<rc;n++)a.hyperlinkProtocolList.push(yb[n]);
var zb=DEXT5.util.xml.getNodeValue(p,"no_resize_class");0<zb.length&&(a.tableNoResizeClass=zb);var Ab=DEXT5.util.xml.getNodeValue(p,"no_selection_class");0<Ab.length&&(a.tableNoSelectionClass=Ab);var Bb=DEXT5.util.xml.getNodeValue(p,"no_action_class");0<Bb.length&&(a.tableNoActionClass=Bb);var U=DEXT5.util.xml.getNode(d,"img_default_size");U&&U.getAttribute("width")&&(a.imgDefaultWidth=U.getAttribute("width"));U&&U.getAttribute("height")&&(a.imgDefaultHeight=U.getAttribute("height"));var F=DEXT5.util.xml.getNode(d,
"img_default_margin");F&&(F.getAttribute("margin_left")&&(a.imgDefaultMarginLeft=F.getAttribute("margin_left")),F.getAttribute("margin_right")&&(a.imgDefaultMarginRight=F.getAttribute("margin_right")),F.getAttribute("margin_top")&&(a.imgDefaultMarginTop=F.getAttribute("margin_top")),F.getAttribute("margin_bottom")&&(a.imgDefaultMarginBottom=F.getAttribute("margin_bottom")));a.style.width=""==DEXT5.config.Width?0==m.length?a.style.width:m:DEXT5.config.Width;a.style.height=""==DEXT5.config.Height?0==
t.length?a.style.height:t:DEXT5.config.Height;a.style.skinName=""==DEXT5.config.SkinName?0==q.length?a.style.skinName:q:DEXT5.config.SkinName;if("random"==a.style.skinName){var sc=Math.floor(11*Math.random()),tc=DEXT5.util.getSkinNames();a.style.skinName=tc[sc]}a.defaultMessage=""==DEXT5.config.DefaultMessage?"":DEXT5.config.DefaultMessage;a.firstLoadType=""==DEXT5.config.FirstLoadType?"":DEXT5.config.FirstLoadType;a.firstLoadMessage=""==DEXT5.config.FirstLoadMessage?"":DEXT5.config.FirstLoadMessage;
a.fileFieldID=""==DEXT5.config.FileFieldID?"Filedata":DEXT5.config.FileFieldID;a.nextTabElementId=""==DEXT5.config.NextTabElementId?"":DEXT5.config.NextTabElementId;a.userFieldID=""==DEXT5.config.UserFieldID?"Userdata":DEXT5.config.UserFieldID;a.userFieldValue=DEXT5.config.UserFieldValue;a.toSavePathURL=""==DEXT5.config.ToSavePathURL?0==db.length?a.toSavePathURL:db:DEXT5.config.ToSavePathURL;a.toSaveFilePathURL=""==DEXT5.config.ToSaveFilePathURL?0==eb.length?a.toSaveFilePathURL:eb:DEXT5.config.ToSaveFilePathURL;
a.sourceViewtype="1"==u||"2"==u?u:"0";var Cb=DEXT5.util.xml.getNode(d,"source_viewtype");Cb&&"1"==Cb.getAttribute("use_selection_mark")&&(a.useSelectionMark="1");"1"==a.useSelectionMark&&(a.sourceViewtype="2");5<H.length&&"http"==H.substring(0,4).toLowerCase()?(a.userCssUrl=H,la&&la.getAttribute("always_set")&&(a.userCssAlwaysSet=la.getAttribute("always_set"))):a.userCssUrl="";5<I.length&&"http"==I.substring(0,4).toLowerCase()?a.userJsUrl=I:a.userJsUrl="";a.xhtml_value="1"==P?"1":"0";""!=W&&(a.system_title=
"0"==W?"":W);if(""!=DEXT5.config.ViewModeAutoHeight)a.view_mode_auto_height=DEXT5.config.ViewModeAutoHeight;else{var Db=DEXT5.util.xml.getNodeValue(d,"view_mode_auto_height");""!=Db&&(a.view_mode_auto_height=Db)}if(""!=DEXT5.config.ViewModeAutoWidth)a.view_mode_auto_width=DEXT5.config.ViewModeAutoWidth;else{var Eb=DEXT5.util.xml.getNodeValue(d,"view_mode_auto_width");""!=Eb&&(a.view_mode_auto_width=Eb)}""!=DEXT5.config.ChangeMultiValueMode&&(a.changeMultiValueMode=DEXT5.config.ChangeMultiValueMode);
"0"==Da&&(a.tableAutoAdjust="0");var Fb=DEXT5.util.xml.getNodeValue(d,"allow_link_media_caption");"1"==DEXT5.config.AllowLinkMediaCaption?a.allowLinkMediaCaption=DEXT5.config.AllowLinkMediaCaption:"1"==Fb&&(a.allowLinkMediaCaption=Fb);var za=DEXT5.util.xml.getNodeValue(d,"user_help_url");""!=DEXT5.config.UserHelpUrl&&"http"==DEXT5.config.UserHelpUrl.substring(0,4).toLowerCase()?a.userHelpUrl=DEXT5.config.UserHelpUrl:za&&"http"==za.substring(0,4).toLowerCase()&&(a.userHelpUrl=za);""!=a.userHelpUrl&&
("/"!=a.userHelpUrl.substring(a.userHelpUrl.length-1,a.userHelpUrl.length)&&(a.userHelpUrl+="/"),a.webPath.help=a.userHelpUrl);""!=DEXT5.config.ImgUploadContenttype?a.imgUploadContenttype="1"==DEXT5.config.ImgUploadContenttype?"1":"0":"1"==DEXT5.util.xml.getNodeValue(d,"img_upload_contenttype")?a.imgUploadContenttype="1":a.imgUploadContenttype="0";0<DEXT5.config.mimeCharset.length&&(a.mimeCharset=DEXT5.config.mimeCharset);0<DEXT5.config.mimeConentEncodingType.length&&(a.mimeConentEncodingType=DEXT5.config.mimeConentEncodingType);
0<DEXT5.config.mimeLocalOnly.length&&(a.mimeLocalOnly=DEXT5.config.mimeLocalOnly);0<DEXT5.config.mimeRemoveHeader.length&&(a.mimeRemoveHeader=DEXT5.config.mimeRemoveHeader);0<DEXT5.config.mimeFileTypeFilter.length&&(a.mimeFileTypeFilter=DEXT5.config.mimeFileTypeFilter);0<DEXT5.config.userOpenDlgTitle.length&&(a.userOpenDlgTitle=DEXT5.config.userOpenDlgTitle);0<DEXT5.config.userOpenDlgType.length&&(a.userOpenDlgType=DEXT5.config.userOpenDlgType);0<DEXT5.config.userOpenDlgInitDir.length&&(a.userOpenDlgInitDir=
DEXT5.config.userOpenDlgInitDir);0<DEXT5.config.userImageDlgStyle.length&&(a.userImageDlgStyle=DEXT5.config.userImageDlgStyle);0<DEXT5.config.mimeBaseURL.length&&(a.mimeBaseURL=DEXT5.config.mimeBaseURL);""!=DEXT5.config.ShowDialogPosition?a.showDialogPosition=DEXT5.config.ShowDialogPosition:""!=A&&(a.showDialogPosition=A);""!=DEXT5.config.StatusBarItem&&(a.statusBarItem=DEXT5.config.StatusBarItem);""!=DEXT5.config.StatusBarItemTitle&&(a.statusBarTitle=DEXT5.config.StatusBarItemTitle.split(","));r=
r.toLowerCase();a.lang=""==r?"ko-kr":DEXT5.util.getUserLang(r);2<=DEXT5.config.InitLang.length&&(a.lang=DEXT5.util.getUserLang(DEXT5.config.InitLang));2<=DEXT5.config.Lang.length&&(a.lang=DEXT5.util.getUserLang(DEXT5.config.Lang));a.accessibility=0==y.length?"0":y;var V=DEXT5.util.xml.getNode(d,"accessibility");""==DEXT5.config.AccessibilityValidationItems?(V&&V.getAttribute("validation_item")&&(a.accessibilityValidationItems=V.getAttribute("validation_item")),V&&V.getAttribute("tab_sequence_mode")&&
(a.tabSequenceMode=V.getAttribute("tab_sequence_mode"))):a.accessibilityValidationItems=DEXT5.config.AccessibilityValidationItems;if(""!=DEXT5.config.SaveFolderNameRule)a.saveFolderNameRule=DEXT5.config.SaveFolderNameRule;else if("YYYYMMDD/"==M||"YYYYMM/"==M||"YYYY/"==M||"YYYY/MM/"==M||"YYYY/MM/DD/"==M||"/"==M||""==M)a.saveFolderNameRule=M;if(""!=DEXT5.config.SaveFileFolderNameRule)a.saveFileFolderNameRule=DEXT5.config.SaveFileFolderNameRule;else if("YYYYMMDD/"==N||"YYYYMM/"==N||"YYYY/"==N||"YYYY/MM/"==
N||"YYYY/MM/DD/"==N||"/"==N||""==N)a.saveFileFolderNameRule=N;if("GUID"==wa||"DATETIME"==wa)a.saveFileNameRule=wa;var Gb=DEXT5.util.xml.getNodeValue(d,"topmenu"),Z=DEXT5.util.xml.getNodeValue(d,"toolbar"),Hb=DEXT5.util.xml.getNodeValue(d,"toolbaradmin"),Ib=DEXT5.util.xml.getNodeValue(d,"topstatusbar"),Jb=DEXT5.util.xml.getNodeValue(d,"statusbar"),Kb=DEXT5.util.xml.getNodeValue(d,"resizebar");a.top_menu="1"==Gb?Gb:"0";a.tool_bar="1"==Z||"2"==Z||"3"==Z||"4"==Z?Z:"0";if(""!=DEXT5.config.ToolBarGrouping)a.tool_bar_grouping=
DEXT5.config.ToolBarGrouping;else{var ha=DEXT5.util.xml.getNode(d,"toolbar");ha&&ha.getAttribute("grouping")&&""!=ha.getAttribute("grouping")&&(a.tool_bar_grouping=ha.getAttribute("grouping"))}a.top_status_bar=""!=Ib?Ib:"1";a.status_bar="1"==Jb?Jb:"0";a.resize_bar="1"==Kb?Kb:"0";a.tool_bar_admin="1"==Hb?Hb:"0";""!=DEXT5.config.zTopMenu&&(a.top_menu=DEXT5.config.zTopMenu);""!=DEXT5.config.zToolBar&&(a.tool_bar=DEXT5.config.zToolBar);""!=DEXT5.config.zTopStatusBar&&(a.top_status_bar=DEXT5.config.zTopStatusBar);
""!=DEXT5.config.zStatusBar&&(a.status_bar=DEXT5.config.zStatusBar);if(""!=DEXT5.config.StatusBarLoading)a.statusBarLoading=DEXT5.config.StatusBarLoading;else{var ia=DEXT5.util.xml.getNode(d,"statusbar");ia&&ia.getAttribute("loading")&&""!=ia.getAttribute("loading")&&(a.statusBarLoading=ia.getAttribute("loading"))}if(""!=DEXT5.config.TopStatusBarLoading)a.topStatusBarLoading=DEXT5.config.TopStatusBarLoading;else{var ja=DEXT5.util.xml.getNode(d,"topstatusbar");ja&&ja.getAttribute("loading")&&""!=ja.getAttribute("loading")&&
(a.topStatusBarLoading=ja.getAttribute("loading"))}""!=DEXT5.config.HasContainer&&(a.hasContainer=DEXT5.config.HasContainer);""!=DEXT5.config.Mode?a.mode=DEXT5.config.Mode:"view"==DEXT5.util.xml.getNodeValue(d,"default_mode")&&(a.mode="view");var aa="",aa=0==C.length?DEXT5.rootPath:"/"==C.substring(0,1)?location.protocol+"//"+location.host:4<C.length&&"http"==C.substring(0,4).toLowerCase()?"":DEXT5.rootPath;a.style.InitVisible=DEXT5.config.InitVisible;""!=DEXT5.config.DevelopLangage?a.developLang=
DEXT5.config.DevelopLangage:0<L.length&&(a.developLang=L);if("user"!=a.developLang.toLowerCase())if(""!=DEXT5.config.Security.EncryptParam)a.security.encryptParam="1"==DEXT5.config.Security.EncryptParam?"1":"0";else{var Lb=DEXT5.util.xml.getNode(d,"security");if(Lb){var uc=DEXT5.util.xml.getNodeValue(Lb,"encrypt_param");a.security.encryptParam="1"==uc?"1":"0"}}var Aa=!1;if(DEXT5.isRelease&&("1"==DEXT5.config.UseGZip?Aa=!0:"1"==DEXT5.util.xml.getNodeValue(d,"use_gzip")&&(Aa=!0),1==Aa))switch(a.developLang.toUpperCase()){case "JAVA":case "JSP":a.editor_url=
DEXT5.rootPath+"pages/editor_release_java.html";break;case "PHP":a.editor_url=DEXT5.rootPath+"pages/editor_release_php.html";break;default:a.editor_url=DEXT5.rootPath+"pages/editor_release_net.html"}if(0==C.length)switch(a.developLang.toUpperCase()){case "JAVA":case "JSP":a.post_url=aa+"handler/upload_handler.jsp";break;case "PHP":a.post_url=aa+"handler/upload_handler.php";break;default:a.post_url=aa+"handler/upload_handler.ashx"}else{if(4<C.length&&"http"==C.substring(0,4).toLowerCase()&&C.match(/:\/\/(.[^\/]+)/)[1]!=
window.location.host){var ka="";switch(L.toUpperCase()){case "JAVA":case "JSP":ka=DEXT5.rootPath+"handler/upload_handler.jsp";break;case "PHP":ka=DEXT5.rootPath+"handler/upload_handler.php";break;default:ka=DEXT5.rootPath+"handler/upload_handler.ashx"}a.proxy_url=ka}a.post_url=aa+C}""!=a.userFieldValue&&(-1<a.post_url.indexOf("?")?a.post_url=a.post_url+"&"+a.userFieldID+"="+a.userFieldValue:a.post_url=a.post_url+"?"+a.userFieldID+"="+a.userFieldValue);""!=DEXT5.config.focusInitObjId&&(a.focusInitObjId=
DEXT5.config.focusInitObjId);""!=DEXT5.config.focusInitEditorObjId&&(a.focusInitEditorObjId=DEXT5.config.focusInitEditorObjId);""!=DEXT5.config.tabIndexObjId&&(a.tabIndexObjId=DEXT5.config.tabIndexObjId);""!=DEXT5.config.SetValueObjId&&(a.setValueObjId=DEXT5.config.SetValueObjId);""!=DEXT5.config.LoadedEvent&&(a.LoadedEvent=DEXT5.config.LoadedEvent);""!=DEXT5.config.DirectEditHtmlUrl&&(a.directEditHtmlUrl=DEXT5.config.DirectEditHtmlUrl);var z=DEXT5.util.xml.getNode(e,"license"),vc=DEXT5.util.xml.getNodeValue(z,
"product_key"),Mb=DEXT5.util.xml.getNodeValue(z,"license_plugin"),Nb=DEXT5.util.xml.getNodeValue(z,"plugin_use"),Ob=DEXT5.util.xml.getNodeValue(z,"image_editor_use"),Ba=DEXT5.util.xml.getNodeValue(z,"plugin_version"),wc=DEXT5.util.xml.getNodeValue(z,"print_preview"),Pb=DEXT5.util.xml.getNodeValue(z,"print_header"),Qb=DEXT5.util.xml.getNodeValue(z,"print_footer"),Ca=DEXT5.util.xml.getNode(z,"mime_use"),Rb=DEXT5.util.xml.getNodeValue(z,"mime_use"),xc=DEXT5.util.xml.getNodeValue(z,"trust_sites"),Sb=
DEXT5.util.xml.getNodeValue(z,"print_margin_ltrb");""!=DEXT5.config.PrintMarginltrb&&(Sb=DEXT5.config.PrintMarginltrb);a.printMarginltrb=Sb;a.LicenseKey=""!=DEXT5.config.LicenseKey?DEXT5.config.LicenseKey:DEXT5.util.xml.getNodeValue(z,"license_key");a.printPreview="1"==wc?"1":"0";a.printHeader=Pb;a.printFooter=Qb;a.basePrintHeader=Pb;a.basePrintFooter=Qb;a.trustSites=xc;a.productKey=""!=DEXT5.config.ProductKey?DEXT5.config.ProductKey:vc;""!=Mb&&(a.plugin_root=Mb);a.plugInUse=""==DEXT5.config.pluginUse?
0==Nb.length?a.plugInUse:Nb:DEXT5.config.pluginUse;0==a.plugInUse&&"ieplugin"==a.runtimes&&(a.plugInUse=1);a.imageEditorUse=""==DEXT5.config.imageEditorUse?0==Ob.length?a.imageEditorUse:Ob:DEXT5.config.imageEditorUse;""==DEXT5.config.mimeCharset?Ca&&Ca.getAttribute("mimeCharset")&&(a.mimeCharset=Ca.getAttribute("mimeCharset")):a.mimeCharset=DEXT5.config.mimeCharset;a.mimeUse=""==DEXT5.config.mimeUse?0==Rb.length?a.mimeUse:Rb:DEXT5.config.mimeUse;null!=Ba&&7<=Ba.length&&(a.plugin_version=Ba);if(""==
a.proxy_url&&("NET"==L.toUpperCase()||"JSP"==L.toUpperCase()||"JAVA"==L.toUpperCase()||"PHP"==L.toUpperCase()||"ASP"==L.toUpperCase())){var ba=a.post_url;""!=a.userFieldValue&&(ba=a.post_url.split("?")[0]);var Tb=ba+"?dext=test";"CCODE_001"==a.custom_code&&(Tb=ba+"?hello=test");DEXT5.ajax.load(Tb,function(b){if(null==b||""==b){b="";var c=0<DEXT5.config.InitXml.length?c:"dext_editor.xml";"ko"==a.lang||"ko-kr"==a.lang?(b="Editor\uc758 \uc124\uc815\uac12\uc774 \uc62c\ubc14\ub974\uc9c0 \uc54a\uc2b5\ub2c8\ub2e4. \uc544\ub798 URL \uc811\uadfc\uc774 \uc720\ud6a8\ud558\uc9c0 \uc54a\uc2b5\ub2c8\ub2e4.\n\n"+
(ba+"\n\n"),b+=c+" \ud30c\uc77c\uc758 uploader_setting \uc139\uc158\uc758 <develop_langage>\uc640 <handler_url> \uc124\uc815\uac12\uc744 \ud655\uc778\ud558\uc138\uc694."):(b="Editor's setting is not correct. Access the following URL is not valid.\n\n"+(ba+"\n\n"),b+='Please check the settings, <handler_url> and <develop_langage> in "uploader_setting" section in the "'+c+'."');alert(b)}else b=b.toLowerCase(),-1<b.indexOf("hi, dext5 editor !!!!")&&-1<b.indexOf("-")&&(DEXT5.ServerReleaseVer=b.split("-")[1])})}a.useLog=
"1"==DEXT5.config.useLog?"1":"0";this.editor=null;a.editor_id=b;this.FrameID="dext_frame_"+b;a.holderID="dext_frame_holder"+b;this.ID=b;var G="",Ub=a.style.height;0==a.style.InitVisible&&(Ub="1px");G='<div id="'+a.holderID+'" style="width:'+a.style.width+"; height:"+Ub+"; ";if(DEXT5.browser.iOS||DEXT5.browser.mobile)G="view"==a.mode&&"1"==a.view_mode_auto_height?G+" overflow:hidden;":G+" overflow:scroll; overflow-x:hidden; -webkit-overflow-scrolling:touch; ";G+='"></div>';if(""!=DEXT5.config.EditorHolder){var Vb=
document.getElementById(DEXT5.config.EditorHolder);Vb?Vb.innerHTML=G:document.write(G)}else document.write(G);var yc=document.getElementById(a.holderID),w;try{w=document.createElement("<iframe frameborder='0' scrolling='no'>")}catch(Ac){w=document.createElement("iframe"),w.setAttribute("frameborder","0"),w.setAttribute("scrolling","no")}w.setAttribute("id",this.FrameID);w.style.width="100%";w.style.height="100%";a.style.height.indexOf("%");if(DEXT5.browser.iOS||DEXT5.browser.mobile)w.style.overflow=
"hidden",w.style.display="inline-block";w.width="100%";w.height="100%";yc.appendChild(w);var zc=this,Wb=function(){try{w.contentWindow.dext_frame_loaded_event(b,a,zc)}catch(c){""!=DEXT5.config.LoadErrorCustomMessage?alert(DEXT5.config.LoadErrorCustomMessage):alert("ErrCode : 1001")}};w.addEventListener?w.addEventListener("load",Wb,!1):w.attachEvent&&w.attachEvent("onload",Wb);w.src=a.editor_url;""!=a.custom_code&&DEXT5.util.CustomSetting("function",a.custom_code,a)}}}
function CustomSettingFunction(b){"CCODE_001"==b.custom_code&&(b.empty_tag_remove="1",b.sourceViewtype="1",b.system_title="",b.tableAutoAdjust="0",b.accessibility="-1",b.tool_bar="2",b.top_menu="1",b.setDefaultStyle.value="2",b.setDefaultStyle.body_id="hello_body",b.emoticon_url=DEXT5.rootPath+"config/hello_emoticon.xml",b.forms_url=DEXT5.rootPath+"config/hello_formlist.xml")}
function CustomRemoveItem(b){var c=[];"CCODE_001"==b&&(c="save pagebreak copy cut paste doc_bg_image insert_link_media media_create entity iframe_create flash_create table_row_clone about insert_row_column grid tool_replace convert_table_to_text table_tool table_indent table_outdent row_property column_property align_vertical".split(" "));return c}
function replacePtOrCmToPx(b){try{for(var c=b.toLowerCase().split(" "),a=c.length,e,h,g="",f=0;f<a;f++){var k=c[f];-1<k.indexOf("pt")?(e=4*parseFloat(k)/3,0<e&&1>e&&(e=1),0>e&&(e=0),h=Math.round(e)+"px",g=""!=g?g+" "+h:h):-1<k.indexOf("cm")?(_cm=37.795275593333*parseFloat(k),0<_cm&&1>_cm&&(_cm=1),0>_cm&&(_cm=0),h=Math.round(_cm)+"px",g=""!=g?g+" "+h:h):g=""!=g?g+" "+k:k}return""!=g?g:b}catch(d){return b}}window.DEXT5&&"samsung.net"==document.domain&&(window.HELLO=window.DEXT5,HelloEditor=Dext5editor);
function GetUserRunTimeEditor(b){b=b.toLowerCase();var c="";""==b||"html5"==b?c="html5":"ieplugin"==b?c=1==DEXT5.browser.ie&&12>DEXT5.browser.ieVersion?"ieplugin":"html5":-1<b.indexOf("ieplugin")&&8<b.length?(b=DEXT5.util.parseIntOr0(b),c=1==DEXT5.browser.ie&&b>=DEXT5.browser.ieVersion?"ieplugin":"html5"):c="html5";return c};
